"""Extends mappings.json with PCI DSS and SOX correspondences and with the
rationale of every partial correspondence.

Run after build_map.py. It is idempotent: the PCI and SOX blocks and the
rationales are rewritten from the tables below; the ENS, NIS2 and DORA blocks
that build_map.py produced are left untouched.
"""
import json, pathlib
from details import DETAILS   # covers / adds / close, one module per framework

# ISO id -> (PCI DSS requirement ids, coverage). Coverage: F full, P partial, N none.
PCI = {
"5.1":(["req.12.1"],"F"),
"5.2":(["req.12.1"],"P"),
"5.3":(["req.6.5"],"P"),
"5.4":(["req.12.4"],"P"),
"5.5":(["req.12.10"],"P"),
"5.6":(["req.6.3"],"P"),
"5.7":(["req.6.3"],"P"),
"5.8":([],"N"),
"5.9":(["req.12.5"],"P"),
"5.10":(["req.12.2"],"F"),
"5.11":([],"N"),
"5.12":(["req.9.4"],"P"),
"5.13":([],"N"),
"5.14":(["req.4.2","req.9.4"],"P"),
"5.15":(["req.7.1","req.7.2"],"F"),
"5.16":(["req.8.2"],"F"),
"5.17":(["req.8.3","req.8.6"],"P"),
"5.18":(["req.7.2","req.7.3"],"P"),
"5.19":(["req.12.8"],"P"),
"5.20":(["req.12.8"],"F"),
"5.21":(["req.12.8","req.6.3"],"P"),
"5.22":(["req.12.8"],"F"),
"5.23":(["req.12.8","req.12.9"],"P"),
"5.24":(["req.12.10"],"F"),
"5.25":(["req.12.10","req.10.7"],"P"),
"5.26":(["req.12.10"],"F"),
"5.27":(["req.12.10"],"F"),
"5.28":(["req.12.10","req.10.5"],"P"),
"5.29":(["req.12.10"],"P"),
"5.30":(["req.12.10"],"P"),
"5.31":(["req.12.4","req.12.5"],"P"),
"5.32":([],"N"),
"5.33":(["req.10.5","req.3.2"],"P"),
"5.34":([],"N"),
"5.35":(["req.12.4"],"P"),
"5.36":(["req.12.4"],"P"),
"5.37":(["req.1.1","req.2.1","req.3.1","req.4.1","req.5.1","req.6.1","req.7.1","req.8.1","req.9.1","req.10.1","req.11.1"],"P"),
"6.1":(["req.12.7"],"F"),
"6.2":(["req.12.6"],"P"),
"6.3":(["req.12.6"],"F"),
"6.4":([],"N"),
"6.5":(["req.8.2"],"P"),
"6.6":([],"N"),
"6.7":(["req.1.5","req.8.4"],"P"),
"6.8":(["req.12.10"],"P"),
"7.1":(["req.9.2"],"F"),
"7.2":(["req.9.2","req.9.3"],"F"),
"7.3":(["req.9.2"],"P"),
"7.4":(["req.9.2"],"P"),
"7.5":([],"N"),
"7.6":(["req.9.3"],"P"),
"7.7":([],"N"),
"7.8":(["req.9.2","req.9.5"],"P"),
"7.9":(["req.9.4","req.9.5"],"P"),
"7.10":(["req.9.4"],"F"),
"7.11":([],"N"),
"7.12":(["req.9.2"],"P"),
"7.13":(["req.9.5"],"P"),
"7.14":(["req.9.4"],"F"),
"8.1":(["req.1.5","req.12.2"],"P"),
"8.2":(["req.7.2","req.8.6"],"P"),
"8.3":(["req.7.2","req.7.3","req.3.4"],"P"),
"8.4":(["req.7.2"],"P"),
"8.5":(["req.8.3","req.8.4","req.8.5"],"P"),
"8.6":([],"N"),
"8.7":(["req.5.2","req.5.3","req.5.4"],"P"),
"8.8":(["req.6.3","req.11.3"],"P"),
"8.9":(["req.2.2","req.2.3"],"F"),
"8.10":(["req.3.2","req.3.3"],"P"),
"8.11":(["req.3.4","req.3.5"],"P"),
"8.12":(["req.3.4","req.4.2"],"P"),
"8.13":(["req.9.4"],"P"),
"8.14":([],"N"),
"8.15":(["req.10.2","req.10.3","req.10.5"],"P"),
"8.16":(["req.10.4","req.10.7","req.11.5"],"P"),
"8.17":(["req.10.6"],"F"),
"8.18":(["req.2.2","req.7.2"],"P"),
"8.19":(["req.2.2","req.6.5","req.12.2"],"P"),
"8.20":(["req.1.2","req.1.4","req.11.2"],"P"),
"8.21":(["req.1.2","req.2.2"],"P"),
"8.22":(["req.1.3","req.1.4","req.11.4"],"P"),
"8.23":(["req.1.3"],"P"),
"8.24":(["req.3.5","req.3.6","req.3.7","req.4.2"],"P"),
"8.25":(["req.6.2"],"F"),
"8.26":(["req.6.2","req.6.4","req.11.6"],"P"),
"8.27":(["req.1.2","req.6.2"],"P"),
"8.28":(["req.6.2"],"F"),
"8.29":(["req.6.2","req.6.4","req.11.3","req.11.4"],"P"),
"8.30":(["req.6.2","req.12.8"],"P"),
"8.31":(["req.6.5"],"F"),
"8.32":(["req.6.5","req.12.5"],"P"),
"8.33":(["req.6.5"],"F"),
"8.34":([],"N"),
}

# ISO id -> (SOX / ITGC ids, coverage)
SOX = {
"5.1":(["elc.3"],"F"),
"5.2":(["elc.1"],"F"),
"5.3":(["acc.6"],"F"),
"5.4":(["elc.1"],"P"),
"5.5":([],"N"),
"5.6":([],"N"),
"5.7":([],"N"),
"5.8":(["dev.1"],"P"),
"5.9":(["elc.2"],"P"),
"5.10":(["elc.3"],"P"),
"5.11":(["acc.2"],"P"),
"5.12":([],"N"),
"5.13":([],"N"),
"5.14":(["ops.1"],"P"),
"5.15":(["acc.1","acc.6"],"F"),
"5.16":(["acc.1","acc.2"],"F"),
"5.17":(["acc.5"],"F"),
"5.18":(["acc.1","acc.2","acc.3"],"F"),
"5.19":(["elc.5"],"P"),
"5.20":(["elc.5"],"P"),
"5.21":([],"N"),
"5.22":(["elc.5"],"P"),
"5.23":(["elc.5"],"P"),
"5.24":(["ops.3"],"P"),
"5.25":(["ops.3"],"P"),
"5.26":(["ops.3"],"P"),
"5.27":(["ops.3"],"P"),
"5.28":([],"N"),
"5.29":(["ops.4"],"P"),
"5.30":(["ops.4"],"F"),
"5.31":(["sec.302","sec.404"],"P"),
"5.32":([],"N"),
"5.33":(["sec.802"],"P"),
"5.34":([],"N"),
"5.35":(["elc.4","sec.404"],"P"),
"5.36":(["elc.4"],"P"),
"5.37":(["elc.3","ops.1"],"P"),
"6.1":([],"N"),
"6.2":([],"N"),
"6.3":(["elc.1"],"P"),
"6.4":([],"N"),
"6.5":(["acc.2"],"P"),
"6.6":([],"N"),
"6.7":(["acc.5"],"P"),
"6.8":(["ops.3"],"P"),
"7.1":(["acc.7"],"F"),
"7.2":(["acc.7"],"F"),
"7.3":(["acc.7"],"P"),
"7.4":(["acc.7"],"P"),
"7.5":(["ops.4"],"P"),
"7.6":(["acc.7"],"P"),
"7.7":([],"N"),
"7.8":(["acc.7"],"P"),
"7.9":([],"N"),
"7.10":(["ops.2"],"P"),
"7.11":(["ops.4"],"P"),
"7.12":([],"N"),
"7.13":([],"N"),
"7.14":([],"N"),
"8.1":([],"N"),
"8.2":(["acc.4","acc.9"],"F"),
"8.3":(["acc.1","acc.9"],"F"),
"8.4":(["chg.3"],"P"),
"8.5":(["acc.5"],"F"),
"8.6":([],"N"),
"8.7":([],"N"),
"8.8":(["chg.5"],"P"),
"8.9":(["chg.5"],"F"),
"8.10":([],"N"),
"8.11":([],"N"),
"8.12":([],"N"),
"8.13":(["ops.2"],"F"),
"8.14":(["ops.4"],"P"),
"8.15":(["acc.8"],"F"),
"8.16":(["acc.8"],"F"),
"8.17":(["acc.8"],"P"),
"8.18":(["acc.9"],"F"),
"8.19":(["chg.3","chg.5"],"F"),
"8.20":([],"N"),
"8.21":([],"N"),
"8.22":([],"N"),
"8.23":([],"N"),
"8.24":([],"N"),
"8.25":(["dev.1"],"F"),
"8.26":(["dev.1"],"P"),
"8.27":(["dev.1"],"P"),
"8.28":(["dev.1"],"P"),
"8.29":(["chg.2","dev.3"],"F"),
"8.30":(["dev.1","elc.5"],"P"),
"8.31":(["chg.3"],"F"),
"8.32":(["chg.1","chg.2","chg.4","chg.5"],"F"),
"8.33":(["chg.2"],"P"),
"8.34":([],"N"),
}

# (ISO id, framework key) -> (why the correspondence is only partial, EN / ES).
# Written for every block whose coverage is "partial": what the other regime
# asks for that the ISO control does not give, or where it is narrower.
R = {
# ---- ENS ------------------------------------------------------------------
("5.2","ens"):("org.3 asks for a formal authorisation procedure with named signatories for each kind of decision, beyond assigning roles.",
               "org.3 exige un procedimiento formal de autorizacion con firmantes designados para cada tipo de decision, mas alla de asignar roles."),
("5.4","ens"):("org.1 requires the security policy to be approved by the governing body and to name the responsible roles explicitly; management support alone is not enough.",
               "org.1 exige que la politica la apruebe el organo superior y que nombre explicitamente los roles responsables; el respaldo de la direccion no basta."),
("5.5","ens"):("op.exp.7 requires notifying the CCN-CERT (or the competent CSIRT) of incidents under Art. 33, with the timing and channel the ENS sets; ISO only asks to know whom to call.",
               "op.exp.7 obliga a notificar al CCN-CERT (o al CSIRT competente) los incidentes segun el art. 33, con los plazos y el canal que fija el ENS; ISO solo pide saber a quien llamar."),
("5.7","ens"):("op.mon.3 asks for continuous surveillance and the consumption of threat feeds integrated with monitoring; it is an operational measure, not the analytical process ISO describes.",
               "op.mon.3 pide vigilancia continua y consumo de fuentes de amenazas integradas con la monitorizacion; es una medida operativa, no el proceso analitico que describe ISO."),
("5.8","ens"):("op.pl.2 and org.4 require a security architecture and an authorisation process for new systems, which is narrower than embedding security in every project.",
               "op.pl.2 y org.4 exigen una arquitectura de seguridad y un proceso de autorizacion para los sistemas nuevos, algo mas estrecho que integrar la seguridad en todo proyecto."),
("5.10","ens"):("mp.per.2 and mp.eq.1 fix the duties of users and a clear desk rule; they do not constitute a general acceptable-use policy for information and assets.",
                "mp.per.2 y mp.eq.1 fijan los deberes de los usuarios y una regla de puesto despejado; no constituyen una politica general de uso aceptable de la informacion y los activos."),
("5.11","ens"):("mp.if.7 only registers equipment entering and leaving the premises; it says nothing about recovering information or credentials when a person leaves.",
                "mp.if.7 solo registra la entrada y salida de equipamiento de las instalaciones; no dice nada de recuperar informacion o credenciales cuando una persona se va."),
("5.14","ens"):("The ENS splits transfer into measures per channel (mp.com.2/3 network confidentiality and integrity, mp.s.1 e-mail, mp.si.4 media transport) with concrete requirements that grow with the category; ISO has one policy-level control.",
                "El ENS descompone la transferencia en medidas por canal (mp.com.2/3 confidencialidad e integridad en red, mp.s.1 correo, mp.si.4 transporte de soportes) con exigencias concretas que crecen con la categoria; ISO tiene un unico control de nivel politica."),
("5.31","ens"):("org.2 and mp.info.1 cover the security regulations and personal data; the ENS is itself a legal obligation with its own compliance regime (Art. 27, conformity), which ISO cannot supply.",
                "org.2 y mp.info.1 cubren la normativa de seguridad y los datos personales; el ENS es en si mismo una obligacion legal con su propio regimen de conformidad (art. 27), que ISO no puede aportar."),
("5.33","ens"):("op.exp.8 and mp.info.6 protect activity logs and backups; the ENS does not have a general records-protection measure, and its retention periods come from the sectoral law of each entity.",
                "op.exp.8 y mp.info.6 protegen los registros de actividad y las copias; el ENS no tiene una medida general de proteccion de registros y sus plazos de conservacion vienen de la normativa sectorial de cada entidad."),
("5.35","ens"):("The ENS requires a formal audit every two years by an accredited body (Art. 31, Annex III) and self-assessment for basic systems; op.pl.1 and op.mon.2 supply the risk analysis and metrics that feed it. ISO's independent review has no fixed cycle or accreditation.",
                "El ENS exige una auditoria formal cada dos anos por una entidad acreditada (art. 31, Anexo III) y autoevaluacion en sistemas de categoria basica; op.pl.1 y op.mon.2 aportan el analisis de riesgos y las metricas que la alimentan. La revision independiente de ISO no tiene ciclo fijo ni acreditacion."),
("5.36","ens"):("org.2 and org.4 give the rules and the authorisation process; the ENS verifies compliance through the Declaration or Certificate of Conformity, not through management review.",
                "org.2 y org.4 aportan la normativa y el proceso de autorizacion; el ENS verifica el cumplimiento mediante la Declaracion o Certificacion de Conformidad, no mediante la revision de la direccion."),
("6.5","ens"):("mp.per.2 states the duties of personnel while in post; it does not deal with obligations that survive the end or change of the relationship.",
               "mp.per.2 recoge los deberes del personal mientras esta en el puesto; no trata las obligaciones que perduran tras el fin o el cambio de la relacion."),
("6.7","ens"):("mp.eq.3 and op.acc.5 protect portable devices and set the authentication mechanism, with stronger requirements per category; there is no measure about the remote-working arrangement itself (home environment, rules, support).",
               "mp.eq.3 y op.acc.5 protegen los dispositivos portatiles y fijan el mecanismo de autenticacion, con exigencias mayores por categoria; no hay medida sobre el trabajo a distancia en si (entorno, reglas, soporte)."),
("6.8","ens"):("op.exp.7 asks for an incident management process; the internal reporting channel for personnel is implied, not required as such.",
               "op.exp.7 pide un proceso de gestion de incidentes; el canal interno de notificacion para el personal se sobreentiende, no se exige como tal."),
("7.4","ens"):("mp.if.2 requires identifying and registering people who enter; it does not require continuous surveillance (cameras, alarms) of the premises.",
               "mp.if.2 exige identificar y registrar a las personas que entran; no exige vigilancia continua (camaras, alarmas) de las instalaciones."),
("7.6","ens"):("mp.if.1 separates areas and controls entry; it has no rules for how to work inside a secure area.",
               "mp.if.1 separa areas y controla la entrada; no tiene reglas sobre como se trabaja dentro de un area segura."),
("7.12","ens"):("mp.if.3 conditions the premises (power, temperature, cabling) generically; it does not address interception or interference on cables.",
                "mp.if.3 acondiciona los locales (energia, temperatura, cableado) de forma generica; no trata la interceptacion o la interferencia en los cables."),
("7.13","ens"):("op.exp.4 governs maintenance and updates of the equipment's software; physical maintenance and its security conditions are not addressed.",
                "op.exp.4 rige el mantenimiento y las actualizaciones del software de los equipos; el mantenimiento fisico y sus condiciones de seguridad no se tratan."),
("8.4","ens"):("mp.sw.1 sets conditions for developing applications; restricting access to source code and repositories is not among them.",
               "mp.sw.1 fija condiciones para el desarrollo de aplicaciones; restringir el acceso al codigo fuente y a los repositorios no esta entre ellas."),
("8.12","ens"):("mp.info.5 cleans metadata from documents and mp.com.2 protects confidentiality on the network; neither is a data-leakage detection and blocking measure.",
                "mp.info.5 limpia los metadatos de los documentos y mp.com.2 protege la confidencialidad en la red; ninguna es una medida de deteccion y bloqueo de fugas de datos."),
("8.18","ens"):("op.acc.4 and op.exp.2 manage rights and secure configuration; the ENS does not single out privileged utility programs as a control of their own.",
                "op.acc.4 y op.exp.2 gestionan derechos y configuracion segura; el ENS no singulariza los programas de utilidad privilegiados como control propio."),
("8.28","ens"):("mp.sw.1 asks for a secure development methodology; it does not prescribe secure coding rules or their verification.",
                "mp.sw.1 pide una metodologia de desarrollo seguro; no prescribe reglas de codificacion segura ni su verificacion."),
("8.30","ens"):("mp.sw.1 and op.ext.1 set conditions for development and for contracting with service levels; supervising an external developer's process is not addressed as such.",
                "mp.sw.1 y op.ext.1 fijan condiciones para el desarrollo y para la contratacion con niveles de servicio; supervisar el proceso de un desarrollador externo no se trata como tal."),
("8.31","ens"):("mp.sw.2 requires acceptance testing before going live; separating development, test and production environments is implied only for higher categories.",
                "mp.sw.2 exige pruebas de aceptacion antes de la puesta en servicio; la separacion de entornos de desarrollo, prueba y produccion solo se implica en las categorias superiores."),
("8.33","ens"):("mp.sw.2 governs acceptance testing; it does not require protecting or anonymising the data used in tests.",
                "mp.sw.2 rige las pruebas de aceptacion; no exige proteger ni anonimizar los datos usados en las pruebas."),
("8.34","ens"):("op.pl.1 plans the risk analysis; protecting production systems during audit tests is not an ENS measure.",
                "op.pl.1 planifica el analisis de riesgos; proteger los sistemas en produccion durante las pruebas de auditoria no es una medida del ENS."),
# ---- NIS2 -----------------------------------------------------------------
("5.3","nis2"):("cir.1.2 assigns roles and responsibilities; it does not require separating conflicting duties, which NIS2 only touches indirectly through access control (cir.11).",
                "cir.1.2 asigna roles y responsabilidades; no exige separar funciones en conflicto, algo que NIS2 solo toca de forma indirecta por el control de acceso (cir.11)."),
("5.5","nis2"):("Art. 23 sets a mandatory reporting chain — early warning in 24 h, notification in 72 h, final report in a month — to the CSIRT or competent authority; cir.3.3 is the internal channel that feeds it. ISO only asks to keep contacts ready.",
                "El art. 23 fija una cadena de notificacion obligatoria — alerta temprana en 24 h, notificacion en 72 h, informe final en un mes — al CSIRT o a la autoridad competente; cir.3.3 es el canal interno que la alimenta. ISO solo pide tener los contactos preparados."),
("5.7","nis2"):("cir.2.1 wants threats fed into the risk framework and Art. 29 encourages formal information-sharing arrangements; ISO's threat intelligence is an internal analytical process with no sharing expectation.",
                "cir.2.1 quiere que las amenazas alimenten el marco de riesgos y el art. 29 fomenta acuerdos formales de intercambio de informacion; la inteligencia de amenazas de ISO es un proceso analitico interno sin expectativa de compartir."),
("5.8","nis2"):("cir.6.1 and cir.6.2 concern security in acquisition and in the development lifecycle of network and information systems; projects that are not systems fall outside.",
                "cir.6.1 y cir.6.2 se refieren a la seguridad en la adquisicion y en el ciclo de desarrollo de sistemas de redes e informacion; los proyectos que no son sistemas quedan fuera."),
("5.13","nis2"):("cir.12.1 requires a classification scheme; labelling as a distinct practice is not required.",
                 "cir.12.1 exige un esquema de clasificacion; el etiquetado como practica diferenciada no se exige."),
("5.14","nis2"):("Art. 21(2)(j) and cir.9 require secured voice, video and text communications and cryptography where appropriate; a general transfer policy covering paper, verbal and physical media is not what NIS2 has in mind.",
                 "El art. 21.2.j y cir.9 exigen comunicaciones de voz, video y texto protegidas y criptografia cuando proceda; una politica general de transferencia que abarque papel, verbal y soportes fisicos no es lo que NIS2 tiene en mente."),
("5.20","nis2"):("cir.5.1 asks the supply-chain policy to set the security requirements suppliers must meet, considering their practices and vulnerabilities; the content of the individual agreement is not prescribed.",
                 "cir.5.1 pide que la politica de cadena de suministro fije los requisitos que deben cumplir los proveedores, considerando sus practicas y vulnerabilidades; el contenido del acuerdo individual no se prescribe."),
("5.23","nis2"):("cir.5.1 and cir.6.1 treat cloud providers as any other supplier or acquisition; NIS2 adds sector obligations for cloud providers themselves (Annex I) that the customer control does not cover.",
                 "cir.5.1 y cir.6.1 tratan a los proveedores de nube como a cualquier otro proveedor o adquisicion; NIS2 anade obligaciones sectoriales para los propios proveedores de nube (Anexo I) que el control del cliente no cubre."),
("5.28","nis2"):("cir.3.2 requires logs to be retained and protected so that incidents can be investigated; it does not require an evidence-handling procedure that preserves admissibility.",
                 "cir.3.2 exige conservar y proteger los registros para poder investigar incidentes; no exige un procedimiento de manejo de evidencias que preserve su admisibilidad."),
("5.31","nis2"):("cir.1.1 and cir.2.2 want the policy aligned with regulatory obligations and compliance monitored; NIS2 itself brings registration, reporting and supervision duties (Arts. 3, 23, 32) that identifying requirements does not satisfy.",
                 "cir.1.1 y cir.2.2 quieren la politica alineada con las obligaciones regulatorias y el cumplimiento supervisado; NIS2 en si trae deberes de registro, notificacion y supervision (arts. 3, 23, 32) que identificar requisitos no satisface."),
("5.33","nis2"):("cir.3.2 protects and retains logs; NIS2 has no general measure on the protection of records.",
                 "cir.3.2 protege y conserva los registros de actividad; NIS2 no tiene una medida general de proteccion de registros."),
("5.37","nis2"):("cir.1.1 requires a policy and its supporting topic-specific policies; documented operating procedures at the operational level are assumed rather than required.",
                 "cir.1.1 exige una politica y las politicas especificas que la desarrollan; los procedimientos operativos documentados se dan por supuestos mas que exigirse."),
("6.6","nis2"):("cir.10.1 asks for employees and suppliers to understand and commit to their security responsibilities; a confidentiality agreement is one means, not a requirement.",
                "cir.10.1 pide que empleados y proveedores entiendan y asuman sus responsabilidades de seguridad; un acuerdo de confidencialidad es un medio, no un requisito."),
("6.7","nis2"):("cir.11.1 and cir.6.7 govern access control and network security, including remote access; the human and physical side of remote working is not covered.",
                "cir.11.1 y cir.6.7 rigen el control de acceso y la seguridad de red, incluido el acceso remoto; el lado humano y fisico del trabajo a distancia no esta cubierto."),
("7.3","nis2"):("cir.13.3 protects the perimeter and physical access to the areas holding network and information systems; ordinary offices are out of scope.",
                "cir.13.3 protege el perimetro y el acceso fisico a las areas que albergan sistemas de redes e informacion; las oficinas ordinarias quedan fuera."),
("7.4","nis2"):("cir.13.3 requires access control at the perimeter; continuous physical monitoring is not spelled out.",
                "cir.13.3 exige control de acceso en el perimetro; la vigilancia fisica continua no se detalla."),
("7.6","nis2"):("cir.13.3 controls who gets in; it has no rules for working inside secure areas.",
                "cir.13.3 controla quien entra; no tiene reglas para el trabajo dentro de las areas seguras."),
("7.7","nis2"):("cir.12.2 sets rules for handling assets; a clear desk and clear screen rule is an example of such handling, not a requirement.",
                "cir.12.2 fija reglas de manejo de activos; una regla de puesto despejado y pantalla limpia es un ejemplo de ese manejo, no un requisito."),
("7.8","nis2"):("cir.13.2 protects against physical and environmental threats; siting individual equipment to reduce unauthorised access is not addressed.",
                "cir.13.2 protege frente a amenazas fisicas y ambientales; ubicar cada equipo para reducir el acceso no autorizado no se trata."),
("7.9","nis2"):("cir.12.2 covers handling of assets in general; assets used off-site are not addressed separately.",
                "cir.12.2 cubre el manejo de activos en general; los activos usados fuera de las instalaciones no se tratan por separado."),
("7.12","nis2"):("cir.13.1 protects supporting utilities against failures; cabling is treated as a utility, not as an interception risk.",
                 "cir.13.1 protege los suministros frente a fallos; el cableado se trata como un suministro, no como un riesgo de interceptacion."),
("7.14","nis2"):("cir.12.5 requires deleting data from assets returned on termination; secure disposal of equipment in general and its verification are not covered.",
                 "cir.12.5 exige borrar los datos de los activos devueltos al cesar; la eliminacion segura de equipos en general y su verificacion no estan cubiertas."),
("8.1","nis2"):("cir.6.9 and cir.12.2 protect against malware and set handling rules; a policy on endpoint devices as such (configuration, encryption, BYOD, remote wipe) is not required.",
                "cir.6.9 y cir.12.2 protegen frente al malware y fijan reglas de manejo; una politica de dispositivos de usuario como tal (configuracion, cifrado, BYOD, borrado remoto) no se exige."),
("8.4","nis2"):("cir.6.2 requires a secure development lifecycle; protecting source code and repositories is not named among its elements.",
                "cir.6.2 exige un ciclo de vida de desarrollo seguro; proteger el codigo fuente y los repositorios no figura entre sus elementos."),
("8.6","nis2"):("cir.6.3 is configuration management; capacity is only touched through business continuity, not as a control.",
                "cir.6.3 es gestion de la configuracion; la capacidad solo se toca a traves de la continuidad, no como control."),
("8.10","nis2"):("cir.12.5 requires deletion on return of assets at termination; deleting information when no longer needed, in general, is not required.",
                 "cir.12.5 exige el borrado al devolver activos en el cese; borrar la informacion cuando ya no es necesaria, en general, no se exige."),
("8.12","nis2"):("cir.6.7 secures the network; data-leakage prevention is not an explicit requirement.",
                 "cir.6.7 protege la red; la prevencion de fugas de datos no es un requisito explicito."),
("8.17","nis2"):("cir.3.2 asks for logs that support investigation; it does not require synchronised clocks explicitly.",
                 "cir.3.2 pide registros que permitan investigar; no exige de forma explicita relojes sincronizados."),
("8.18","nis2"):("cir.11.3 manages privileged accounts; restricting the utility programs those accounts can run is not covered.",
                 "cir.11.3 gestiona las cuentas privilegiadas; restringir los programas de utilidad que esas cuentas pueden ejecutar no esta cubierto."),
("8.19","nis2"):("cir.6.9 protects against malicious software; controlling software installation on production systems is a means to it, not a requirement.",
                 "cir.6.9 protege frente al software malicioso; controlar la instalacion de software en produccion es un medio para ello, no un requisito."),
("8.23","nis2"):("cir.6.7 covers network security in general; filtering web access is not named.",
                 "cir.6.7 cubre la seguridad de red en general; filtrar el acceso web no se nombra."),
("8.26","nis2"):("cir.6.2 places security requirements inside the development lifecycle for in-house systems; requirements for acquired applications sit in cir.6.1 and are less detailed.",
                 "cir.6.2 situa los requisitos de seguridad dentro del ciclo de desarrollo de sistemas propios; los requisitos de las aplicaciones adquiridas estan en cir.6.1 y son menos detallados."),
("8.27","nis2"):("cir.6.2 mentions secure engineering practices as part of the lifecycle; a documented set of architecture principles is not required.",
                 "cir.6.2 menciona practicas de ingenieria segura como parte del ciclo de vida; un conjunto documentado de principios de arquitectura no se exige."),
("8.28","nis2"):("cir.6.2 asks for secure coding practices within the lifecycle without defining them; ISO expects concrete coding rules.",
                 "cir.6.2 pide practicas de codificacion segura dentro del ciclo de vida sin definirlas; ISO espera reglas de codificacion concretas."),
("8.30","nis2"):("cir.6.2 and cir.5.1 apply the lifecycle and supplier policy to outsourced development; the supervision of an external developer's process is not specific.",
                 "cir.6.2 y cir.5.1 aplican el ciclo de vida y la politica de proveedores al desarrollo externalizado; la supervision del proceso de un desarrollador externo no es especifica."),
("8.31","nis2"):("cir.6.2 requires secure development and testing environments; separating them from production is implied, not stated.",
                 "cir.6.2 exige entornos de desarrollo y prueba seguros; separarlos de produccion se implica, no se enuncia."),
("8.33","nis2"):("cir.6.5 requires security testing; protecting or anonymising the data used in tests is not required.",
                 "cir.6.5 exige pruebas de seguridad; proteger o anonimizar los datos usados en las pruebas no se exige."),
("8.34","nis2"):("cir.2.3 requires an independent review of the risk management; protecting production systems during audit tests is not addressed.",
                 "cir.2.3 exige una revision independiente de la gestion de riesgos; proteger los sistemas en produccion durante las pruebas de auditoria no se trata."),
# ---- DORA -----------------------------------------------------------------
("5.1","dora"):("Art. 5 places the ICT risk framework under the management body, which must approve it and be trained; Art. 6 wants a documented framework reviewed at least yearly and audited. A security policy is one piece of that framework.",
                "El art. 5 pone el marco de riesgo TIC bajo el organo de direccion, que debe aprobarlo y formarse; el art. 6 quiere un marco documentado, revisado al menos anualmente y auditado. Una politica de seguridad es una pieza de ese marco."),
("5.2","dora"):("Art. 5 makes the management body personally responsible and requires an ICT risk control function that is independent and reports to it; assigning roles does not create that function.",
                "El art. 5 hace responsable al organo de direccion y exige una funcion de control del riesgo TIC independiente que le reporte; asignar roles no crea esa funcion."),
("5.3","dora"):("Art. 5 and RTS 2024/1774 require the three lines of defence to be segregated (operations, risk control, internal audit); ISO's segregation of duties is a general principle.",
                "El art. 5 y el RTS 2024/1774 exigen segregar las tres lineas de defensa (operaciones, control de riesgos, auditoria interna); la segregacion de tareas de ISO es un principio general."),
("5.5","dora"):("Art. 19 requires major incidents to be reported to the competent authority with an initial notification, intermediate and final reports on fixed deadlines and templates; keeping contacts is not reporting.",
                "El art. 19 exige notificar los incidentes graves a la autoridad competente con notificacion inicial, informes intermedio y final en plazos y plantillas fijos; tener contactos no es notificar."),
("5.7","dora"):("Art. 13 requires post-incident reviews, lessons learned and monitoring of the effectiveness of the strategy; Art. 45 covers sharing threat intelligence with peers. ISO's threat intelligence is an internal input.",
                "El art. 13 exige revisiones posteriores a los incidentes, lecciones aprendidas y seguimiento de la eficacia de la estrategia; el art. 45 cubre el intercambio de inteligencia con otras entidades. La inteligencia de amenazas de ISO es una entrada interna."),
("5.8","dora"):("Art. 6 and Art. 8 require a framework and an identification of ICT-supported functions and dependencies, with a risk assessment before every major change; project security is only one moment of that.",
                "Los arts. 6 y 8 exigen un marco y una identificacion de las funciones y dependencias soportadas por TIC, con evaluacion de riesgos antes de cada cambio importante; la seguridad en proyectos es solo un momento de eso."),
("5.10","dora"):("Art. 9 asks for policies that protect ICT systems and the information they hold; acceptable-use rules are part of that, not the whole.",
                 "El art. 9 pide politicas que protejan los sistemas TIC y la informacion que contienen; las reglas de uso aceptable son parte de eso, no el todo."),
("5.11","dora"):("Art. 9 protects assets in general; returning assets on departure is not addressed as such.",
                 "El art. 9 protege los activos en general; la devolucion de activos al marcharse no se trata como tal."),
("5.12","dora"):("Art. 8 requires identifying and classifying ICT-supported business functions, assets and dependencies, with criticality; ISO classifies information by its protection needs, not functions by criticality.",
                 "El art. 8 exige identificar y clasificar las funciones de negocio, activos y dependencias soportados por TIC, con su criticidad; ISO clasifica la informacion por sus necesidades de proteccion, no las funciones por criticidad."),
("5.13","dora"):("Art. 8 wants assets identified and classified; labelling is not required.",
                 "El art. 8 quiere activos identificados y clasificados; el etiquetado no se exige."),
("5.14","dora"):("Art. 9 secures the means of transfer and Art. 14 requires communication plans towards clients, counterparts and the public in an incident; the general transfer policy ISO describes is broader in channels and narrower in purpose.",
                 "El art. 9 protege los medios de transferencia y el art. 14 exige planes de comunicacion hacia clientes, contrapartes y el publico ante un incidente; la politica general de transferencia de ISO es mas amplia en canales y mas estrecha en proposito."),
("5.19","dora"):("Art. 28 and RTS 2024/1773 require a strategy on ICT third-party risk, a register of information on all contractual arrangements, pre-contract due diligence and reporting to the authority; a supplier security process is only the starting point.",
                 "El art. 28 y el RTS 2024/1773 exigen una estrategia de riesgo de terceros TIC, un registro de informacion de todos los acuerdos contractuales, diligencia debida precontractual e informacion a la autoridad; un proceso de seguridad de proveedores es solo el punto de partida."),
("5.20","dora"):("Art. 30 lists the mandatory contractual clauses (service descriptions, locations, availability, access and audit rights, exit strategies, incident cooperation); ISO leaves the content of the agreement to the organisation.",
                 "El art. 30 enumera las clausulas contractuales obligatorias (descripcion del servicio, ubicaciones, disponibilidad, derechos de acceso y auditoria, estrategias de salida, cooperacion en incidentes); ISO deja el contenido del acuerdo a la organizacion."),
("5.21","dora"):("Art. 28 and RTS 2025/532 require assessing and conditioning subcontracting chains supporting critical functions, including the right to object; ISO's supply-chain control has no such reach.",
                 "El art. 28 y el RTS 2025/532 exigen evaluar y condicionar las cadenas de subcontratacion que soportan funciones criticas, incluido el derecho de oposicion; el control de cadena de suministro de ISO no tiene ese alcance."),
("5.22","dora"):("Art. 28 and Art. 29 require ongoing monitoring plus an assessment of concentration risk and of the dependency on a single provider; monitoring service delivery does not answer the concentration question.",
                 "Los arts. 28 y 29 exigen seguimiento continuo mas una evaluacion del riesgo de concentracion y de la dependencia de un unico proveedor; supervisar la prestacion del servicio no responde a la pregunta de la concentracion."),
("5.23","dora"):("Art. 28 and Art. 30 apply to cloud as to any ICT third-party service, with the register, the mandatory clauses and, for critical providers, an EU oversight regime; ISO's cloud control is a customer-side policy.",
                 "Los arts. 28 y 30 se aplican a la nube como a cualquier servicio TIC de terceros, con el registro, las clausulas obligatorias y, para proveedores esenciales, un regimen de supervision europeo; el control de nube de ISO es una politica del lado del cliente."),
("5.28","dora"):("Art. 12 and Art. 17 require logs and incident records that allow root-cause analysis; a forensic evidence-handling procedure is not spelled out.",
                 "Los arts. 12 y 17 exigen registros y expedientes de incidentes que permitan el analisis de causa raiz; un procedimiento de manejo de evidencias forenses no se detalla."),
("5.31","dora"):("Art. 5 and Art. 6 make the management body accountable for the framework and its regulatory compliance; DORA is itself directly applicable and brings its own supervisory regime that identifying requirements does not satisfy.",
                 "Los arts. 5 y 6 hacen responsable al organo de direccion del marco y de su cumplimiento regulatorio; DORA es directamente aplicable y trae su propio regimen de supervision que identificar requisitos no satisface."),
("5.33","dora"):("Art. 12 protects backups and recovery; DORA has no general records-protection duty, and the retention of financial records comes from sectoral law.",
                 "El art. 12 protege las copias y la recuperacion; DORA no tiene un deber general de proteccion de registros y la conservacion de registros financieros viene de la normativa sectorial."),
("5.35","dora"):("Art. 6 requires periodic internal audit of the framework by auditors with sufficient ICT knowledge and Art. 24 a testing programme reviewed yearly; ISO's independent review sets neither the auditor's profile nor the frequency.",
                 "El art. 6 exige auditoria interna periodica del marco por auditores con conocimientos TIC suficientes y el art. 24 un programa de pruebas revisado anualmente; la revision independiente de ISO no fija ni el perfil del auditor ni la frecuencia."),
("5.36","dora"):("Art. 6 requires a formal follow-up of audit findings with remediation deadlines; management review of compliance is a weaker mechanism.",
                 "El art. 6 exige un seguimiento formal de los hallazgos de auditoria con plazos de remediacion; la revision de cumplimiento por los responsables es un mecanismo mas debil."),
("5.37","dora"):("Art. 6 requires the whole framework to be documented; operating procedures are part of that documentation, not a separate requirement.",
                 "El art. 6 exige documentar todo el marco; los procedimientos operativos son parte de esa documentacion, no un requisito aparte."),
("6.1","dora"):("Art. 5 requires the management body to keep sufficient ICT knowledge and skills; screening of personnel is not addressed.",
                "El art. 5 exige que el organo de direccion mantenga conocimientos y competencias TIC suficientes; la investigacion de antecedentes del personal no se trata."),
("6.2","dora"):("Art. 5 assigns responsibilities to the management body; the contractual terms of ordinary employees are not addressed.",
                "El art. 5 asigna responsabilidades al organo de direccion; los terminos contractuales de los empleados ordinarios no se tratan."),
("6.6","dora"):("Art. 30 requires confidentiality and data-protection clauses in contracts with ICT providers; agreements with personnel are not covered.",
                "El art. 30 exige clausulas de confidencialidad y proteccion de datos en los contratos con proveedores TIC; los acuerdos con el personal no se cubren."),
("6.7","dora"):("Art. 9 protects remote access technically; the organisational side of remote working is not addressed.",
                "El art. 9 protege el acceso remoto tecnicamente; el lado organizativo del trabajo a distancia no se trata."),
("6.8","dora"):("Art. 17 requires an incident management process with early warning indicators; an internal reporting channel for staff is implied, not required.",
                "El art. 17 exige un proceso de gestion de incidentes con indicadores de alerta temprana; un canal interno de notificacion para el personal se sobreentiende, no se exige."),
("7.1","dora"):("Art. 9 asks for physical protection of ICT assets in general terms; perimeters as a defined control are not required.",
                "El art. 9 pide proteccion fisica de los activos TIC en terminos generales; los perimetros como control definido no se exigen."),
("7.2","dora"):("Art. 9 mentions physical access control among protection measures without detail.",
                "El art. 9 menciona el control de acceso fisico entre las medidas de proteccion sin detallarlo."),
("7.3","dora"):("Art. 9 refers to physical protection generically; securing offices and rooms is not itemised.",
                "El art. 9 se refiere a la proteccion fisica de forma generica; la seguridad de oficinas y salas no se detalla."),
("7.4","dora"):("Art. 10 concerns detecting anomalous activities in ICT systems; physical monitoring of premises is out of its scope.",
                "El art. 10 trata de detectar actividades anomalas en los sistemas TIC; la vigilancia fisica de las instalaciones queda fuera de su alcance."),
("7.5","dora"):("Art. 9 asks for resilience against physical and environmental events at a high level; the design of specific protections is left to the entity.",
                "El art. 9 pide resiliencia frente a eventos fisicos y ambientales a alto nivel; el diseno de protecciones concretas se deja a la entidad."),
("7.8","dora"):("Art. 9 covers physical protection in general; siting of equipment is not addressed.",
                "El art. 9 cubre la proteccion fisica en general; la ubicacion de los equipos no se trata."),
("7.9","dora"):("Art. 9 covers protection generally; assets used off-premises are not addressed separately.",
                "El art. 9 cubre la proteccion en general; los activos usados fuera de las instalaciones no se tratan por separado."),
("7.10","dora"):("Art. 9 protects data at rest and in transit; the lifecycle of storage media is not addressed.",
                 "El art. 9 protege los datos en reposo y en transito; el ciclo de vida de los soportes no se trata."),
("7.11","dora"):("Art. 9 asks for resilience of ICT systems; supporting utilities are not itemised.",
                 "El art. 9 pide resiliencia de los sistemas TIC; los suministros de apoyo no se detallan."),
("7.13","dora"):("Art. 9 requires keeping ICT systems updated and patched; physical maintenance of equipment is not covered.",
                 "El art. 9 exige mantener los sistemas TIC actualizados y parcheados; el mantenimiento fisico de los equipos no se cubre."),
("7.14","dora"):("Art. 9 protects data at rest; the secure disposal of equipment is not addressed.",
                 "El art. 9 protege los datos en reposo; la eliminacion segura de equipos no se trata."),
("8.1","dora"):("Art. 9 protects ICT assets in general; endpoint devices are not addressed as a separate policy.",
                "El art. 9 protege los activos TIC en general; los dispositivos de usuario no se tratan como politica aparte."),
("8.4","dora"):("Art. 9 controls access to ICT systems; access to source code is not itemised.",
                "El art. 9 controla el acceso a los sistemas TIC; el acceso al codigo fuente no se detalla."),
("8.6","dora"):("Art. 7 and Art. 9 require ICT systems to be reliable, with sufficient capacity and resilient to peaks; a capacity management process as such is not required.",
                "Los arts. 7 y 9 exigen sistemas TIC fiables, con capacidad suficiente y resistentes a picos; un proceso de gestion de capacidad como tal no se exige."),
("8.10","dora"):("Art. 9 protects data across its lifecycle; deletion when no longer needed is not required as a control.",
                 "El art. 9 protege los datos a lo largo de su ciclo de vida; el borrado cuando ya no se necesitan no se exige como control."),
("8.12","dora"):("Art. 9 protects the confidentiality of data; data-leakage prevention is not named.",
                 "El art. 9 protege la confidencialidad de los datos; la prevencion de fugas no se nombra."),
("8.17","dora"):("Art. 10 requires detection mechanisms and multi-layer control; clock synchronisation is not itemised.",
                 "El art. 10 exige mecanismos de deteccion y control multicapa; la sincronizacion de relojes no se detalla."),
("8.18","dora"):("Art. 9 requires access control policies; privileged utility programs are not addressed.",
                 "El art. 9 exige politicas de control de acceso; los programas de utilidad privilegiados no se tratan."),
("8.19","dora"):("Art. 9 requires ICT change management; software installation on production systems is one case within it.",
                 "El art. 9 exige gestion de cambios TIC; la instalacion de software en produccion es un caso dentro de ella."),
("8.21","dora"):("Art. 9 requires securing networks and infrastructure; the security of network services bought from third parties falls under Art. 28.",
                 "El art. 9 exige proteger redes e infraestructura; la seguridad de los servicios de red contratados a terceros cae bajo el art. 28."),
("8.23","dora"):("Art. 9 requires protection against unauthorised access and malicious code; web filtering is not named.",
                 "El art. 9 exige proteccion frente al acceso no autorizado y el codigo malicioso; el filtrado web no se nombra."),
("8.25","dora"):("Art. 9 and RTS 2024/1774 (Art. 16) require a secure acquisition, development and maintenance policy with security testing before deployment and specific rules for critical functions; ISO's lifecycle control is less prescriptive.",
                 "El art. 9 y el RTS 2024/1774 (art. 16) exigen una politica de adquisicion, desarrollo y mantenimiento seguros con pruebas antes del despliegue y reglas especificas para funciones criticas; el control de ciclo de vida de ISO es menos prescriptivo."),
("8.26","dora"):("Art. 9 asks for security to be considered in ICT systems generally; application security requirements are not itemised.",
                 "El art. 9 pide considerar la seguridad en los sistemas TIC en general; los requisitos de seguridad de aplicaciones no se detallan."),
("8.27","dora"):("Art. 6 and Art. 7 require a framework and reliable, resilient, up-to-date ICT systems; secure architecture principles are implied rather than required.",
                 "Los arts. 6 y 7 exigen un marco y sistemas TIC fiables, resilientes y actualizados; los principios de arquitectura segura se implican mas que exigirse."),
("8.28","dora"):("Art. 9 requires secure development; coding rules are not defined.",
                 "El art. 9 exige desarrollo seguro; las reglas de codificacion no se definen."),
("8.30","dora"):("Art. 28 and Art. 30 apply the third-party regime, register and contractual clauses to outsourced development; the supervision of the developer's process is not specific.",
                 "Los arts. 28 y 30 aplican el regimen de terceros, el registro y las clausulas contractuales al desarrollo externalizado; la supervision del proceso del desarrollador no es especifica."),
("8.31","dora"):("Art. 9 requires production environments to be separated from development and test environments; the detail of the separation is left to RTS 2024/1774.",
                 "El art. 9 exige separar los entornos de produccion de los de desarrollo y prueba; el detalle de la separacion se deja al RTS 2024/1774."),
("8.34","dora"):("Art. 6 requires internal audits of the framework; protecting production systems during audit tests is not addressed.",
                 "El art. 6 exige auditorias internas del marco; proteger los sistemas en produccion durante las pruebas de auditoria no se trata."),
# ---- PCI DSS --------------------------------------------------------------
("5.2","pci"):("Req. 12.1.3 wants roles and responsibilities for security formally defined, and every requirement (x.1.2) repeats it for its own area, documented and acknowledged; ISO assigns roles once, globally.",
               "El req. 12.1.3 quiere roles y responsabilidades de seguridad definidos formalmente, y cada requisito (x.1.2) lo repite para su area, documentado y reconocido; ISO asigna roles una vez, de forma global."),
("5.3","pci"):("Req. 6.5.3/6.5.4 only separate development from production duties; a general segregation of conflicting duties is not required.",
               "El req. 6.5.3/6.5.4 solo separa las funciones de desarrollo de las de produccion; una segregacion general de funciones en conflicto no se exige."),
("5.4","pci"):("Req. 12.4 requires executive management to formally establish responsibility for cardholder data protection and a PCI DSS compliance programme (service providers, with quarterly reviews); management support of security in general does not do that.",
               "El req. 12.4 exige que la alta direccion establezca formalmente la responsabilidad sobre la proteccion de los datos de tarjeta y un programa de cumplimiento PCI DSS (proveedores de servicios, con revisiones trimestrales); el respaldo general de la direccion a la seguridad no lo hace."),
("5.5","pci"):("Req. 12.10.1 requires the incident plan to include notification of the payment brands and acquirers and the legal reporting obligations; ISO only asks to know whom to contact.",
               "El req. 12.10.1 exige que el plan de incidentes incluya la notificacion a las marcas de tarjetas y a los adquirentes y las obligaciones legales de reporte; ISO solo pide saber a quien contactar."),
("5.6","pci"):("Req. 6.3.1 requires using industry-recognised sources to learn of vulnerabilities; contact with interest groups is a means, not what PCI measures.",
               "El req. 6.3.1 exige usar fuentes reconocidas del sector para conocer vulnerabilidades; el contacto con grupos de interes es un medio, no lo que PCI mide."),
("5.7","pci"):("Req. 6.3.1 wants vulnerability intelligence with a risk ranking; PCI has no broader threat intelligence requirement.",
               "El req. 6.3.1 quiere inteligencia de vulnerabilidades con una clasificacion de riesgo; PCI no tiene un requisito mas amplio de inteligencia de amenazas."),
("5.9","pci"):("Req. 12.5.1 wants an inventory of in-scope system components, and 12.5.2 a documented scope confirmation at least every 12 months and on change; a general asset inventory does not validate PCI scope.",
               "El req. 12.5.1 quiere un inventario de los componentes en alcance, y el 12.5.2 una confirmacion documentada del alcance al menos cada 12 meses y ante cambios; un inventario general de activos no valida el alcance PCI."),
("5.12","pci"):("Req. 9.4.1 requires media with cardholder data to be classified by sensitivity; the classification is limited to that data.",
                "El req. 9.4.1 exige clasificar por sensibilidad los soportes con datos de tarjeta; la clasificacion se limita a esos datos."),
("5.14","pci"):("Req. 4.2 requires strong cryptography whenever PAN crosses open networks and req. 9.4.3/9.4.4 tracked, approved shipment of media; PCI cares about one class of data, ISO about all transfers.",
                "El req. 4.2 exige criptografia robusta siempre que el PAN atraviese redes abiertas y el 9.4.3/9.4.4 envios de soportes aprobados y rastreados; a PCI le importa una clase de datos, a ISO todas las transferencias."),
("5.17","pci"):("Req. 8.3 fixes the parameters — 12-character passwords, four-generation history, lockout after 10 attempts, change every 90 days or dynamic analysis — and 8.6 governs system and application account credentials; ISO leaves the parameters to the organisation.",
                "El req. 8.3 fija los parametros — contrasenas de 12 caracteres, historial de cuatro, bloqueo tras 10 intentos, cambio cada 90 dias o analisis dinamico — y el 8.6 rige las credenciales de cuentas de sistema y aplicacion; ISO deja los parametros a la organizacion."),
("5.18","pci"):("Req. 7.2.4 requires reviewing all user accounts at least every six months and 7.2.5 the same for system accounts; 7.3 wants an access control system that defaults to deny. ISO sets no frequency.",
                "El req. 7.2.4 exige revisar todas las cuentas de usuario al menos cada seis meses y el 7.2.5 lo mismo para las de sistema; el 7.3 quiere un sistema de control de acceso que deniegue por defecto. ISO no fija frecuencia."),
("5.19","pci"):("Req. 12.8 wants a list of TPSPs with a description of the service, the compliance status of each TPSP verified at least every 12 months and a matrix of which requirements each party manages; ISO's supplier process has no such items.",
                "El req. 12.8 quiere una lista de TPSP con la descripcion del servicio, el estado de cumplimiento de cada TPSP verificado al menos cada 12 meses y una matriz de que requisitos gestiona cada parte; el proceso de proveedores de ISO no tiene esos elementos."),
("5.21","pci"):("Req. 12.8 reaches only providers that store, process or transmit account data or can affect its security, and 6.3.2 asks for an inventory of third-party software components; PCI does not look beyond the direct provider.",
                "El req. 12.8 alcanza solo a los proveedores que almacenan, procesan o transmiten datos de cuenta o pueden afectar a su seguridad, y el 6.3.2 pide un inventario de componentes de software de terceros; PCI no mira mas alla del proveedor directo."),
("5.23","pci"):("Req. 12.8 treats the cloud provider as a TPSP, and 12.9 obliges the provider to give its customers a responsibility matrix and compliance evidence; multi-tenant providers also have Appendix A1. ISO's cloud control is customer-side only.",
                "El req. 12.8 trata al proveedor de nube como un TPSP, y el 12.9 obliga al proveedor a dar a sus clientes una matriz de responsabilidades y evidencias de cumplimiento; los proveedores multiinquilino tienen ademas el Apendice A1. El control de nube de ISO es solo del lado del cliente."),
("5.25","pci"):("Req. 12.10.5 requires alerts from IDS/IPS, file integrity monitoring and change-detection systems to feed the incident plan, and 10.7 the prompt handling of failures of critical security controls; ISO's assessment step is generic.",
                "El req. 12.10.5 exige que las alertas de IDS/IPS, monitorizacion de integridad y deteccion de cambios alimenten el plan de incidentes, y el 10.7 el tratamiento rapido de los fallos de los controles criticos; el paso de evaluacion de ISO es generico."),
("5.28","pci"):("Req. 10.5 fixes log retention at 12 months, three immediately available, and 12.10.1 requires the plan to cover the forensic process the payment brands expect; PCI has no evidence-handling procedure as such.",
                "El req. 10.5 fija la conservacion de registros en 12 meses, tres inmediatamente disponibles, y el 12.10.1 exige que el plan cubra el proceso forense que esperan las marcas; PCI no tiene un procedimiento de manejo de evidencias como tal."),
("5.29","pci"):("Req. 12.10.1 asks the incident plan to include business recovery and continuity procedures; PCI has no continuity requirement beyond that.",
                "El req. 12.10.1 pide que el plan de incidentes incluya procedimientos de recuperacion y continuidad del negocio; PCI no tiene mas requisito de continuidad que ese."),
("5.30","pci"):("Req. 12.10.1 mentions recovery and continuity inside the incident plan; ICT readiness for continuity (RTO, alternate sites, tests) is not a PCI requirement.",
                "El req. 12.10.1 menciona la recuperacion y la continuidad dentro del plan de incidentes; la preparacion TIC para la continuidad (RTO, sedes alternativas, pruebas) no es un requisito PCI."),
("5.31","pci"):("Req. 12.4 and 12.5 make PCI DSS compliance a managed programme with a validated scope; identifying PCI as an applicable contractual requirement is the first step, not the programme.",
                "Los reqs. 12.4 y 12.5 hacen del cumplimiento PCI DSS un programa gestionado con un alcance validado; identificar PCI como requisito contractual aplicable es el primer paso, no el programa."),
("5.33","pci"):("Req. 10.5 fixes audit log retention (12 months) and 3.2.1 requires a data retention policy that keeps account data to the minimum and deletes it at least quarterly; ISO protects records without setting periods.",
                "El req. 10.5 fija la conservacion de registros de auditoria (12 meses) y el 3.2.1 exige una politica de retencion que reduzca al minimo los datos de cuenta y los borre al menos trimestralmente; ISO protege los registros sin fijar plazos."),
("5.35","pci"):("Req. 12.4.2 requires service providers to review at least quarterly that personnel follow the policies, and PCI validation itself is an annual assessment (ROC or SAQ) by a QSA or ISA; ISO's independent review has no fixed cycle.",
                "El req. 12.4.2 exige a los proveedores de servicios revisar al menos trimestralmente que el personal sigue las politicas, y la propia validacion PCI es una evaluacion anual (ROC o SAQ) por un QSA o ISA; la revision independiente de ISO no tiene ciclo fijo."),
("5.36","pci"):("Req. 12.4.2 fixes a quarterly review of policy compliance with documented results, for service providers; ISO leaves the frequency open.",
                "El req. 12.4.2 fija una revision trimestral del cumplimiento de las politicas con resultados documentados, para proveedores de servicios; ISO deja la frecuencia abierta."),
("5.37","pci"):("Every requirement opens with an x.1.1 asking for its policies and procedures to be documented, kept up to date, in use and known to all affected parties; one general set of operating procedures meets the spirit but not the per-requirement evidence PCI expects.",
                "Cada requisito abre con un x.1.1 que pide que sus politicas y procedimientos esten documentados, actualizados, en uso y sean conocidos por todas las partes afectadas; un conjunto general de procedimientos cumple el espiritu pero no la evidencia por requisito que PCI espera."),
("6.2","pci"):("Req. 12.6.3 requires personnel to acknowledge, at least annually, that they have read and understood the security policy; the terms of employment themselves are not addressed.",
               "El req. 12.6.3 exige que el personal reconozca, al menos anualmente, que ha leido y entendido la politica de seguridad; los terminos del empleo en si no se tratan."),
("6.5","pci"):("Req. 8.2.5 requires access to be revoked immediately on termination; the other post-employment responsibilities are not addressed.",
               "El req. 8.2.5 exige revocar el acceso de inmediato al cesar; las demas responsabilidades posteriores al empleo no se tratan."),
("6.7","pci"):("Req. 8.4.3 requires MFA for all remote access from outside the network, and 1.5 controls devices that connect to both untrusted networks and the CDE; the organisational side of remote working is not covered.",
               "El req. 8.4.3 exige MFA para todo acceso remoto desde fuera de la red, y el 1.5 controla los dispositivos que se conectan a redes no confiables y al CDE; el lado organizativo del trabajo a distancia no se cubre."),
("6.8","pci"):("Req. 12.10.4 trains the response staff; an event reporting channel for all personnel is not an explicit requirement.",
               "El req. 12.10.4 forma al personal de respuesta; un canal de notificacion de eventos para todo el personal no es un requisito explicito."),
("7.3","pci"):("Req. 9.2.1.1 requires video or electronic monitoring of entry points to sensitive areas, with recordings retained three months; PCI only cares about the areas that hold cardholder data.",
               "El req. 9.2.1.1 exige videovigilancia o control electronico de los puntos de entrada a las areas sensibles, con grabaciones conservadas tres meses; a PCI solo le importan las areas que albergan datos de tarjeta."),
("7.4","pci"):("Req. 9.2.1.1 fixes video or electronic monitoring of sensitive areas, reviewed and retained for three months; ISO's monitoring covers all premises without such specifics.",
               "El req. 9.2.1.1 fija videovigilancia o control electronico de las areas sensibles, revisada y conservada tres meses; la vigilancia de ISO cubre todas las instalaciones sin esas concreciones."),
("7.6","pci"):("Req. 9.3 authorises and escorts visitors with badges and a log kept three months; rules for staff working inside the area are not addressed.",
               "El req. 9.3 autoriza y acompana a los visitantes con identificaciones y un registro conservado tres meses; las reglas del personal que trabaja dentro del area no se tratan."),
("7.8","pci"):("Req. 9.2.2 restricts publicly accessible network jacks and 9.5 the placement and inspection of POI devices; general siting of equipment is not addressed.",
               "El req. 9.2.2 restringe las tomas de red accesibles al publico y el 9.5 la ubicacion e inspeccion de los dispositivos POI; la ubicacion general de los equipos no se trata."),
("7.9","pci"):("Req. 9.4.3/9.4.4 control media sent outside the facility and 9.5 POI devices; other assets used off-site are not addressed.",
               "El req. 9.4.3/9.4.4 controlan los soportes enviados fuera de las instalaciones y el 9.5 los dispositivos POI; los demas activos usados fuera no se tratan."),
("7.12","pci"):("Req. 9.2.2 restricts publicly accessible network jacks; protection of cabling as such is not required.",
                "El req. 9.2.2 restringe las tomas de red accesibles al publico; la proteccion del cableado como tal no se exige."),
("7.13","pci"):("Req. 9.5.1 requires an inventory and periodic inspection of POI devices for tampering; maintenance of other equipment is not addressed.",
                "El req. 9.5.1 exige un inventario y una inspeccion periodica de los dispositivos POI frente a manipulaciones; el mantenimiento de otros equipos no se trata."),
("8.1","pci"):("Req. 12.2 wants an acceptable-use policy with a list of approved products and 1.5 security controls on devices that reach both untrusted networks and the CDE; full endpoint management (encryption, remote wipe, BYOD) is not required.",
               "El req. 12.2 quiere una politica de uso aceptable con lista de productos aprobados y el 1.5 controles en los dispositivos que alcanzan redes no confiables y el CDE; la gestion completa del dispositivo (cifrado, borrado remoto, BYOD) no se exige."),
("8.2","pci"):("Req. 7.2.2/7.2.3 require least privilege with documented approval, 8.6 strict control of system and application accounts, and 10.2.1.2 logging of every administrative action; ISO's privileged-access control has no such specifics.",
               "Los reqs. 7.2.2/7.2.3 exigen minimo privilegio con aprobacion documentada, el 8.6 control estricto de las cuentas de sistema y aplicacion, y el 10.2.1.2 el registro de toda accion administrativa; el control de acceso privilegiado de ISO no tiene esas concreciones."),
("8.3","pci"):("Req. 7.2/7.3 restrict access by need to know with a deny-by-default system, and 3.4 restricts displaying the full PAN and copying it; ISO restricts access without fixing the mechanism.",
               "Los reqs. 7.2/7.3 restringen el acceso por necesidad de conocer con un sistema que deniega por defecto, y el 3.4 restringe mostrar el PAN completo y copiarlo; ISO restringe el acceso sin fijar el mecanismo."),
("8.4","pci"):("Req. 7.2 restricts access to system components in general; source code is not singled out.",
               "El req. 7.2 restringe el acceso a los componentes del sistema en general; el codigo fuente no se singulariza."),
("8.5","pci"):("Req. 8.4 mandates MFA for all access into the CDE and all administrative access, and 8.5 fixes how MFA must be configured (no bypass, independent factors, no success until all factors pass); ISO leaves the authentication strength to a risk decision.",
               "El req. 8.4 impone MFA para todo acceso al CDE y todo acceso administrativo, y el 8.5 fija como debe configurarse (sin elusion, factores independientes, sin exito hasta pasar todos); ISO deja la fortaleza de la autenticacion a una decision de riesgo."),
("8.7","pci"):("Req. 5.3 requires anti-malware to run periodic scans, keep logs, and be impossible for users to disable, and 5.4 an automated anti-phishing mechanism; ISO's control combines technology with awareness without those specifics.",
               "El req. 5.3 exige que el antimalware haga analisis periodicos, guarde registros y no pueda ser desactivado por los usuarios, y el 5.4 un mecanismo antiphishing automatizado; el control de ISO combina tecnologia y concienciacion sin esas concreciones."),
("8.8","pci"):("Req. 6.3.3 patches critical vulnerabilities within a month and 11.3 requires quarterly internal and external scans, the external ones by an ASV, with rescans until clean; ISO's vulnerability management sets no frequency or assessor.",
               "El req. 6.3.3 parchea las vulnerabilidades criticas en un mes y el 11.3 exige analisis trimestrales internos y externos, los externos por un ASV, con reanalisis hasta quedar limpios; la gestion de vulnerabilidades de ISO no fija frecuencia ni evaluador."),
("8.10","pci"):("Req. 3.2.1 requires a quarterly process to delete account data beyond retention and 3.3 forbids storing sensitive authentication data after authorisation; ISO's deletion control has no such data-specific rules.",
                "El req. 3.2.1 exige un proceso trimestral de borrado de datos de cuenta fuera de retencion y el 3.3 prohibe almacenar datos sensibles de autenticacion tras la autorizacion; el control de borrado de ISO no tiene esas reglas por tipo de dato."),
("8.11","pci"):("Req. 3.4.1 fixes the mask (at most the first six and last four digits) and 3.5.1 the methods that make PAN unreadable (truncation, hashing with key, tokenisation, strong encryption); ISO's masking control leaves technique and scope open.",
                "El req. 3.4.1 fija la mascara (como maximo los seis primeros y cuatro ultimos digitos) y el 3.5.1 los metodos que hacen ilegible el PAN (truncado, hash con clave, tokenizacion, cifrado robusto); el control de enmascaramiento de ISO deja tecnica y alcance abiertos."),
("8.12","pci"):("Req. 3.4.2 blocks copying or relocating PAN by remote-access technologies and 4.2.2 secures PAN in end-user messaging; there is no general data-leakage prevention requirement.",
                "El req. 3.4.2 bloquea copiar o mover el PAN mediante tecnologias de acceso remoto y el 4.2.2 protege el PAN en la mensajeria de usuario; no hay un requisito general de prevencion de fugas."),
("8.13","pci"):("Req. 9.4.1.1 only requires offline backup media to be stored in a secure location reviewed at least annually; backup policy, testing and restoration are not PCI requirements.",
                "El req. 9.4.1.1 solo exige que los soportes de copia fuera de linea se guarden en un lugar seguro revisado al menos anualmente; la politica de copias, sus pruebas y la restauracion no son requisitos PCI."),
("8.15","pci"):("Req. 10.2 fixes which events must be logged and which fields each entry needs, 10.3 protects logs with file integrity monitoring, and 10.5 retains them 12 months; ISO's logging control leaves all of that to the organisation.",
                "El req. 10.2 fija que eventos deben registrarse y que campos necesita cada entrada, el 10.3 protege los registros con monitorizacion de integridad, y el 10.5 los conserva 12 meses; el control de registro de ISO deja todo eso a la organizacion."),
("8.16","pci"):("Req. 10.4 requires daily review of security events and critical component logs, with automated tools, 10.7 the detection of failures of critical security controls, and 11.5 intrusion detection plus file integrity monitoring compared weekly; ISO's monitoring control sets none of that.",
                "El req. 10.4 exige revisar a diario los eventos de seguridad y los registros de componentes criticos, con herramientas automatizadas, el 10.7 detectar los fallos de los controles criticos, y el 11.5 deteccion de intrusiones y monitorizacion de integridad comparada semanalmente; el control de seguimiento de ISO no fija nada de eso."),
("8.18","pci"):("Req. 2.2.4 removes unnecessary functionality and 7.2 restricts access; privileged utility programs are not addressed as such.",
                "El req. 2.2.4 elimina la funcionalidad innecesaria y el 7.2 restringe el acceso; los programas de utilidad privilegiados no se tratan como tales."),
("8.19","pci"):("Req. 2.2.4 removes unnecessary software, 6.5 puts installation through change management and 12.2 keeps a list of approved products; the control on installing software in production is spread across them rather than stated.",
                "El req. 2.2.4 elimina el software innecesario, el 6.5 pasa la instalacion por la gestion de cambios y el 12.2 mantiene una lista de productos aprobados; el control sobre instalar software en produccion esta repartido entre ellos, no enunciado."),
("8.20","pci"):("Req. 1.2 requires network diagrams, data-flow diagrams and a review of NSC rulesets at least every six months, and 11.2 quarterly detection of rogue wireless access points; ISO's network security control is not prescriptive.",
                "El req. 1.2 exige diagramas de red, diagramas de flujo de datos y una revision de las reglas de los NSC al menos cada seis meses, y el 11.2 deteccion trimestral de puntos de acceso inalambrico no autorizados; el control de seguridad de redes de ISO no es prescriptivo."),
("8.21","pci"):("Req. 1.2.5/1.2.6 require every allowed service, protocol and port to be identified and justified, with insecure ones mitigated, and 2.2.7 encrypts non-console administrative access; the security of network services bought from third parties is not addressed.",
                "Los reqs. 1.2.5/1.2.6 exigen identificar y justificar cada servicio, protocolo y puerto permitido, mitigando los inseguros, y el 2.2.7 cifra el acceso administrativo no consola; la seguridad de los servicios de red contratados a terceros no se trata."),
("8.22","pci"):("Req. 1.3/1.4 restrict traffic into and out of the CDE and between trusted and untrusted networks, and 11.4.5 requires segmentation to be tested by penetration testing at least annually (six-monthly for service providers); ISO segregates networks without demanding proof.",
                "Los reqs. 1.3/1.4 restringen el trafico hacia y desde el CDE y entre redes de confianza y no confiables, y el 11.4.5 exige probar la segmentacion con pruebas de penetracion al menos anuales (semestrales para proveedores de servicios); ISO segrega redes sin exigir prueba."),
("8.23","pci"):("Req. 1.3.2 restricts outbound traffic from the CDE to what is necessary; filtering web access for users in general is not required.",
                "El req. 1.3.2 restringe el trafico saliente del CDE a lo necesario; filtrar el acceso web de los usuarios en general no se exige."),
("8.24","pci"):("Req. 3.5 fixes how PAN is made unreadable, 3.6/3.7 impose key management with split knowledge, dual control, key custodians and a full key lifecycle, and 4.2 strong cryptography and an inventory of certificates in transit; ISO's cryptography control asks for a policy, not these mechanisms.",
                "El req. 3.5 fija como se hace ilegible el PAN, el 3.6/3.7 imponen una gestion de claves con conocimiento dividido, doble control, custodios y ciclo de vida completo, y el 4.2 criptografia robusta y un inventario de certificados en transito; el control de criptografia de ISO pide una politica, no estos mecanismos."),
("8.26","pci"):("Req. 6.4 requires public-facing web applications to be protected by an automated technical solution (WAF) or reviewed at least annually, and 11.6 a change-and-tamper detection mechanism on payment pages checked weekly; ISO's requirements control is design-time only.",
                "El req. 6.4 exige que las aplicaciones web expuestas esten protegidas por una solucion tecnica automatizada (WAF) o revisadas al menos anualmente, y el 11.6 un mecanismo de deteccion de cambios y manipulacion en las paginas de pago comprobado semanalmente; el control de requisitos de ISO se queda en la fase de diseno."),
("8.27","pci"):("Req. 1.2.3/1.2.4 require current network and account-data-flow diagrams and 6.2.4 engineering techniques against common attacks; a documented set of secure architecture principles is not required.",
                "Los reqs. 1.2.3/1.2.4 exigen diagramas actualizados de red y de flujo de datos de cuenta y el 6.2.4 tecnicas de ingenieria frente a ataques comunes; un conjunto documentado de principios de arquitectura segura no se exige."),
("8.29","pci"):("Req. 6.2.3 reviews bespoke code before release, 6.4 reviews public web applications, 11.3 requires quarterly vulnerability scans and 11.4 penetration testing at least annually and after significant change, following a defined methodology; ISO defines the testing process without frequencies or assessors.",
                "El req. 6.2.3 revisa el codigo a medida antes de la puesta en produccion, el 6.4 revisa las aplicaciones web expuestas, el 11.3 exige analisis de vulnerabilidades trimestrales y el 11.4 pruebas de penetracion al menos anuales y tras cambios significativos, con una metodologia definida; ISO define el proceso de pruebas sin frecuencias ni evaluadores."),
("8.30","pci"):("Req. 6.2 applies to bespoke software whether built in-house or by a third party, and 12.8 governs the provider relationship; the supervision of an external developer's process is not addressed.",
                "El req. 6.2 se aplica al software a medida tanto propio como de terceros, y el 12.8 rige la relacion con el proveedor; la supervision del proceso de un desarrollador externo no se trata."),
("8.32","pci"):("Req. 6.5.1 fixes the content of every change record (reason, approval, impact, testing, back-out) and 6.5.2 requires confirming, after a significant change, that all PCI requirements still hold and updating the scope (12.5.2); ISO's change management does not tie changes to compliance validation.",
                "El req. 6.5.1 fija el contenido de cada registro de cambio (motivo, aprobacion, impacto, pruebas, marcha atras) y el 6.5.2 exige confirmar, tras un cambio significativo, que todos los requisitos PCI siguen cumpliendose y actualizar el alcance (12.5.2); la gestion de cambios de ISO no liga los cambios a la validacion del cumplimiento."),
# ---- SOX / ITGC -----------------------------------------------------------
("5.4","sox"):("elc.1 expects the tone at the top to be about the reliability of financial reporting, with the CEO and CFO certifying under 302/906; management support for information security is a narrower commitment.",
               "elc.1 espera que el tono desde la direccion se refiera a la fiabilidad de la informacion financiera, con el CEO y el CFO certificando bajo 302/906; el respaldo de la direccion a la seguridad es un compromiso mas estrecho."),
("5.8","sox"):("dev.1 wants a development methodology with control points (requirements, testing, approval) for systems that support financial reporting; embedding security in projects is a different objective.",
               "dev.1 quiere una metodologia de desarrollo con puntos de control (requisitos, pruebas, aprobacion) para los sistemas que soportan la informacion financiera; integrar la seguridad en los proyectos es un objetivo distinto."),
("5.9","sox"):("elc.2 needs an inventory of the applications, databases, operating systems and infrastructure that are in SOX scope, linked to the financial processes and key reports; a general asset inventory does not establish that scope.",
               "elc.2 necesita un inventario de las aplicaciones, bases de datos, sistemas operativos e infraestructura en alcance SOX, ligado a los procesos financieros y a los informes clave; un inventario general de activos no establece ese alcance."),
("5.10","sox"):("elc.3 requires IT policies to be documented, approved and communicated; an acceptable-use policy is one of them.",
                "elc.3 exige politicas de TI documentadas, aprobadas y comunicadas; una politica de uso aceptable es una de ellas."),
("5.11","sox"):("acc.2 is about removing access when someone leaves; returning physical assets is not an ITGC.",
                "acc.2 trata de retirar el acceso cuando alguien se va; devolver los activos fisicos no es un ITGC."),
("5.14","sox"):("ops.1 wants interfaces between financial systems monitored and their completeness and accuracy reconciled; the security of information transfer in general is not the concern.",
                "ops.1 quiere que las interfaces entre sistemas financieros se supervisen y se concilie su integridad y exactitud; la seguridad de la transferencia de informacion en general no es la preocupacion."),
("5.19","sox"):("elc.5 requires obtaining and reviewing SOC 1 Type II reports from service organisations that process financial transactions, covering the period, and testing the complementary user entity controls; a supplier security process does not produce that assurance.",
                "elc.5 exige obtener y revisar informes SOC 1 tipo II de las organizaciones de servicios que procesan transacciones financieras, cubriendo el periodo, y probar los controles complementarios de la entidad usuaria; un proceso de seguridad de proveedores no produce ese aseguramiento."),
("5.20","sox"):("elc.5 expects the contract to give the right to a SOC 1 report or to audit; security clauses in general are not what the auditor looks for.",
                "elc.5 espera que el contrato de derecho a un informe SOC 1 o a auditar; las clausulas de seguridad en general no son lo que busca el auditor."),
("5.22","sox"):("elc.5 monitors the provider through the annual SOC 1 report, bridge letters for the gap period and the evaluation of exceptions; monitoring service delivery is broader and less formal.",
                "elc.5 supervisa al proveedor mediante el informe SOC 1 anual, cartas puente para el periodo no cubierto y la evaluacion de las excepciones; supervisar la prestacion del servicio es mas amplio y menos formal."),
("5.23","sox"):("elc.5 treats a cloud provider hosting financial systems as a service organisation needing a SOC 1 report; the customer-side cloud policy ISO describes does not supply that.",
                "elc.5 trata a un proveedor de nube que aloja sistemas financieros como una organizacion de servicios que necesita un informe SOC 1; la politica de nube del lado del cliente que describe ISO no lo aporta."),
("5.24","sox"):("ops.3 wants incidents and problems affecting the financial systems recorded, resolved and escalated with evidence; security incident planning covers a different set of events.",
                "ops.3 quiere que los incidentes y problemas que afectan a los sistemas financieros se registren, resuelvan y escalen con evidencia; la planificacion de incidentes de seguridad cubre otro conjunto de eventos."),
("5.25","sox"):("ops.3 assesses incidents by their effect on the integrity of financial data and processing; the security triage ISO describes uses other criteria.",
                "ops.3 evalua los incidentes por su efecto en la integridad de los datos y el procesamiento financiero; el triaje de seguridad de ISO usa otros criterios."),
("5.26","sox"):("ops.3 requires evidence that incidents affecting financial processing were resolved and that any data impact was corrected; security response procedures do not address data correction.",
                "ops.3 exige evidencia de que los incidentes que afectaron al procesamiento financiero se resolvieron y de que cualquier impacto en los datos se corrigio; los procedimientos de respuesta de seguridad no tratan la correccion de datos."),
("5.27","sox"):("ops.3 expects root-cause and problem management for recurring failures in financial systems; ISO's lessons learned are about security controls.",
                "ops.3 espera analisis de causa raiz y gestion de problemas para los fallos recurrentes en los sistemas financieros; las lecciones aprendidas de ISO se refieren a los controles de seguridad."),
("5.29","sox"):("ops.4 cares about the recoverability of financial systems and data; maintaining security during a disruption is a different objective.",
                "ops.4 se preocupa de la recuperabilidad de los sistemas y datos financieros; mantener la seguridad durante una interrupcion es un objetivo distinto."),
("5.31","sox"):("Sections 302 and 404 are obligations to certify and to assess ICFR, with the external auditor's attestation; identifying SOX as an applicable requirement does not perform the assessment.",
                "Las secciones 302 y 404 son obligaciones de certificar y de evaluar el ICFR, con la atestacion del auditor externo; identificar SOX como requisito aplicable no realiza la evaluacion."),
("5.33","sox"):("Section 802 requires audit and review workpapers to be retained for seven years, with criminal penalties for destruction; ISO protects records without fixing periods or covering the auditor's papers.",
                "La seccion 802 exige conservar los papeles de trabajo de auditoria y revision durante siete anos, con sanciones penales por destruirlos; ISO protege los registros sin fijar plazos ni cubrir los papeles del auditor."),
("5.35","sox"):("Section 404 requires an annual management assessment of ICFR and, for accelerated filers, the external auditor's attestation under AS 2201; elc.4 adds internal audit testing. ISO's independent review of security is neither annual by rule nor about financial reporting.",
                "La seccion 404 exige una evaluacion anual del ICFR por la direccion y, para los emisores acelerados, la atestacion del auditor externo bajo AS 2201; elc.4 anade las pruebas de auditoria interna. La revision independiente de ISO ni es anual por norma ni trata de la informacion financiera."),
("5.36","sox"):("elc.4 expects deficiencies to be evaluated as deficiency, significant deficiency or material weakness and remediated before year end; a management compliance review has no such grading.",
                "elc.4 espera que las deficiencias se evaluen como deficiencia, deficiencia significativa o debilidad material y se remedien antes del cierre; una revision de cumplimiento de la direccion no tiene esa graduacion."),
("5.37","sox"):("elc.3 and ops.1 want documented IT procedures and, specifically, job schedules and interface run-books for financial processing; general operating procedures cover the first, not the second.",
                "elc.3 y ops.1 quieren procedimientos de TI documentados y, en concreto, calendarios de procesos y guias de ejecucion de interfaces para el procesamiento financiero; los procedimientos operativos generales cubren lo primero, no lo segundo."),
("6.3","sox"):("elc.1 expects personnel to understand their role in internal control over financial reporting; security awareness training covers a different subject.",
               "elc.1 espera que el personal entienda su papel en el control interno sobre la informacion financiera; la formacion en concienciacion de seguridad cubre otro tema."),
("6.5","sox"):("acc.2 requires access to be removed within a defined number of days of termination or transfer, with evidence (HR feed reconciled to accounts); ISO's control is about the person's obligations, not the timeliness of revocation.",
               "acc.2 exige retirar el acceso en un numero definido de dias tras el cese o el traslado, con evidencia (listado de RR. HH. conciliado con las cuentas); el control de ISO trata de las obligaciones de la persona, no de la rapidez de la revocacion."),
("6.7","sox"):("acc.5 expects remote access to financial systems to use MFA or an equivalent; the rest of the remote-working arrangement is not an ITGC.",
               "acc.5 espera que el acceso remoto a los sistemas financieros use MFA o un equivalente; el resto del regimen de trabajo a distancia no es un ITGC."),
("6.8","sox"):("ops.3 needs a ticketing channel for incidents in financial systems; a security event reporting channel is a different route.",
               "ops.3 necesita un canal de tickets para los incidentes en los sistemas financieros; un canal de notificacion de eventos de seguridad es una via distinta."),
("7.3","sox"):("acc.7 restricts physical access to data centres and server rooms only; offices are out of scope.",
               "acc.7 restringe el acceso fisico solo a los centros de datos y salas de servidores; las oficinas quedan fuera."),
("7.4","sox"):("acc.7 wants access lists to the data centre reviewed and entries logged; continuous physical surveillance is not required.",
               "acc.7 quiere listas de acceso al centro de datos revisadas y entradas registradas; la vigilancia fisica continua no se exige."),
("7.5","sox"):("ops.4 cares about environmental protection of the data centre only to the extent it supports recovery of financial systems.",
               "ops.4 se ocupa de la proteccion ambiental del centro de datos solo en la medida en que soporta la recuperacion de los sistemas financieros."),
("7.6","sox"):("acc.7 controls who enters the data centre; rules for working inside are not addressed.",
               "acc.7 controla quien entra en el centro de datos; las reglas para trabajar dentro no se tratan."),
("7.8","sox"):("acc.7 concerns the physical protection of the servers that host financial systems; siting of other equipment is out of scope.",
               "acc.7 concierne a la proteccion fisica de los servidores que alojan los sistemas financieros; la ubicacion de otros equipos queda fuera."),
("7.10","sox"):("ops.2 covers backup media handling and off-site storage; storage media in general are not an ITGC.",
                "ops.2 cubre el manejo de los soportes de copia y su custodia externa; los soportes de almacenamiento en general no son un ITGC."),
("7.11","sox"):("ops.4 expects power and environmental resilience only for the systems in scope, as part of recoverability.",
                "ops.4 espera resiliencia electrica y ambiental solo para los sistemas en alcance, como parte de la recuperabilidad."),
("8.4","sox"):("chg.3 expects developers not to have access to production code and objects; access to source code in development is not restricted as such.",
               "chg.3 espera que los desarrolladores no tengan acceso al codigo y los objetos de produccion; el acceso al codigo fuente en desarrollo no se restringe como tal."),
("8.8","sox"):("chg.5 wants patches to financial systems to follow the change process with approval and testing; identifying and assessing vulnerabilities is not what the auditor tests.",
               "chg.5 quiere que los parches de los sistemas financieros sigan el proceso de cambios con aprobacion y pruebas; identificar y evaluar vulnerabilidades no es lo que prueba el auditor."),
("8.14","sox"):("ops.4 expects recovery capability for financial systems, tested periodically; redundancy is one way to get there, not a requirement.",
                "ops.4 espera capacidad de recuperacion de los sistemas financieros, probada periodicamente; la redundancia es una forma de lograrla, no un requisito."),
("8.17","sox"):("acc.8 relies on audit trails whose timestamps are trustworthy; clock synchronisation is assumed rather than tested.",
                "acc.8 se apoya en pistas de auditoria con marcas de tiempo fiables; la sincronizacion de relojes se da por supuesta mas que probarse."),
("8.26","sox"):("dev.1 expects requirements to include the automated application controls and audit trails the financial process needs; security requirements are a subset.",
                "dev.1 espera que los requisitos incluyan los controles automatizados de aplicacion y las pistas de auditoria que necesita el proceso financiero; los requisitos de seguridad son un subconjunto."),
("8.27","sox"):("dev.1 wants a methodology with approvals at each phase; secure architecture principles are not tested.",
                "dev.1 quiere una metodologia con aprobaciones en cada fase; los principios de arquitectura segura no se prueban."),
("8.28","sox"):("dev.1 wants evidence that development followed the methodology; secure coding rules are not an ITGC.",
                "dev.1 quiere evidencia de que el desarrollo siguio la metodologia; las reglas de codificacion segura no son un ITGC."),
("8.30","sox"):("dev.1 and elc.5 expect outsourced development to follow the methodology and, if the provider operates the system, a SOC 1 report; supervising the developer's security process is a different objective.",
                "dev.1 y elc.5 esperan que el desarrollo externalizado siga la metodologia y, si el proveedor opera el sistema, un informe SOC 1; supervisar el proceso de seguridad del desarrollador es un objetivo distinto."),
("8.33","sox"):("chg.2 wants test evidence that is representative of the financial process and retained; protecting or anonymising the test data is not the concern.",
                "chg.2 quiere evidencia de pruebas representativa del proceso financiero y conservada; proteger o anonimizar los datos de prueba no es la preocupacion."),
}

COV = {"F": "full", "P": "partial", "N": "none"}
path = pathlib.Path("crossmap/data/mappings.json")
data = json.loads(path.read_text(encoding="utf-8"))
rows = data["rows"]
for row in rows:
    iso = row["iso"]
    pci_ids, pci_cov = PCI[iso]
    sox_ids, sox_cov = SOX[iso]
    row["pci"] = {"ids": pci_ids, "coverage": COV[pci_cov], "source": "PCI-DSS-4.0.1"}
    row["sox"] = {"ids": sox_ids, "coverage": COV[sox_cov],
                  "source": "ITGC-COSO-AS2201" if all(not i.startswith("sec.") for i in sox_ids)
                  else "SOX-2002"}
    status = row.pop("status", "proposed")
    for key in ("ens", "nis2", "dora", "pci", "sox"):
        block = row[key]
        block.pop("rationale", None)
        block.pop("detail", None)
        if block["coverage"] == "partial":
            en, es = R[(iso, key)]
            block["rationale"] = {"en": en, "es": es}
            d = DETAILS[key][iso]
            block["detail"] = {part: {"en": d[part][0], "es": d[part][1]}
                               for part in ("covers", "adds", "close")}
    row["status"] = status
unused = set(R) - {(r["iso"], k) for r in rows for k in ("ens", "nis2", "dora", "pci", "sox")
                   if r[k]["coverage"] == "partial"}
assert not unused, f"rationales without a partial block: {sorted(unused)}"
unused_detail = {(i, k) for k, d in DETAILS.items() for i in d} - set(R)
assert not unused_detail, f"details without a rationale: {sorted(unused_detail)}"
path.write_text(json.dumps(data, ensure_ascii=False, indent=1))
from collections import Counter
for key in ("ens", "nis2", "dora", "pci", "sox"):
    print(key, dict(Counter(r[key]["coverage"] for r in rows)))
print("rationales:", sum(1 for r in rows for k in ("ens", "nis2", "dora", "pci", "sox") if "rationale" in r[k]))
