import json, pathlib
# PCI DSS v4.0.1 (June 2024), the twelve principal requirements and their
# second-level requirements (x.y). Titles condensed from the standard published
# by the PCI Security Standards Council; the detailed x.y.z requirements, testing
# procedures and guidance are not reproduced.
REQ = {
 "1": ("Install and maintain network security controls",
       "Instalar y mantener controles de seguridad de red"),
 "2": ("Apply secure configurations to all system components",
       "Aplicar configuraciones seguras a todos los componentes del sistema"),
 "3": ("Protect stored account data",
       "Proteger los datos de cuenta almacenados"),
 "4": ("Protect cardholder data with strong cryptography during transmission over open, public networks",
       "Proteger los datos del titular de la tarjeta con criptografia robusta durante su transmision por redes publicas abiertas"),
 "5": ("Protect all systems and networks from malicious software",
       "Proteger todos los sistemas y redes frente al software malicioso"),
 "6": ("Develop and maintain secure systems and software",
       "Desarrollar y mantener sistemas y software seguros"),
 "7": ("Restrict access to system components and cardholder data by business need to know",
       "Restringir el acceso a los componentes del sistema y a los datos del titular segun la necesidad de conocer"),
 "8": ("Identify users and authenticate access to system components",
       "Identificar a los usuarios y autenticar el acceso a los componentes del sistema"),
 "9": ("Restrict physical access to cardholder data",
       "Restringir el acceso fisico a los datos del titular de la tarjeta"),
 "10": ("Log and monitor all access to system components and cardholder data",
        "Registrar y supervisar todo acceso a los componentes del sistema y a los datos del titular"),
 "11": ("Test security of systems and networks regularly",
        "Probar regularmente la seguridad de los sistemas y redes"),
 "12": ("Support information security with organizational policies and programs",
        "Respaldar la seguridad de la informacion con politicas y programas organizativos"),
}
ITEMS = [
("1.1","Processes and mechanisms for installing and maintaining network security controls are defined and understood","Los procesos y mecanismos para instalar y mantener controles de seguridad de red estan definidos y se comprenden"),
("1.2","Network security controls (NSCs) are configured and maintained","Los controles de seguridad de red (NSC) estan configurados y se mantienen"),
("1.3","Network access to and from the cardholder data environment is restricted","El acceso de red hacia y desde el entorno de datos del titular (CDE) esta restringido"),
("1.4","Network connections between trusted and untrusted networks are controlled","Las conexiones de red entre redes de confianza y no confiables estan controladas"),
("1.5","Risks to the CDE from computing devices that connect to both untrusted networks and the CDE are mitigated","Se mitigan los riesgos para el CDE derivados de dispositivos que se conectan tanto a redes no confiables como al CDE"),
("2.1","Processes and mechanisms for applying secure configurations to all system components are defined and understood","Los procesos y mecanismos para aplicar configuraciones seguras a todos los componentes estan definidos y se comprenden"),
("2.2","System components are configured and managed securely","Los componentes del sistema se configuran y gestionan de forma segura"),
("2.3","Wireless environments are configured and managed securely","Los entornos inalambricos se configuran y gestionan de forma segura"),
("3.1","Processes and mechanisms for protecting stored account data are defined and understood","Los procesos y mecanismos para proteger los datos de cuenta almacenados estan definidos y se comprenden"),
("3.2","Storage of account data is kept to a minimum","El almacenamiento de datos de cuenta se reduce al minimo"),
("3.3","Sensitive authentication data (SAD) is not stored after authorization","Los datos sensibles de autenticacion (SAD) no se almacenan tras la autorizacion"),
("3.4","Access to displays of full PAN and ability to copy PAN are restricted","El acceso a la visualizacion del PAN completo y la capacidad de copiarlo estan restringidos"),
("3.5","Primary account number (PAN) is secured wherever it is stored","El numero de cuenta principal (PAN) esta protegido alli donde se almacena"),
("3.6","Cryptographic keys used to protect stored account data are secured","Las claves criptograficas usadas para proteger los datos de cuenta almacenados estan protegidas"),
("3.7","Key management processes and procedures covering the full key lifecycle are defined and implemented","Los procesos y procedimientos de gestion de claves que cubren todo su ciclo de vida estan definidos e implantados"),
("4.1","Processes and mechanisms for protecting cardholder data in transit are defined and understood","Los procesos y mecanismos para proteger los datos del titular en transito estan definidos y se comprenden"),
("4.2","PAN is protected with strong cryptography during transmission","El PAN se protege con criptografia robusta durante su transmision"),
("5.1","Processes and mechanisms for protecting systems and networks from malware are defined and understood","Los procesos y mecanismos para proteger sistemas y redes frente al malware estan definidos y se comprenden"),
("5.2","Malicious software (malware) is prevented, or detected and addressed","El software malicioso se previene, o se detecta y se trata"),
("5.3","Anti-malware mechanisms and processes are active, maintained, and monitored","Los mecanismos y procesos antimalware estan activos, se mantienen y se supervisan"),
("5.4","Anti-phishing mechanisms protect users against phishing attacks","Mecanismos antiphishing protegen a los usuarios frente a ataques de phishing"),
("6.1","Processes and mechanisms for developing and maintaining secure systems and software are defined and understood","Los procesos y mecanismos para desarrollar y mantener sistemas y software seguros estan definidos y se comprenden"),
("6.2","Bespoke and custom software are developed securely","El software a medida y personalizado se desarrolla de forma segura"),
("6.3","Security vulnerabilities are identified and addressed","Las vulnerabilidades de seguridad se identifican y se tratan"),
("6.4","Public-facing web applications are protected against attacks","Las aplicaciones web expuestas al publico estan protegidas frente a ataques"),
("6.5","Changes to all system components are managed securely","Los cambios en todos los componentes del sistema se gestionan de forma segura"),
("7.1","Processes and mechanisms for restricting access by business need to know are defined and understood","Los procesos y mecanismos para restringir el acceso segun la necesidad de conocer estan definidos y se comprenden"),
("7.2","Access to system components and data is appropriately defined and assigned","El acceso a los componentes del sistema y a los datos esta definido y asignado adecuadamente"),
("7.3","Access to system components and data is managed via an access control system(s)","El acceso a los componentes del sistema y a los datos se gestiona mediante sistemas de control de acceso"),
("8.1","Processes and mechanisms for identifying users and authenticating access are defined and understood","Los procesos y mecanismos para identificar usuarios y autenticar el acceso estan definidos y se comprenden"),
("8.2","User identification and related accounts are strictly managed throughout the account lifecycle","La identificacion de usuarios y sus cuentas se gestionan estrictamente durante todo el ciclo de vida de la cuenta"),
("8.3","Strong authentication for users and administrators is established and managed","Se establece y gestiona una autenticacion robusta para usuarios y administradores"),
("8.4","Multi-factor authentication (MFA) is implemented to secure access into the CDE","Se implanta autenticacion multifactor (MFA) para proteger el acceso al CDE"),
("8.5","Multi-factor authentication (MFA) systems are configured to prevent misuse","Los sistemas de autenticacion multifactor estan configurados para impedir su uso indebido"),
("8.6","Use of application and system accounts and associated authentication factors is strictly managed","El uso de cuentas de aplicacion y de sistema y de sus factores de autenticacion se gestiona estrictamente"),
("9.1","Processes and mechanisms for restricting physical access to cardholder data are defined and understood","Los procesos y mecanismos para restringir el acceso fisico a los datos del titular estan definidos y se comprenden"),
("9.2","Physical access controls manage entry into facilities and systems containing cardholder data","Controles de acceso fisico gestionan la entrada a instalaciones y sistemas que contienen datos del titular"),
("9.3","Physical access for personnel and visitors is authorized and managed","El acceso fisico del personal y de los visitantes esta autorizado y gestionado"),
("9.4","Media with cardholder data is securely stored, accessed, distributed, and destroyed","Los soportes con datos del titular se almacenan, consultan, distribuyen y destruyen de forma segura"),
("9.5","Point-of-interaction (POI) devices are protected from tampering and unauthorized substitution","Los dispositivos de punto de interaccion (POI) estan protegidos frente a manipulacion y sustitucion no autorizada"),
("10.1","Processes and mechanisms for logging and monitoring all access are defined and understood","Los procesos y mecanismos para registrar y supervisar todo acceso estan definidos y se comprenden"),
("10.2","Audit logs are implemented to support the detection of anomalies and suspicious activity, and forensic analysis","Se implantan registros de auditoria que permiten detectar anomalias y actividad sospechosa y realizar analisis forense"),
("10.3","Audit logs are protected from destruction and unauthorized modifications","Los registros de auditoria estan protegidos frente a destruccion y modificaciones no autorizadas"),
("10.4","Audit logs are reviewed to identify anomalies or suspicious activity","Los registros de auditoria se revisan para identificar anomalias o actividad sospechosa"),
("10.5","Audit log history is retained and available for analysis","El historico de registros de auditoria se conserva y esta disponible para su analisis"),
("10.6","Time-synchronization mechanisms support consistent time settings across all systems","Mecanismos de sincronizacion horaria garantizan una hora coherente en todos los sistemas"),
("10.7","Failures of critical security control systems are detected, reported, and responded to promptly","Los fallos de los sistemas de control de seguridad criticos se detectan, notifican y atienden con prontitud"),
("11.1","Processes and mechanisms for regularly testing security of systems and networks are defined and understood","Los procesos y mecanismos para probar regularmente la seguridad de sistemas y redes estan definidos y se comprenden"),
("11.2","Wireless access points are identified and monitored, and unauthorized wireless access points are addressed","Los puntos de acceso inalambrico se identifican y supervisan, y los no autorizados se tratan"),
("11.3","External and internal vulnerabilities are regularly identified, prioritized, and addressed","Las vulnerabilidades externas e internas se identifican, priorizan y tratan regularmente"),
("11.4","External and internal penetration testing is regularly performed, and exploitable weaknesses are corrected","Se realizan regularmente pruebas de penetracion externas e internas y se corrigen las debilidades explotables"),
("11.5","Network intrusions and unexpected file changes are detected and responded to","Las intrusiones de red y los cambios inesperados en ficheros se detectan y se atienden"),
("11.6","Unauthorized changes on payment pages are detected and responded to","Los cambios no autorizados en las paginas de pago se detectan y se atienden"),
("12.1","A comprehensive information security policy that governs and provides direction for protection of information assets is known and current","Una politica integral de seguridad de la informacion que gobierna y orienta la proteccion de los activos es conocida y esta actualizada"),
("12.2","Acceptable use policies for end-user technologies are defined and implemented","Las politicas de uso aceptable de las tecnologias de usuario final estan definidas e implantadas"),
("12.3","Risks to the cardholder data environment are formally identified, evaluated, and managed","Los riesgos para el entorno de datos del titular se identifican, evaluan y gestionan formalmente"),
("12.4","PCI DSS compliance is managed","El cumplimiento de PCI DSS se gestiona"),
("12.5","PCI DSS scope is documented and validated","El alcance de PCI DSS esta documentado y validado"),
("12.6","Security awareness education is an ongoing activity","La formacion en concienciacion de seguridad es una actividad continua"),
("12.7","Personnel are screened to reduce risks from insider threats","Se investiga al personal para reducir los riesgos de amenazas internas"),
("12.8","Risk to information assets associated with third-party service provider (TPSP) relationships is managed","Se gestiona el riesgo para los activos de informacion asociado a las relaciones con proveedores de servicios (TPSP)"),
("12.9","Third-party service providers (TPSPs) support their customers' PCI DSS compliance","Los proveedores de servicios (TPSP) respaldan el cumplimiento de PCI DSS de sus clientes"),
("12.10","Suspected and confirmed security incidents that could impact the CDE are responded to immediately","Los incidentes de seguridad sospechados y confirmados que puedan afectar al CDE se atienden de inmediato"),
]
items = []
for rid, en, es in ITEMS:
    req = rid.split(".")[0]
    items.append({
        "id": f"req.{rid}", "family": req,
        "family_title": {"en": f"Requirement {req} - {REQ[req][0]}",
                         "es": f"Requisito {req} - {REQ[req][1]}"},
        "title": {"en": en, "es": es},
    })
pathlib.Path("crossmap/data/controls_pci.json").write_text(
    json.dumps({"framework": "PCI", "items": items}, ensure_ascii=False, indent=1))
print("PCI DSS:", len(items), "requisitos")
