import json, pathlib
M = [
 ("org.1","org","Security policy","Politica de seguridad"),
 ("org.2","org","Security regulations","Normativa de seguridad"),
 ("org.3","org","Security procedures","Procedimientos de seguridad"),
 ("org.4","org","Authorisation process","Proceso de autorizacion"),
 ("op.pl.1","op.pl","Risk analysis","Analisis de riesgos"),
 ("op.pl.2","op.pl","Security architecture","Arquitectura de seguridad"),
 ("op.pl.3","op.pl","Acquisition of new components","Adquisicion de nuevos componentes"),
 ("op.pl.4","op.pl","Capacity sizing and management","Dimensionamiento/gestion de la capacidad"),
 ("op.pl.5","op.pl","Certified components","Componentes certificados"),
 ("op.acc.1","op.acc","Identification","Identificacion"),
 ("op.acc.2","op.acc","Access requirements","Requisitos de acceso"),
 ("op.acc.3","op.acc","Segregation of duties and tasks","Segregacion de funciones y tareas"),
 ("op.acc.4","op.acc","Access rights management process","Proceso de gestion de derechos de acceso"),
 ("op.acc.5","op.acc","Authentication mechanism (external users)","Mecanismo de autenticacion (usuarios externos)"),
 ("op.acc.6","op.acc","Authentication mechanism (organisation users)","Mecanismo de autenticacion (usuarios de la organizacion)"),
 ("op.exp.1","op.exp","Asset inventory","Inventario de activos"),
 ("op.exp.2","op.exp","Security configuration","Configuracion de seguridad"),
 ("op.exp.3","op.exp","Security configuration management","Gestion de la configuracion de seguridad"),
 ("op.exp.4","op.exp","Maintenance and security updates","Mantenimiento y actualizaciones de seguridad"),
 ("op.exp.5","op.exp","Change management","Gestion de cambios"),
 ("op.exp.6","op.exp","Protection against malicious code","Proteccion frente a codigo danino"),
 ("op.exp.7","op.exp","Incident management","Gestion de incidentes"),
 ("op.exp.8","op.exp","Activity logging","Registro de la actividad"),
 ("op.exp.9","op.exp","Incident management logging","Registro de la gestion de incidentes"),
 ("op.exp.10","op.exp","Protection of cryptographic keys","Proteccion de claves criptograficas"),
 ("op.ext.1","op.ext","Contracting and service level agreements","Contratacion y acuerdos de nivel de servicio"),
 ("op.ext.2","op.ext","Day-to-day management","Gestion diaria"),
 ("op.ext.3","op.ext","Supply chain protection","Proteccion de la cadena de suministro"),
 ("op.ext.4","op.ext","System interconnection","Interconexion de sistemas"),
 ("op.nub.1","op.nub","Protection of cloud services","Proteccion de servicios en la nube"),
 ("op.cont.1","op.cont","Impact analysis","Analisis de impacto"),
 ("op.cont.2","op.cont","Continuity plan","Plan de continuidad"),
 ("op.cont.3","op.cont","Periodic testing","Pruebas periodicas"),
 ("op.cont.4","op.cont","Alternative means","Medios alternativos"),
 ("op.mon.1","op.mon","Intrusion detection","Deteccion de intrusion"),
 ("op.mon.2","op.mon","Metrics system","Sistema de metricas"),
 ("op.mon.3","op.mon","Surveillance","Vigilancia"),
 ("mp.if.1","mp.if","Separate areas with access control","Areas separadas y con control de acceso"),
 ("mp.if.2","mp.if","Identification of persons","Identificacion de las personas"),
 ("mp.if.3","mp.if","Fitting out of premises","Acondicionamiento de los locales"),
 ("mp.if.4","mp.if","Electrical power","Energia electrica"),
 ("mp.if.5","mp.if","Fire protection","Proteccion frente a incendios"),
 ("mp.if.6","mp.if","Flood protection","Proteccion frente a inundaciones"),
 ("mp.if.7","mp.if","Equipment entry and exit register","Registro de entrada y salida de equipamiento"),
 ("mp.per.1","mp.per","Job characterisation","Caracterizacion del puesto de trabajo"),
 ("mp.per.2","mp.per","Duties and obligations","Deberes y obligaciones"),
 ("mp.per.3","mp.per","Awareness","Concienciacion"),
 ("mp.per.4","mp.per","Training","Formacion"),
 ("mp.eq.1","mp.eq","Clear desk","Puesto de trabajo despejado"),
 ("mp.eq.2","mp.eq","Workstation lock","Bloqueo de puesto de trabajo"),
 ("mp.eq.3","mp.eq","Protection of portable devices","Proteccion de dispositivos portatiles"),
 ("mp.eq.4","mp.eq","Other devices connected to the network","Otros dispositivos conectados a la red"),
 ("mp.com.1","mp.com","Secure perimeter","Perimetro seguro"),
 ("mp.com.2","mp.com","Protection of confidentiality","Proteccion de la confidencialidad"),
 ("mp.com.3","mp.com","Protection of integrity and authenticity","Proteccion de la integridad y de la autenticidad"),
 ("mp.com.4","mp.com","Separation of information flows in the network","Separacion de flujos de informacion en la red"),
 ("mp.si.1","mp.si","Media marking","Marcado de soportes"),
 ("mp.si.2","mp.si","Cryptography","Criptografia"),
 ("mp.si.3","mp.si","Custody","Custodia"),
 ("mp.si.4","mp.si","Transport","Transporte"),
 ("mp.si.5","mp.si","Erasure and destruction","Borrado y destruccion"),
 ("mp.sw.1","mp.sw","Application development","Desarrollo de aplicaciones"),
 ("mp.sw.2","mp.sw","Acceptance and commissioning","Aceptacion y puesta en servicio"),
 ("mp.info.1","mp.info","Personal data","Datos personales"),
 ("mp.info.2","mp.info","Information classification","Calificacion de la informacion"),
 ("mp.info.3","mp.info","Electronic signature","Firma electronica"),
 ("mp.info.4","mp.info","Time stamps","Sellos de tiempo"),
 ("mp.info.5","mp.info","Cleaning of published documents","Limpieza de documentos"),
 ("mp.info.6","mp.info","Backups","Copias de seguridad"),
 ("mp.s.1","mp.s","Email protection","Proteccion del correo electronico"),
 ("mp.s.2","mp.s","Protection of web services and applications","Proteccion de servicios y aplicaciones web"),
 ("mp.s.3","mp.s","Web browsing protection","Proteccion de la navegacion web"),
 ("mp.s.4","mp.s","Denial of service protection","Proteccion frente a denegacion de servicio"),
]
FAM = {
 "org": ("Organisational framework","Marco organizativo"),
 "op.pl": ("Operational / Planning","Operacional / Planificacion"),
 "op.acc": ("Operational / Access control","Operacional / Control de acceso"),
 "op.exp": ("Operational / Exploitation","Operacional / Explotacion"),
 "op.ext": ("Operational / External services","Operacional / Servicios externos"),
 "op.nub": ("Operational / Cloud services","Operacional / Servicios en la nube"),
 "op.cont": ("Operational / Continuity","Operacional / Continuidad del servicio"),
 "op.mon": ("Operational / Monitoring","Operacional / Monitorizacion del sistema"),
 "mp.if": ("Protection / Facilities","Proteccion / Instalaciones e infraestructuras"),
 "mp.per": ("Protection / Personnel","Proteccion / Gestion del personal"),
 "mp.eq": ("Protection / Equipment","Proteccion / Equipos"),
 "mp.com": ("Protection / Communications","Proteccion / Comunicaciones"),
 "mp.si": ("Protection / Information media","Proteccion / Soportes de informacion"),
 "mp.sw": ("Protection / Applications","Proteccion / Aplicaciones informaticas"),
 "mp.info": ("Protection / Information","Proteccion / Informacion"),
 "mp.s": ("Protection / Services","Proteccion / Servicios"),
}
out = {"framework":"ENS","items":[
 {"id":i,"family":f,"family_title":{"en":FAM[f][0],"es":FAM[f][1]},"title":{"en":en,"es":es}}
 for i,f,en,es in M]}
pathlib.Path("crossmap/data/controls_ens.json").write_text(json.dumps(out, ensure_ascii=False, indent=1))
print("ENS:", len(M), "medidas |", len({f for _,f,_,_ in M}), "familias")
