import json, pathlib
S = [
 {"id":"ISO-27002-2022","kind":"standard",
  "title":{"en":"ISO/IEC 27002:2022 - Information security controls","es":"ISO/IEC 27002:2022 - Controles de seguridad de la informacion"},
  "url":"https://www.iso.org/standard/75652.html",
  "note":{"en":"Control titles only. The standard itself is copyrighted and is not reproduced here.",
          "es":"Solo los titulos de los controles. La norma es de pago y no se reproduce aqui."},
  "watch":True},
 {"id":"RD-311-2022","kind":"legislation",
  "title":{"en":"Royal Decree 311/2022 regulating the National Security Framework (ENS), Annex II",
           "es":"Real Decreto 311/2022 por el que se regula el Esquema Nacional de Seguridad (ENS), Anexo II"},
  "url":"https://www.boe.es/buscar/act.php?id=BOE-A-2022-7191","watch":True},
 {"id":"CCN-STIC-825","kind":"guidance",
  "title":{"en":"CCN-STIC 825 Independent Annex - Mapping between ISO 27001:2022 and RD 311/2022 (ENS)",
           "es":"CCN-STIC 825 Anexo Independiente - Mapeo entre la norma ISO 27001:2022 y el RD 311/2022 (ENS)"},
  "url":"https://www.ccn-cert.cni.es/es/series-ccn-stic/800-guia-esquema-nacional-de-seguridad/7101-ccn-stic-825-anexo-independiente-mapeo-entre-la-norma-iso-27001-2022-y-el-rd-311-2022-ens",
  "note":{"en":"The reference correspondence between ISO and the ENS. Rows citing it must be confirmed against the published annex.",
          "es":"La correspondencia de referencia entre ISO y el ENS. Las filas que lo citan deben confirmarse contra el anexo publicado."},
  "watch":True},
 {"id":"DIR-2022-2555","kind":"legislation",
  "title":{"en":"Directive (EU) 2022/2555 (NIS2)","es":"Directiva (UE) 2022/2555 (NIS2)"},
  "url":"https://eur-lex.europa.eu/eli/dir/2022/2555/oj","watch":True},
 {"id":"CIR-2024-2690","kind":"legislation",
  "title":{"en":"Commission Implementing Regulation (EU) 2024/2690 - technical and methodological requirements",
           "es":"Reglamento de Ejecucion (UE) 2024/2690 - requisitos tecnicos y metodologicos"},
  "url":"https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj",
  "note":{"en":"Legally binding for digital infrastructure, ICT service management and digital provider entities. For other sectors it is the reference of choice until national law says otherwise.",
          "es":"Vinculante para infraestructura digital, gestion de servicios TIC y proveedores digitales. Para otros sectores es la referencia de eleccion mientras la ley nacional no diga otra cosa."},
  "watch":True},
 {"id":"ENISA-TIG-1.0","kind":"guidance",
  "title":{"en":"ENISA Technical Implementation Guidance on cybersecurity risk-management measures, v1.0 (June 2025)",
           "es":"Guia tecnica de implantacion de ENISA sobre medidas de gestion de riesgos de ciberseguridad, v1.0 (junio 2025)"},
  "url":"https://www.enisa.europa.eu/publications/nis2-technical-implementation-guidance",
  "note":{"en":"Non-binding. Its separate mapping table (v1.2, xlsx) is the authority for the NIS2 side of this dataset.",
          "es":"No vinculante. Su tabla de mapeo aparte (v1.2, xlsx) es la referencia para el lado NIS2 de este conjunto de datos."},
  "watch":True},
 {"id":"ENISA-TIG-MAP","kind":"guidance",
  "title":{"en":"ENISA Technical Implementation Guidance mapping table v1.2","es":"Tabla de mapeo de la guia tecnica de ENISA v1.2"},
  "url":"https://www.enisa.europa.eu/sites/default/files/2025-09/ENISA_Technical_Implementation_Guidance_Mapping_table_version_1.2.xlsx","watch":True},
 {"id":"DORA-2022-2554","kind":"legislation",
  "title":{"en":"Regulation (EU) 2022/2554 (DORA)","es":"Reglamento (UE) 2022/2554 (DORA)"},
  "url":"https://eur-lex.europa.eu/eli/reg/2022/2554/oj",
  "note":{"en":"Applies from 17 January 2025 to financial entities.","es":"Aplicable desde el 17 de enero de 2025 a las entidades financieras."},
  "watch":True},
 {"id":"DORA-RTS-2024-1774","kind":"legislation",
  "title":{"en":"Delegated Regulation (EU) 2024/1774 - RTS on ICT risk management framework",
           "es":"Reglamento Delegado (UE) 2024/1774 - NTR sobre el marco de gestion del riesgo TIC"},
  "url":"https://eur-lex.europa.eu/eli/reg_del/2024/1774/oj","watch":True},
 {"id":"ES-NIS2-BILL","kind":"legislation",
  "title":{"en":"Spain: draft Law on Coordination and Governance of Cybersecurity, transposing NIS2",
           "es":"Espana: Anteproyecto de Ley de Coordinacion y Gobernanza de la Ciberseguridad, que transpone NIS2"},
  "url":"https://www.boe.es/buscar/doc.php?id=BOE-A-2022-7191",
  "note":{"en":"Not in force at the time of writing. Watch this one: when it is published, the NIS2 side of the dataset needs revisiting.",
          "es":"No vigente al escribir esto. Vigilar: cuando se publique, habra que revisar el lado NIS2 del conjunto de datos."},
  "watch":False},
 {"id":"PCI-DSS-4.0.1","kind":"standard",
  "title":{"en":"PCI DSS v4.0.1 - Payment Card Industry Data Security Standard (PCI SSC, June 2024)",
           "es":"PCI DSS v4.0.1 - Norma de seguridad de datos del sector de tarjetas de pago (PCI SSC, junio 2024)"},
  "url":"https://www.pcisecuritystandards.org/document_library/",
  "note":{"en":"Requirement titles at the x.y level only. The detailed requirements, testing procedures and guidance are in the standard, which is free to download from the PCI SSC document library.",
          "es":"Solo los titulos de los requisitos de nivel x.y. Los requisitos detallados, procedimientos de prueba y guia estan en la norma, descargable gratuitamente de la biblioteca del PCI SSC."},
  "watch":True},
 {"id":"SOX-2002","kind":"legislation",
  "title":{"en":"Sarbanes-Oxley Act of 2002 (Pub. L. 107-204), Sections 302, 404, 409, 802 and 906",
           "es":"Ley Sarbanes-Oxley de 2002 (Pub. L. 107-204), secciones 302, 404, 409, 802 y 906"},
  "url":"https://www.govinfo.gov/content/pkg/PLAW-107publ204/pdf/PLAW-107publ204.pdf","watch":True},
 {"id":"ITGC-COSO-AS2201","kind":"guidance",
  "title":{"en":"IT General Controls under SOX 404 - COSO Internal Control Integrated Framework (2013) and PCAOB AS 2201",
           "es":"Controles generales de TI bajo SOX 404 - Marco integrado de control interno COSO (2013) y PCAOB AS 2201"},
  "url":"https://pcaobus.org/oversight/standards/auditing-standards/details/AS2201",
  "note":{"en":"SOX has no catalogue of IT controls. The SOX side of this dataset is the classic four-domain ITGC catalogue (access, changes, development, operations) as it is tested in practice under AS 2201 - a synthesis of common audit practice, not an official taxonomy.",
          "es":"SOX no tiene un catalogo de controles de TI. El lado SOX de este conjunto de datos es el catalogo ITGC clasico de cuatro dominios (acceso, cambios, desarrollo, operaciones) tal como se prueba en la practica bajo AS 2201: una sintesis de la practica de auditoria, no una taxonomia oficial."},
  "watch":True},
]
pathlib.Path("crossmap/data/sources.json").write_text(json.dumps({"sources":S}, ensure_ascii=False, indent=1))
F = [
 {"id":"ISO","name":{"en":"ISO/IEC 27001:2022 / 27002:2022","es":"ISO/IEC 27001:2022 / 27002:2022"},
  "kind":{"en":"Voluntary standard, certifiable","es":"Norma voluntaria, certificable"},
  "scope":{"en":"Any organisation","es":"Cualquier organizacion"},"source":"ISO-27002-2022"},
 {"id":"ENS","name":{"en":"National Security Framework (RD 311/2022)","es":"Esquema Nacional de Seguridad (RD 311/2022)"},
  "kind":{"en":"Spanish law, certifiable","es":"Norma espanola, certificable"},
  "scope":{"en":"Spanish public sector and its suppliers","es":"Sector publico espanol y sus proveedores"},"source":"RD-311-2022"},
 {"id":"NIS2","name":{"en":"Directive (EU) 2022/2555 (NIS2)","es":"Directiva (UE) 2022/2555 (NIS2)"},
  "kind":{"en":"EU directive, transposed nationally","es":"Directiva europea, de transposicion nacional"},
  "scope":{"en":"Essential and important entities in the listed sectors","es":"Entidades esenciales e importantes de los sectores listados"},"source":"DIR-2022-2555"},
 {"id":"DORA","name":{"en":"Regulation (EU) 2022/2554 (DORA)","es":"Reglamento (UE) 2022/2554 (DORA)"},
  "kind":{"en":"EU regulation, directly applicable","es":"Reglamento europeo, de aplicacion directa"},
  "scope":{"en":"Financial entities and their critical ICT providers","es":"Entidades financieras y sus proveedores TIC esenciales"},"source":"DORA-2022-2554"},
 {"id":"PCI","name":{"en":"PCI DSS v4.0.1","es":"PCI DSS v4.0.1"},
  "kind":{"en":"Industry standard, contractually mandated by the card brands","es":"Norma sectorial, exigida contractualmente por las marcas de tarjetas"},
  "scope":{"en":"Any entity that stores, processes or transmits cardholder data","es":"Cualquier entidad que almacene, procese o transmita datos de tarjetas"},"source":"PCI-DSS-4.0.1"},
 {"id":"SOX","name":{"en":"Sarbanes-Oxley Act (SOX) - IT General Controls","es":"Ley Sarbanes-Oxley (SOX) - Controles generales de TI"},
  "kind":{"en":"US federal law; IT controls tested via ITGC under Section 404","es":"Ley federal de EE. UU.; controles de TI evaluados como ITGC bajo la seccion 404"},
  "scope":{"en":"SEC-registered companies and their subsidiaries, including those outside the US","es":"Empresas registradas en la SEC y sus filiales, incluidas las de fuera de EE. UU."},"source":"SOX-2002"},
]
pathlib.Path("crossmap/data/frameworks.json").write_text(json.dumps({"frameworks":F}, ensure_ascii=False, indent=1))
print("fuentes:", len(S), "| marcos:", len(F))
