import json, pathlib
# One-sentence description of what each ISO/IEC 27002:2022 control is about.
# These are the author's own paraphrases of the purpose of each control, written
# for orientation; the text of the standard is copyrighted and is not reproduced.
S = {
"5.1":("Management defines, approves, publishes and periodically reviews an information security policy and the topic-specific policies that hang from it.",
       "La direccion define, aprueba, publica y revisa periodicamente una politica de seguridad de la informacion y las politicas especificas que dependen de ella."),
"5.2":("Every information security responsibility is assigned to a named role and communicated, so that nothing depends on goodwill.",
       "Cada responsabilidad de seguridad de la informacion se asigna a un rol concreto y se comunica, de modo que nada dependa de la buena voluntad."),
"5.3":("Conflicting duties are separated so that no single person can execute and conceal fraud or error.",
       "Las funciones en conflicto se separan para que ninguna persona pueda ejecutar y ocultar por si sola un fraude o un error."),
"5.4":("Management requires and visibly supports the application of security by all personnel, in line with policy.",
       "La direccion exige y respalda de forma visible que todo el personal aplique la seguridad conforme a la politica."),
"5.5":("The organisation knows which authorities to contact, when and how, and keeps those channels ready.",
       "La organizacion sabe con que autoridades contactar, cuando y como, y mantiene esos canales preparados."),
"5.6":("Contacts with professional bodies, forums and peer groups keep the organisation informed about threats and practice.",
       "Los contactos con asociaciones profesionales, foros y grupos de pares mantienen a la organizacion al dia de amenazas y practicas."),
"5.7":("Information about threats is collected, analysed and turned into actions that reduce risk.",
       "La informacion sobre amenazas se recopila, analiza y convierte en acciones que reducen el riesgo."),
"5.8":("Security is built into every project, whatever its nature, from initiation to closure.",
       "La seguridad se integra en todo proyecto, sea del tipo que sea, desde su inicio hasta su cierre."),
"5.9":("An inventory of information and associated assets is kept, with an owner for each entry.",
       "Se mantiene un inventario de la informacion y los activos asociados, con un propietario para cada entrada."),
"5.10":("Rules for the acceptable use and handling of information and assets are defined and communicated.",
        "Se definen y comunican las reglas de uso aceptable y manejo de la informacion y los activos."),
"5.11":("Personnel and third parties return all organisational assets when their engagement ends or changes.",
        "El personal y los terceros devuelven todos los activos de la organizacion al terminar o cambiar su relacion."),
"5.12":("Information is classified by its confidentiality, integrity and availability needs and by stakeholder requirements.",
        "La informacion se clasifica segun sus necesidades de confidencialidad, integridad y disponibilidad y los requisitos de las partes interesadas."),
"5.13":("Labelling procedures make the classification visible on information and in systems, following the scheme adopted.",
        "Los procedimientos de etiquetado hacen visible la clasificacion en la informacion y en los sistemas, segun el esquema adoptado."),
"5.14":("Rules, procedures and agreements govern how information is transferred inside and outside the organisation, by any means.",
        "Reglas, procedimientos y acuerdos rigen como se transfiere la informacion dentro y fuera de la organizacion, por cualquier medio."),
"5.15":("Rules restrict logical and physical access to information and assets according to business and security requirements.",
        "Unas reglas restringen el acceso logico y fisico a la informacion y los activos segun los requisitos del negocio y de seguridad."),
"5.16":("The full lifecycle of identities is managed: creation, uniqueness, changes and removal, for people and for systems.",
        "Se gestiona todo el ciclo de vida de las identidades: creacion, unicidad, cambios y baja, tanto de personas como de sistemas."),
"5.17":("Passwords and other authentication secrets are allocated, protected and changed through a controlled process.",
        "Las contrasenas y otros secretos de autenticacion se asignan, protegen y cambian mediante un proceso controlado."),
"5.18":("Access rights are provisioned, reviewed, modified and revoked in line with the access control policy.",
        "Los derechos de acceso se conceden, revisan, modifican y revocan de acuerdo con la politica de control de acceso."),
"5.19":("Processes manage the risks that come from suppliers having access to the organisation's information or assets.",
        "Unos procesos gestionan los riesgos derivados de que los proveedores accedan a la informacion o los activos de la organizacion."),
"5.20":("Supplier agreements set out the security requirements each party must meet.",
        "Los acuerdos con proveedores establecen los requisitos de seguridad que cada parte debe cumplir."),
"5.21":("Risks in the ICT products and services supply chain are identified and managed, beyond the direct supplier.",
        "Los riesgos en la cadena de suministro de productos y servicios TIC se identifican y gestionan, mas alla del proveedor directo."),
"5.22":("Supplier service delivery is monitored, reviewed and its changes evaluated for their impact on security.",
        "La prestacion de servicios de los proveedores se supervisa, se revisa y sus cambios se evaluan por su impacto en la seguridad."),
"5.23":("Acquisition, use, management and exit from cloud services follow the organisation's security requirements.",
        "La adquisicion, uso, gestion y salida de servicios en la nube siguen los requisitos de seguridad de la organizacion."),
"5.24":("Incident management is planned in advance: roles, procedures, contacts and tooling to respond quickly and in order.",
        "La gestion de incidentes se planifica de antemano: roles, procedimientos, contactos y herramientas para responder con rapidez y orden."),
"5.25":("Security events are assessed and it is decided whether they constitute incidents and with what priority.",
        "Los eventos de seguridad se evaluan y se decide si constituyen incidentes y con que prioridad."),
"5.26":("Incidents are responded to following documented procedures: containment, eradication, recovery and communication.",
        "Los incidentes se atienden siguiendo procedimientos documentados: contencion, erradicacion, recuperacion y comunicacion."),
"5.27":("Lessons from incidents feed back into controls, so that the same failure is not repeated.",
        "Las lecciones de los incidentes retroalimentan los controles, para que el mismo fallo no se repita."),
"5.28":("Evidence related to security events is identified, collected, acquired and preserved so that it is admissible.",
        "Las evidencias relacionadas con eventos de seguridad se identifican, recopilan, adquieren y preservan de forma que sean admisibles."),
"5.29":("The organisation plans how to keep information security at the required level during a disruption.",
        "La organizacion planifica como mantener la seguridad de la informacion al nivel requerido durante una interrupcion."),
"5.30":("ICT continuity is planned, implemented, maintained and tested according to business continuity objectives.",
        "La continuidad de las TIC se planifica, implanta, mantiene y prueba conforme a los objetivos de continuidad de negocio."),
"5.31":("The legal, statutory, regulatory and contractual requirements relevant to security are identified, documented and kept up to date.",
        "Los requisitos legales, estatutarios, reglamentarios y contractuales relevantes para la seguridad se identifican, documentan y mantienen al dia."),
"5.32":("Procedures protect intellectual property rights and ensure that only licensed software and content are used.",
        "Unos procedimientos protegen los derechos de propiedad intelectual y aseguran que solo se usen software y contenidos con licencia."),
"5.33":("Records are protected from loss, destruction, falsification and unauthorised access, for as long as they must be kept.",
        "Los registros se protegen frente a perdida, destruccion, falsificacion y acceso no autorizado durante el tiempo en que deban conservarse."),
"5.34":("Privacy and personal data protection requirements are identified and met according to applicable law and contracts.",
        "Los requisitos de privacidad y proteccion de datos personales se identifican y cumplen conforme a la ley y los contratos aplicables."),
"5.35":("The organisation's approach to security and its implementation are reviewed independently at planned intervals and after significant change.",
        "El enfoque de seguridad de la organizacion y su implantacion se revisan de forma independiente a intervalos planificados y tras cambios significativos."),
"5.36":("Compliance with the security policy, rules and standards is regularly reviewed by managers and corrected where needed.",
        "El cumplimiento de la politica, reglas y normas de seguridad se revisa regularmente por los responsables y se corrige cuando es necesario."),
"5.37":("Operating procedures for information processing facilities are documented and available to those who need them.",
        "Los procedimientos operativos de las instalaciones de tratamiento de la informacion estan documentados y disponibles para quien los necesita."),
"6.1":("Candidates are vetted before joining, and periodically afterwards, in proportion to the risk of the role.",
       "Los candidatos se verifican antes de incorporarse, y periodicamente despues, en proporcion al riesgo del puesto."),
"6.2":("Employment contracts state the information security responsibilities of the person and of the organisation.",
       "Los contratos de trabajo recogen las responsabilidades de seguridad de la informacion de la persona y de la organizacion."),
"6.3":("Personnel and relevant third parties receive awareness, education and training appropriate to their role and updated over time.",
       "El personal y los terceros relevantes reciben concienciacion, educacion y formacion adecuadas a su rol y actualizadas en el tiempo."),
"6.4":("A formal disciplinary process handles security policy violations, known to and applied on all personnel.",
       "Un proceso disciplinario formal trata las violaciones de la politica de seguridad, conocido y aplicable a todo el personal."),
"6.5":("Security duties that survive termination or change of employment are defined, communicated and enforced.",
       "Las obligaciones de seguridad que perduran tras el cese o cambio de empleo se definen, comunican y hacen cumplir."),
"6.6":("Confidentiality or non-disclosure agreements reflect the organisation's needs and are signed by personnel and third parties.",
       "Los acuerdos de confidencialidad o no divulgacion reflejan las necesidades de la organizacion y los firman el personal y los terceros."),
"6.7":("Security measures protect information accessed, processed or stored when personnel work outside the premises.",
       "Medidas de seguridad protegen la informacion a la que se accede, se procesa o se almacena cuando el personal trabaja fuera de las instalaciones."),
"6.8":("Personnel can report observed or suspected security events quickly through an appropriate channel.",
       "El personal puede notificar con rapidez, por un canal adecuado, los eventos de seguridad observados o sospechados."),
"7.1":("Physical perimeters are defined and used to protect areas holding information and assets.",
       "Se definen y usan perimetros fisicos para proteger las areas que albergan informacion y activos."),
"7.2":("Entry controls ensure that only authorised people access secure areas.",
       "Controles de entrada garantizan que solo las personas autorizadas acceden a las areas seguras."),
"7.3":("Offices, rooms and facilities are designed and protected physically.",
       "Las oficinas, despachos e instalaciones se disenan y protegen fisicamente."),
"7.4":("Premises are continuously monitored for unauthorised physical access.",
       "Las instalaciones se vigilan de forma continua frente a accesos fisicos no autorizados."),
"7.5":("Protection against fire, flood, earthquake, explosion, civil unrest and other physical or environmental threats is designed and implemented.",
       "Se disena e implanta proteccion frente a incendio, inundacion, terremoto, explosion, disturbios y otras amenazas fisicas o ambientales."),
"7.6":("Rules govern how people work inside secure areas.",
       "Unas reglas rigen como se trabaja dentro de las areas seguras."),
"7.7":("Rules for a clear desk of papers and media and a clear screen are defined and enforced.",
       "Se definen y aplican reglas de puesto de trabajo despejado de papeles y soportes y de pantalla limpia."),
"7.8":("Equipment is sited and protected to reduce environmental risks and opportunities for unauthorised access.",
       "Los equipos se ubican y protegen para reducir los riesgos ambientales y las oportunidades de acceso no autorizado."),
"7.9":("Assets taken or used off-site are protected.",
       "Los activos que salen de las instalaciones o se usan fuera de ellas estan protegidos."),
"7.10":("Storage media are managed across their lifecycle: acquisition, use, transport and disposal, according to classification.",
        "Los soportes de almacenamiento se gestionan durante todo su ciclo de vida: adquisicion, uso, transporte y eliminacion, segun su clasificacion."),
"7.11":("Information processing facilities are protected from power failures and other disruptions of supporting utilities.",
        "Las instalaciones de tratamiento de la informacion estan protegidas frente a fallos electricos y otras interrupciones de los suministros."),
"7.12":("Cables carrying power, data or services are protected from interception, interference and damage.",
        "Los cables que transportan energia, datos o servicios se protegen frente a interceptacion, interferencias y danos."),
"7.13":("Equipment is maintained correctly to ensure its availability, integrity and confidentiality.",
        "Los equipos se mantienen correctamente para asegurar su disponibilidad, integridad y confidencialidad."),
"7.14":("Before disposal or re-use, equipment is checked and any sensitive data or licensed software is removed or securely overwritten.",
        "Antes de eliminar o reutilizar un equipo se verifica y se elimina o sobrescribe de forma segura cualquier dato sensible o software con licencia."),
"8.1":("Information on and accessed through user endpoint devices is protected: configuration, encryption, remote wipe and user rules.",
       "La informacion en los dispositivos de usuario final, y la accesible a traves de ellos, esta protegida: configuracion, cifrado, borrado remoto y reglas de uso."),
"8.2":("Privileged access rights are allocated and managed restrictively, and their use is subject to control.",
       "Los derechos de acceso privilegiado se asignan y gestionan de forma restrictiva y su uso esta sujeto a control."),
"8.3":("Access to information and assets is restricted according to the access control policy.",
       "El acceso a la informacion y los activos se restringe de acuerdo con la politica de control de acceso."),
"8.4":("Read and write access to source code, development tools and software libraries is managed.",
       "El acceso de lectura y escritura al codigo fuente, las herramientas de desarrollo y las bibliotecas de software esta gestionado."),
"8.5":("Authentication technologies and procedures are proportionate to the access restriction, including multi-factor where warranted.",
       "Las tecnologias y procedimientos de autenticacion son proporcionales a la restriccion de acceso, incluido el multifactor cuando esta justificado."),
"8.6":("Resource use is monitored and adjusted to current and expected capacity requirements.",
       "El uso de los recursos se supervisa y ajusta a las necesidades de capacidad actuales y previstas."),
"8.7":("Protection against malware combines technical controls with user awareness.",
       "La proteccion frente al malware combina controles tecnicos con la concienciacion de los usuarios."),
"8.8":("Information about technical vulnerabilities is obtained, exposure is evaluated and appropriate measures are taken.",
       "Se obtiene informacion sobre vulnerabilidades tecnicas, se evalua la exposicion y se toman las medidas apropiadas."),
"8.9":("Configurations, including security configurations, of hardware, software, services and networks are established, documented, monitored and reviewed.",
       "Las configuraciones, incluidas las de seguridad, del hardware, software, servicios y redes se establecen, documentan, supervisan y revisan."),
"8.10":("Information is deleted from systems, devices and media when it is no longer required.",
        "La informacion se borra de sistemas, dispositivos y soportes cuando ya no es necesaria."),
"8.11":("Data masking is applied according to the access control policy and business requirements, taking legislation into account.",
        "El enmascaramiento de datos se aplica segun la politica de control de acceso y los requisitos del negocio, teniendo en cuenta la legislacion."),
"8.12":("Data leakage prevention measures are applied to systems, networks and devices that handle sensitive information.",
        "Se aplican medidas de prevencion de fuga de datos a los sistemas, redes y dispositivos que tratan informacion sensible."),
"8.13":("Backup copies of information, software and systems are kept and regularly tested according to the backup policy.",
        "Se mantienen copias de seguridad de la informacion, el software y los sistemas y se prueban regularmente segun la politica de copias."),
"8.14":("Information processing facilities have enough redundancy to meet availability requirements.",
        "Las instalaciones de tratamiento de la informacion tienen redundancia suficiente para cumplir los requisitos de disponibilidad."),
"8.15":("Logs recording activities, exceptions, faults and relevant events are produced, stored, protected and analysed.",
        "Se generan, almacenan, protegen y analizan registros de actividades, excepciones, fallos y eventos relevantes."),
"8.16":("Networks, systems and applications are monitored for anomalous behaviour and appropriate action is taken.",
        "Las redes, sistemas y aplicaciones se supervisan para detectar comportamientos anomalos y actuar en consecuencia."),
"8.17":("Clocks of the information processing systems are synchronised to approved time sources.",
        "Los relojes de los sistemas de tratamiento de la informacion se sincronizan con fuentes de tiempo aprobadas."),
"8.18":("The use of utility programs that could override system and application controls is restricted and tightly controlled.",
        "El uso de programas de utilidad capaces de eludir los controles del sistema y de las aplicaciones esta restringido y estrechamente controlado."),
"8.19":("Procedures and measures securely manage the installation of software on operational systems.",
        "Procedimientos y medidas gestionan de forma segura la instalacion de software en los sistemas en produccion."),
"8.20":("Networks and network devices are secured, managed and controlled to protect the information in systems and applications.",
        "Las redes y los dispositivos de red se protegen, gestionan y controlan para proteger la informacion de los sistemas y aplicaciones."),
"8.21":("Security mechanisms, service levels and requirements for network services are identified, implemented and monitored.",
        "Los mecanismos de seguridad, niveles de servicio y requisitos de los servicios de red se identifican, implantan y supervisan."),
"8.22":("Groups of information services, users and systems are segregated in the organisation's networks.",
        "Los grupos de servicios de informacion, usuarios y sistemas se segregan en las redes de la organizacion."),
"8.23":("Access to external websites is managed to reduce exposure to malicious content.",
        "El acceso a sitios web externos se gestiona para reducir la exposicion a contenidos maliciosos."),
"8.24":("Rules for the effective use of cryptography, including key management, are defined and implemented.",
        "Se definen e implantan reglas para el uso eficaz de la criptografia, incluida la gestion de claves."),
"8.25":("Rules for secure development of software and systems are established and applied.",
        "Se establecen y aplican reglas para el desarrollo seguro de software y sistemas."),
"8.26":("Security requirements are identified, specified and approved when applications are developed or acquired.",
        "Los requisitos de seguridad se identifican, especifican y aprueban al desarrollar o adquirir aplicaciones."),
"8.27":("Principles for engineering secure systems are established, documented, maintained and applied to development.",
        "Se establecen, documentan, mantienen y aplican principios de ingenieria de sistemas seguros en el desarrollo."),
"8.28":("Secure coding principles are applied to software development.",
        "Se aplican principios de codificacion segura en el desarrollo de software."),
"8.29":("Security testing processes are defined and implemented in the development lifecycle.",
        "Se definen e implantan procesos de pruebas de seguridad en el ciclo de vida de desarrollo."),
"8.30":("The organisation directs, monitors and reviews the activities of outsourced system development.",
        "La organizacion dirige, supervisa y revisa las actividades del desarrollo de sistemas externalizado."),
"8.31":("Development, test and production environments are separated and secured.",
        "Los entornos de desarrollo, prueba y produccion estan separados y protegidos."),
"8.32":("Changes to information processing facilities and systems are subject to change management procedures.",
        "Los cambios en las instalaciones y sistemas de tratamiento de la informacion estan sujetos a procedimientos de gestion de cambios."),
"8.33":("Test information is appropriately selected, protected and managed.",
        "La informacion de prueba se selecciona, protege y gestiona adecuadamente."),
"8.34":("Audit tests and other assurance activities on operational systems are planned and agreed between the tester and management.",
        "Las pruebas de auditoria y otras actividades de aseguramiento sobre sistemas en produccion se planifican y acuerdan entre el auditor y la direccion."),
}
path = pathlib.Path("crossmap/data/controls_iso.json")
data = json.loads(path.read_text(encoding="utf-8"))
for item in data["items"]:
    en, es = S[item["id"]]
    item["summary"] = {"en": en, "es": es}
missing = set(S) - {i["id"] for i in data["items"]}
assert not missing, missing
path.write_text(json.dumps(data, ensure_ascii=False, indent=1))
print("resumenes:", len(S))
