import json, pathlib
C = [
("5.1","Policies for information security","Politicas de seguridad de la informacion"),
("5.2","Information security roles and responsibilities","Funciones y responsabilidades en seguridad de la informacion"),
("5.3","Segregation of duties","Segregacion de tareas"),
("5.4","Management responsibilities","Responsabilidades de la direccion"),
("5.5","Contact with authorities","Contacto con las autoridades"),
("5.6","Contact with special interest groups","Contacto con grupos de interes especial"),
("5.7","Threat intelligence","Inteligencia de amenazas"),
("5.8","Information security in project management","Seguridad de la informacion en la gestion de proyectos"),
("5.9","Inventory of information and other associated assets","Inventario de informacion y otros activos asociados"),
("5.10","Acceptable use of information and other associated assets","Uso aceptable de la informacion y otros activos asociados"),
("5.11","Return of assets","Devolucion de activos"),
("5.12","Classification of information","Clasificacion de la informacion"),
("5.13","Labelling of information","Etiquetado de la informacion"),
("5.14","Information transfer","Transferencia de informacion"),
("5.15","Access control","Control de acceso"),
("5.16","Identity management","Gestion de identidades"),
("5.17","Authentication information","Informacion de autenticacion"),
("5.18","Access rights","Derechos de acceso"),
("5.19","Information security in supplier relationships","Seguridad de la informacion en las relaciones con proveedores"),
("5.20","Addressing information security within supplier agreements","Tratamiento de la seguridad de la informacion en los acuerdos con proveedores"),
("5.21","Managing information security in the ICT supply chain","Gestion de la seguridad de la informacion en la cadena de suministro de TIC"),
("5.22","Monitoring, review and change management of supplier services","Seguimiento, revision y gestion de cambios de los servicios de proveedores"),
("5.23","Information security for use of cloud services","Seguridad de la informacion para el uso de servicios en la nube"),
("5.24","Information security incident management planning and preparation","Planificacion y preparacion de la gestion de incidentes de seguridad de la informacion"),
("5.25","Assessment and decision on information security events","Evaluacion y decision sobre los eventos de seguridad de la informacion"),
("5.26","Response to information security incidents","Respuesta a incidentes de seguridad de la informacion"),
("5.27","Learning from information security incidents","Aprendizaje de los incidentes de seguridad de la informacion"),
("5.28","Collection of evidence","Recopilacion de evidencias"),
("5.29","Information security during disruption","Seguridad de la informacion durante la interrupcion"),
("5.30","ICT readiness for business continuity","Preparacion de las TIC para la continuidad de negocio"),
("5.31","Legal, statutory, regulatory and contractual requirements","Requisitos legales, estatutarios, reglamentarios y contractuales"),
("5.32","Intellectual property rights","Derechos de propiedad intelectual"),
("5.33","Protection of records","Proteccion de registros"),
("5.34","Privacy and protection of PII","Privacidad y proteccion de la informacion de identificacion personal"),
("5.35","Independent review of information security","Revision independiente de la seguridad de la informacion"),
("5.36","Compliance with policies, rules and standards for information security","Cumplimiento de las politicas, reglas y normas de seguridad de la informacion"),
("5.37","Documented operating procedures","Procedimientos operativos documentados"),
("6.1","Screening","Investigacion de antecedentes"),
("6.2","Terms and conditions of employment","Terminos y condiciones del empleo"),
("6.3","Information security awareness, education and training","Concienciacion, educacion y capacitacion en seguridad de la informacion"),
("6.4","Disciplinary process","Proceso disciplinario"),
("6.5","Responsibilities after termination or change of employment","Responsabilidades ante la finalizacion o el cambio de empleo"),
("6.6","Confidentiality or non-disclosure agreements","Acuerdos de confidencialidad o no divulgacion"),
("6.7","Remote working","Trabajo a distancia"),
("6.8","Information security event reporting","Notificacion de eventos de seguridad de la informacion"),
("7.1","Physical security perimeters","Perimetros de seguridad fisica"),
("7.2","Physical entry","Entrada fisica"),
("7.3","Securing offices, rooms and facilities","Seguridad de oficinas, despachos e instalaciones"),
("7.4","Physical security monitoring","Supervision de la seguridad fisica"),
("7.5","Protecting against physical and environmental threats","Proteccion contra amenazas fisicas y ambientales"),
("7.6","Working in secure areas","Trabajo en areas seguras"),
("7.7","Clear desk and clear screen","Puesto de trabajo despejado y pantalla limpia"),
("7.8","Equipment siting and protection","Emplazamiento y proteccion de equipos"),
("7.9","Security of assets off-premises","Seguridad de los activos fuera de las instalaciones"),
("7.10","Storage media","Soportes de almacenamiento"),
("7.11","Supporting utilities","Instalaciones de suministro"),
("7.12","Cabling security","Seguridad del cableado"),
("7.13","Equipment maintenance","Mantenimiento de equipos"),
("7.14","Secure disposal or re-use of equipment","Eliminacion o reutilizacion segura de equipos"),
("8.1","User endpoint devices","Dispositivos de usuario final"),
("8.2","Privileged access rights","Derechos de acceso privilegiado"),
("8.3","Information access restriction","Restriccion del acceso a la informacion"),
("8.4","Access to source code","Acceso al codigo fuente"),
("8.5","Secure authentication","Autenticacion segura"),
("8.6","Capacity management","Gestion de capacidades"),
("8.7","Protection against malware","Proteccion contra el malware"),
("8.8","Management of technical vulnerabilities","Gestion de las vulnerabilidades tecnicas"),
("8.9","Configuration management","Gestion de la configuracion"),
("8.10","Information deletion","Borrado de informacion"),
("8.11","Data masking","Enmascaramiento de datos"),
("8.12","Data leakage prevention","Prevencion de la fuga de datos"),
("8.13","Information backup","Copias de seguridad de la informacion"),
("8.14","Redundancy of information processing facilities","Redundancia de las instalaciones de tratamiento de la informacion"),
("8.15","Logging","Registro de eventos"),
("8.16","Monitoring activities","Actividades de seguimiento"),
("8.17","Clock synchronization","Sincronizacion de relojes"),
("8.18","Use of privileged utility programs","Uso de programas de utilidad privilegiados"),
("8.19","Installation of software on operational systems","Instalacion de software en sistemas operativos"),
("8.20","Networks security","Seguridad de redes"),
("8.21","Security of network services","Seguridad de los servicios de red"),
("8.22","Segregation of networks","Segregacion de redes"),
("8.23","Web filtering","Filtrado web"),
("8.24","Use of cryptography","Uso de criptografia"),
("8.25","Secure development life cycle","Ciclo de vida de desarrollo seguro"),
("8.26","Application security requirements","Requisitos de seguridad de las aplicaciones"),
("8.27","Secure system architecture and engineering principles","Principios de ingenieria y arquitectura de sistemas seguros"),
("8.28","Secure coding","Codificacion segura"),
("8.29","Security testing in development and acceptance","Pruebas de seguridad en desarrollo y aceptacion"),
("8.30","Outsourced development","Desarrollo externalizado"),
("8.31","Separation of development, test and production environments","Separacion de los entornos de desarrollo, prueba y produccion"),
("8.32","Change management","Gestion de cambios"),
("8.33","Test information","Informacion de prueba"),
("8.34","Protection of information systems during audit testing","Proteccion de los sistemas de informacion durante las pruebas de auditoria"),
]
THEME = {"5":("Organizational controls","Controles organizativos"),
         "6":("People controls","Controles de personas"),
         "7":("Physical controls","Controles fisicos"),
         "8":("Technological controls","Controles tecnologicos")}
out = {"framework":"ISO","items":[
 {"id":i,"family":i.split(".")[0],
  "family_title":{"en":THEME[i.split(".")[0]][0],"es":THEME[i.split(".")[0]][1]},
  "title":{"en":en,"es":es}} for i,en,es in C]}
pathlib.Path("crossmap/data/controls_iso.json").write_text(json.dumps(out, ensure_ascii=False, indent=1))
from collections import Counter
print("ISO:", len(C), "controles |", dict(Counter(i.split('.')[0] for i,_,_ in C)))
