D = {
"5.4": dict(
 covers=("Visible management commitment to security: it is required of everyone, resourced and enforced.",
         "Compromiso visible de la direccion con la seguridad: se exige a todos, se dota de recursos y se hace cumplir."),
 adds=("elc.1 is the COSO control environment applied to ICFR: the CEO and CFO certify each periodic report under Sections 302 and 906, management's tone concerns the reliability of financial reporting, and the audit committee oversees it; IT governance must show that the systems supporting the financial statements are under that same accountability. Management support for information security is a narrower commitment that the auditor does not test as such.",
       "elc.1 es el entorno de control de COSO aplicado al ICFR: el CEO y el CFO certifican cada informe periodico bajo las secciones 302 y 906, el tono de la direccion se refiere a la fiabilidad de la informacion financiera, y el comite de auditoria lo supervisa; el gobierno de TI debe mostrar que los sistemas que soportan los estados financieros estan bajo esa misma responsabilidad. El respaldo de la direccion a la seguridad de la informacion es un compromiso mas estrecho que el auditor no prueba como tal."),
 close=("Document the IT governance structure (steering committee, reporting to the audit committee) and the sub-certifications IT management signs for 302.",
        "Documentar la estructura de gobierno de TI (comite de direccion, reporte al comite de auditoria) y las subcertificaciones que firma la direccion de TI para la 302.")),
"5.8": dict(
 covers=("Security requirements and risk assessed in every project from initiation to closure.",
         "Requisitos de seguridad y riesgo evaluados en todo proyecto de principio a fin."),
 adds=("dev.1 wants a system development methodology for new financial systems and major enhancements with control points the auditor can test: approved requirements including the automated controls and reports the business relies on, user acceptance testing, and formal go-live approval; the objective is that the new system processes transactions completely and accurately, not that the project considered security.",
       "dev.1 quiere una metodologia de desarrollo de sistemas para los nuevos sistemas financieros y las mejoras importantes con puntos de control que el auditor pueda probar: requisitos aprobados que incluyan los controles automatizados y los informes en que se apoya el negocio, pruebas de aceptacion de usuario y aprobacion formal de la puesta en marcha; el objetivo es que el nuevo sistema procese las transacciones de forma completa y exacta, no que el proyecto haya considerado la seguridad."),
 close=("Add the SOX gates (approved requirements, UAT sign-off, go-live approval) to the project method for in-scope systems.",
        "Anadir los hitos SOX (requisitos aprobados, firma de UAT, aprobacion de puesta en marcha) al metodo de proyectos para los sistemas en alcance.")),
"5.9": dict(
 covers=("An inventory of information and associated assets with an owner for each.",
         "Un inventario de la informacion y los activos asociados con un propietario para cada uno."),
 adds=("elc.2 needs the SOX scoping: the financial processes and significant accounts, the applications that support them, the key reports and the underlying databases, operating systems and infrastructure, so that ITGC testing is limited to what matters for the financial statements. A general asset inventory does not carry that linkage from accounts to systems.",
       "elc.2 necesita el alcance SOX: los procesos financieros y las cuentas significativas, las aplicaciones que los soportan, los informes clave y las bases de datos, sistemas operativos e infraestructura subyacentes, de modo que las pruebas ITGC se limiten a lo que importa para los estados financieros. Un inventario general de activos no lleva ese enlace de cuentas a sistemas."),
 close=("Produce the SOX IT scoping document: application, database, OS and infrastructure layers per financial process, refreshed yearly.",
        "Elaborar el documento de alcance SOX de TI: capas de aplicacion, base de datos, sistema operativo e infraestructura por proceso financiero, actualizado anualmente.")),
"5.10": dict(
 covers=("A documented acceptable-use policy for information and assets, communicated to users.",
         "Una politica documentada de uso aceptable de la informacion y los activos, comunicada a los usuarios."),
 adds=("elc.3 requires the IT policies and procedures that govern the in-scope systems to be documented, approved by management, communicated and periodically reviewed; an acceptable-use policy is one of them, but the auditor is looking for the set: access, change, operations, security, with approval evidence and review dates.",
       "elc.3 exige que las politicas y procedimientos de TI que gobiernan los sistemas en alcance esten documentados, aprobados por la direccion, comunicados y revisados periodicamente; una politica de uso aceptable es una de ellas, pero el auditor busca el conjunto: acceso, cambios, operaciones, seguridad, con evidencia de aprobacion y fechas de revision."),
 close=("Keep an IT policy register with approval and review dates covering the four ITGC domains.",
        "Llevar un registro de politicas de TI con fechas de aprobacion y revision que cubra los cuatro dominios ITGC.")),
"5.11": dict(
 covers=("Equipment, information and credentials recovered when a person leaves.",
         "Equipos, informacion y credenciales recuperados cuando una persona se va."),
 adds=("acc.2 tests one thing: that logical access to the financial systems is removed promptly after termination or transfer, evidenced by reconciling the HR leaver list against the user lists of each in-scope application, database and OS. Returning the laptop is not what the auditor samples.",
       "acc.2 prueba una cosa: que el acceso logico a los sistemas financieros se retira con prontitud tras el cese o el traslado, evidenciado conciliando la lista de bajas de RR. HH. con las listas de usuarios de cada aplicacion, base de datos y sistema operativo en alcance. Devolver el portatil no es lo que muestrea el auditor."),
 close=("Run and keep the HR-to-user-list reconciliation for leavers, with removal dates, for every in-scope system.",
        "Ejecutar y conservar la conciliacion entre bajas de RR. HH. y listas de usuarios, con fechas de retirada, para cada sistema en alcance.")),
"5.14": dict(
 covers=("Rules and agreements for transferring information by any means, with encryption where needed.",
         "Reglas y acuerdos para transferir informacion por cualquier medio, con cifrado cuando haga falta."),
 adds=("ops.1 wants the interfaces that move financial data between systems (ERP to consolidation, sub-ledger to GL, bank files) scheduled, monitored for failures and reconciled for completeness and accuracy, with errors investigated; the security of information transfer in general is not the concern, the integrity of the transferred financial data is.",
       "ops.1 quiere que las interfaces que mueven datos financieros entre sistemas (ERP a consolidacion, auxiliares al mayor, ficheros bancarios) esten planificadas, supervisadas frente a fallos y conciliadas por integridad y exactitud, con los errores investigados; la seguridad de la transferencia de informacion en general no es la preocupacion, lo es la integridad de los datos financieros transferidos."),
 close=("Inventory the financial interfaces and evidence the monitoring and reconciliation of each.",
        "Inventariar las interfaces financieras y evidenciar la supervision y conciliacion de cada una.")),
"5.19": dict(
 covers=("A supplier security process: risk-based selection, requirements, monitoring, termination.",
         "Un proceso de seguridad de proveedores: seleccion basada en riesgo, requisitos, seguimiento, terminacion."),
 adds=("elc.5 requires, for every service organisation that processes financial transactions or hosts in-scope systems (payroll provider, SaaS ERP, data centre), a SOC 1 Type II report covering the fiscal period, reviewed for exceptions and for the subservice organisations carved out, with the complementary user entity controls (CUECs) mapped to the entity's own controls and tested. A supplier security process yields none of that assurance.",
       "elc.5 exige, para cada organizacion de servicios que procese transacciones financieras o aloje sistemas en alcance (proveedor de nomina, ERP SaaS, centro de datos), un informe SOC 1 tipo II que cubra el ejercicio, revisado por excepciones y por las suborganizaciones excluidas, con los controles complementarios de la entidad usuaria (CUEC) asociados a los controles propios y probados. Un proceso de seguridad de proveedores no produce ese aseguramiento."),
 close=("List the SOX-relevant service organisations, collect their SOC 1 Type II reports yearly and document the CUEC mapping.",
        "Listar las organizaciones de servicios relevantes para SOX, recoger anualmente sus informes SOC 1 tipo II y documentar la asociacion de CUEC.")),
"5.20": dict(
 covers=("Security requirements written into supplier agreements.",
         "Requisitos de seguridad recogidos en los acuerdos con proveedores."),
 adds=("elc.5 expects the contract with a service organisation to secure the right to receive a SOC 1 report (or to audit) and to be informed of control changes; security clauses in general are not what the auditor reads the contract for.",
       "elc.5 espera que el contrato con una organizacion de servicios asegure el derecho a recibir un informe SOC 1 (o a auditar) y a ser informado de cambios en los controles; las clausulas de seguridad en general no son lo que el auditor busca en el contrato."),
 close=("Add a SOC 1 / right-to-audit clause to contracts with SOX-relevant providers.",
        "Anadir una clausula de SOC 1 / derecho de auditoria a los contratos con proveedores relevantes para SOX.")),
"5.22": dict(
 covers=("Supplier services monitored and reviewed, with changes assessed for their impact.",
         "Servicios de proveedores supervisados y revisados, con los cambios evaluados por su impacto."),
 adds=("elc.5 monitors the provider through a defined ritual: annual SOC 1 Type II report reviewed, bridge letter obtained for the months between the report period end and the fiscal year end, exceptions evaluated for their impact on ICFR, and carved-out subservice organisations addressed. Monitoring service delivery is broader and does not produce that file.",
       "elc.5 supervisa al proveedor mediante un ritual definido: informe SOC 1 tipo II anual revisado, carta puente obtenida para los meses entre el fin del periodo del informe y el cierre del ejercicio, excepciones evaluadas por su impacto en el ICFR, y suborganizaciones excluidas tratadas. Supervisar la prestacion del servicio es mas amplio y no produce ese expediente."),
 close=("Keep a SOC 1 review memo per provider with exceptions, bridge letter and conclusion.",
        "Conservar un memorando de revision del SOC 1 por proveedor con excepciones, carta puente y conclusion.")),
"5.23": dict(
 covers=("A cloud policy on the customer side: risk assessment, shared responsibilities, data location, exit.",
         "Una politica de nube del lado del cliente: evaluacion de riesgos, responsabilidades compartidas, ubicacion de datos, salida."),
 adds=("elc.5 treats a cloud provider hosting a financial application or its infrastructure as a service organisation: SOC 1 Type II report, CUECs implemented by the entity (typically user access administration, change approval, interface monitoring), and evidence that the entity performs them. The customer-side policy ISO describes does not deliver the SOC 1 or the CUEC evidence.",
       "elc.5 trata a un proveedor de nube que aloja una aplicacion financiera o su infraestructura como una organizacion de servicios: informe SOC 1 tipo II, CUEC implantados por la entidad (normalmente administracion de accesos de usuario, aprobacion de cambios, supervision de interfaces) y evidencia de que la entidad los realiza. La politica de nube del lado del cliente que describe ISO no aporta el SOC 1 ni la evidencia de CUEC."),
 close=("Obtain the SOC 1 of each SaaS/IaaS provider hosting in-scope systems and assign each CUEC to an internal control owner.",
        "Obtener el SOC 1 de cada proveedor SaaS/IaaS que aloje sistemas en alcance y asignar cada CUEC a un responsable de control interno.")),
"5.24": dict(
 covers=("Incident management planned: roles, procedures, contacts and tooling.",
         "Gestion de incidentes planificada: roles, procedimientos, contactos y herramientas."),
 adds=("ops.3 is about incidents and problems that affect the processing or integrity of financial data: recorded in a ticketing tool, prioritised, resolved, escalated, and — the auditor's real interest — any data corrections traced and approved. Security incident planning covers a different population of events and does not address the financial-data correction trail.",
       "ops.3 trata de los incidentes y problemas que afectan al procesamiento o a la integridad de los datos financieros: registrados en una herramienta de tickets, priorizados, resueltos, escalados y — el verdadero interes del auditor — cualquier correccion de datos trazada y aprobada. La planificacion de incidentes de seguridad cubre otra poblacion de eventos y no trata el rastro de correcciones de datos financieros."),
 close=("Make sure incidents on in-scope systems are ticketed and that data fixes require documented approval.",
        "Asegurarse de que los incidentes en los sistemas en alcance se registran como tickets y de que las correcciones de datos exigen aprobacion documentada.")),
"5.25": dict(
 covers=("Security events assessed and classified, with a decision on whether they are incidents.",
         "Eventos de seguridad evaluados y clasificados, con una decision sobre si son incidentes."),
 adds=("ops.3 classifies incidents by their effect on financial processing (failed batch, interface error, wrong posting) and by whether financial data needs correction; the security triage of ISO uses confidentiality/integrity/availability criteria and does not flag the financial-statement impact.",
       "ops.3 clasifica los incidentes por su efecto en el procesamiento financiero (proceso por lotes fallido, error de interfaz, apunte incorrecto) y por si los datos financieros necesitan correccion; el triaje de seguridad de ISO usa criterios de confidencialidad, integridad y disponibilidad y no senala el impacto en los estados financieros."),
 close=("Add a 'financial data impact' flag to the incident classification for in-scope systems.",
        "Anadir un indicador de 'impacto en datos financieros' a la clasificacion de incidentes de los sistemas en alcance.")),
"5.26": dict(
 covers=("Incidents responded to per documented procedures: containment, eradication, recovery, communication.",
         "Incidentes atendidos segun procedimientos documentados: contencion, erradicacion, recuperacion, comunicacion."),
 adds=("ops.3 requires evidence that incidents affecting financial processing were resolved, that any resulting data corrections were made through approved means (not direct database updates without approval) and that the business owner confirmed the outcome; the security response playbook does not address the correction and approval of financial data.",
       "ops.3 exige evidencia de que los incidentes que afectaron al procesamiento financiero se resolvieron, de que cualquier correccion de datos resultante se hizo por medios aprobados (no actualizaciones directas de base de datos sin aprobacion) y de que el propietario de negocio confirmo el resultado; el manual de respuesta de seguridad no trata la correccion y aprobacion de datos financieros."),
 close=("Route data corrections through the change or data-fix procedure with business approval and keep the ticket trail.",
        "Canalizar las correcciones de datos por el procedimiento de cambios o de correccion de datos con aprobacion del negocio y conservar el rastro de tickets.")),
"5.27": dict(
 covers=("Lessons from incidents fed back into controls.",
         "Lecciones de los incidentes retroalimentadas a los controles."),
 adds=("ops.3 expects problem management: recurring failures in financial systems analysed for root cause and fixed permanently, with a record the auditor can follow from incident to problem to change; ISO's lessons learned concern the security controls, not the reliability of financial processing.",
       "ops.3 espera gestion de problemas: los fallos recurrentes en los sistemas financieros analizados por causa raiz y corregidos de forma permanente, con un registro que el auditor pueda seguir de incidente a problema a cambio; las lecciones aprendidas de ISO se refieren a los controles de seguridad, no a la fiabilidad del procesamiento financiero."),
 close=("Keep a problem record for recurring incidents on in-scope systems linked to the change that fixed them.",
        "Llevar un registro de problemas para los incidentes recurrentes en los sistemas en alcance, enlazado al cambio que los corrigio.")),
"5.29": dict(
 covers=("Plans to keep security at the required level during a disruption.",
         "Planes para mantener la seguridad al nivel requerido durante una interrupcion."),
 adds=("ops.4 cares that the systems supporting financial reporting can be recovered within a time that does not prevent closing the books, with a tested recovery plan; maintaining security during the disruption is not what is tested. Many audit firms treat ops.4 as out of SOX scope unless recovery failure could cause a misstatement.",
       "ops.4 se preocupa de que los sistemas que soportan la informacion financiera puedan recuperarse en un tiempo que no impida cerrar los libros, con un plan de recuperacion probado; mantener la seguridad durante la interrupcion no es lo que se prueba. Muchas firmas tratan ops.4 como fuera del alcance SOX salvo que un fallo de recuperacion pudiera causar un error material."),
 close=("Confirm with the auditor whether recovery is in scope; if so, evidence the recovery test of the financial systems.",
        "Confirmar con el auditor si la recuperacion esta en alcance; si lo esta, evidenciar la prueba de recuperacion de los sistemas financieros.")),
"5.31": dict(
 covers=("Legal, regulatory and contractual requirements identified, documented and assigned.",
         "Requisitos legales, reglamentarios y contractuales identificados, documentados y asignados."),
 adds=("Section 302 requires the CEO and CFO to certify each quarterly and annual report, including the effectiveness of disclosure controls and any changes in internal control; Section 404(a) requires management's annual assessment of ICFR and 404(b) the external auditor's attestation for accelerated filers. Identifying SOX as an applicable law puts it in the inventory; it does not perform the assessment, the testing or the certification.",
       "La seccion 302 exige que el CEO y el CFO certifiquen cada informe trimestral y anual, incluida la eficacia de los controles de divulgacion y cualquier cambio en el control interno; la seccion 404(a) exige la evaluacion anual del ICFR por la direccion y la 404(b) la atestacion del auditor externo para los emisores acelerados. Identificar SOX como ley aplicable la pone en el inventario; no realiza la evaluacion, las pruebas ni la certificacion."),
 close=("Establish the annual SOX programme: scoping, risk assessment, control matrix, testing calendar and sub-certifications.",
        "Establecer el programa SOX anual: alcance, evaluacion de riesgos, matriz de controles, calendario de pruebas y subcertificaciones.")),
"5.33": dict(
 covers=("Records protected against loss, tampering and unauthorised access for their retention period.",
         "Registros protegidos frente a perdida, manipulacion y acceso no autorizado durante su periodo de conservacion."),
 adds=("Section 802 makes it a crime to alter, destroy or falsify records to obstruct a federal investigation and requires auditors to retain audit and review workpapers for seven years (SEC Rule 2-06); the entity's own retention of financial records follows SEC and tax rules, typically seven years. ISO protects records without fixing periods and says nothing about the auditor's papers.",
       "La seccion 802 tipifica como delito alterar, destruir o falsificar registros para obstruir una investigacion federal y exige a los auditores conservar los papeles de trabajo de auditoria y revision durante siete anos (regla 2-06 de la SEC); la conservacion de los registros financieros por la propia entidad sigue las reglas de la SEC y fiscales, normalmente siete anos. ISO protege los registros sin fijar plazos y no dice nada de los papeles del auditor."),
 close=("Set a seven-year retention for financial records and SOX evidence in the records schedule and apply legal holds when needed.",
        "Fijar una conservacion de siete anos para los registros financieros y la evidencia SOX en el calendario de conservacion y aplicar retenciones legales cuando haga falta.")),
"5.35": dict(
 covers=("Periodic independent review of the security approach, reported to management.",
         "Revision independiente periodica del enfoque de seguridad, reportada a la direccion."),
 adds=("Section 404 requires management to assess ICFR every fiscal year against a recognised framework (COSO 2013), with the ITGCs tested for design and operating effectiveness over the period, and the external auditor to attest under PCAOB AS 2201 (for accelerated filers); elc.4 adds internal audit's own testing. It is annual by law, about financial reporting, and evidenced through walkthroughs and sample testing — none of which an ISO independent review provides.",
       "La seccion 404 exige que la direccion evalue el ICFR cada ejercicio contra un marco reconocido (COSO 2013), con los ITGC probados en diseno y eficacia operativa durante el periodo, y que el auditor externo lo ateste bajo PCAOB AS 2201 (para los emisores acelerados); elc.4 anade las pruebas propias de auditoria interna. Es anual por ley, trata de la informacion financiera y se evidencia mediante recorridos y pruebas por muestreo — nada de lo cual aporta una revision independiente ISO."),
 close=("Run the yearly ITGC testing cycle (design and operating effectiveness) and keep the workpapers for the external auditor.",
        "Ejecutar el ciclo anual de pruebas ITGC (diseno y eficacia operativa) y conservar los papeles de trabajo para el auditor externo.")),
"5.36": dict(
 covers=("Managers periodically check compliance with policies and standards and correct deviations.",
         "Los responsables comprueban periodicamente el cumplimiento de politicas y normas y corrigen las desviaciones."),
 adds=("elc.4 requires control deficiencies to be evaluated by severity — deficiency, significant deficiency or material weakness — using likelihood and magnitude, aggregated, remediated before year end where possible, and reported to the audit committee; a material weakness must be disclosed. A management compliance review has neither the grading nor the disclosure consequence.",
       "elc.4 exige evaluar las deficiencias de control por gravedad — deficiencia, deficiencia significativa o debilidad material — segun probabilidad y magnitud, agregarlas, remediarlas antes del cierre cuando sea posible y reportarlas al comite de auditoria; una debilidad material debe divulgarse. Una revision de cumplimiento de la direccion no tiene ni la graduacion ni la consecuencia de divulgacion."),
 close=("Keep a deficiency log with severity rating, remediation owner and date, reviewed by the audit committee.",
        "Llevar un registro de deficiencias con valoracion de gravedad, responsable y fecha de remediacion, revisado por el comite de auditoria.")),
"5.37": dict(
 covers=("Operating procedures documented, current and available to those who need them.",
         "Procedimientos operativos documentados, actualizados y disponibles para quienes los necesitan."),
 adds=("elc.3 wants the IT policies approved and reviewed; ops.1 wants, specifically, the batch schedule and run-books for the jobs and interfaces that process financial data, so that failures are detected and re-runs controlled. General operating procedures satisfy elc.3; ops.1 needs the job-level documentation and the evidence of monitoring.",
       "elc.3 quiere las politicas de TI aprobadas y revisadas; ops.1 quiere, en concreto, el calendario de procesos por lotes y las guias de ejecucion de los trabajos e interfaces que procesan datos financieros, para que los fallos se detecten y las reejecuciones esten controladas. Los procedimientos operativos generales satisfacen elc.3; ops.1 necesita la documentacion a nivel de trabajo y la evidencia de supervision."),
 close=("Document the financial batch schedule with owners and failure-handling steps.",
        "Documentar el calendario de procesos financieros por lotes con responsables y pasos ante fallos.")),
"6.3": dict(
 covers=("Awareness, education and training on information security for personnel and third parties.",
         "Concienciacion, educacion y formacion en seguridad de la informacion para el personal y los terceros."),
 adds=("elc.1 (COSO principle 4) expects the organisation to attract, develop and retain competent people and to make them aware of their internal control responsibilities, including IT staff who operate the ITGCs; security awareness training covers a different subject and is not what the auditor asks for.",
       "elc.1 (principio 4 de COSO) espera que la organizacion atraiga, desarrolle y retenga a personas competentes y las haga conscientes de sus responsabilidades de control interno, incluido el personal de TI que opera los ITGC; la formacion en concienciacion de seguridad cubre otro tema y no es lo que pide el auditor."),
 close=("Include ICFR/ITGC responsibilities in the training of IT staff who perform key controls, and keep attendance evidence.",
        "Incluir las responsabilidades ICFR/ITGC en la formacion del personal de TI que realiza controles clave, y conservar la evidencia de asistencia.")),
"6.5": dict(
 covers=("Security duties surviving termination or change of role, communicated and enforced.",
         "Deberes de seguridad que perduran tras el cese o cambio de puesto, comunicados y exigidos."),
 adds=("acc.2 requires access to be removed within a defined number of days (commonly the same day for terminations, a few days for transfers), evidenced by a reconciliation of the HR leaver and transfer list against the user lists of every in-scope layer, with exceptions explained; the ISO control is about the person's obligations, not the timeliness of revocation.",
       "acc.2 exige retirar el acceso en un numero definido de dias (normalmente el mismo dia en los ceses, unos dias en los traslados), evidenciado por una conciliacion de la lista de bajas y traslados de RR. HH. con las listas de usuarios de cada capa en alcance, con las excepciones explicadas; el control ISO trata de las obligaciones de la persona, no de la rapidez de la revocacion."),
 close=("Define the revocation SLA and run the periodic HR-to-system reconciliation as the control evidence.",
        "Definir el SLA de revocacion y ejecutar la conciliacion periodica entre RR. HH. y sistemas como evidencia del control.")),
"6.7": dict(
 covers=("A remote-working policy covering environment, device, connection, rules and support.",
         "Una politica de trabajo a distancia que cubre entorno, dispositivo, conexion, reglas y soporte."),
 adds=("acc.5 expects remote access to the financial systems to be authenticated with MFA or an equivalent, through an approved gateway, and logged; the rest of the remote-working arrangement is not an ITGC.",
       "acc.5 espera que el acceso remoto a los sistemas financieros se autentique con MFA o un equivalente, a traves de una pasarela aprobada, y se registre; el resto del regimen de trabajo a distancia no es un ITGC."),
 close=("Evidence MFA on the VPN or gateway used to reach in-scope systems.",
        "Evidenciar MFA en la VPN o pasarela usada para llegar a los sistemas en alcance.")),
"6.8": dict(
 covers=("A channel for anyone to report security events quickly.",
         "Un canal para que cualquiera notifique con rapidez los eventos de seguridad."),
 adds=("ops.3 needs a ticketing channel through which users and operators report failures in financial systems, so that every incident is recorded and traceable; a security event channel is a different route, though the two can be the same tool.",
       "ops.3 necesita un canal de tickets por el que usuarios y operadores notifiquen los fallos en los sistemas financieros, para que todo incidente quede registrado y sea trazable; un canal de eventos de seguridad es una via distinta, aunque ambos pueden ser la misma herramienta."),
 close=("Use one service desk for both and tag incidents on in-scope systems.",
        "Usar un unico servicio de atencion para ambos y etiquetar los incidentes de los sistemas en alcance.")),
"7.3": dict(
 covers=("Offices, rooms and facilities physically secured.",
         "Oficinas, salas e instalaciones protegidas fisicamente."),
 adds=("acc.7 restricts physical access to the data centres and server rooms hosting in-scope systems: badge access limited to a list, reviewed periodically, visitor logs, and — if outsourced — the provider's SOC 1 covering it. Offices are not tested.",
       "acc.7 restringe el acceso fisico a los centros de datos y salas de servidores que alojan sistemas en alcance: acceso por tarjeta limitado a una lista, revisada periodicamente, registros de visitantes y — si esta externalizado — el SOC 1 del proveedor que lo cubra. Las oficinas no se prueban."),
 close=("Keep the data-centre access list and its periodic review as the control evidence.",
        "Conservar la lista de acceso al centro de datos y su revision periodica como evidencia del control.")),
"7.4": dict(
 covers=("Continuous physical monitoring of premises with alerts and review.",
         "Vigilancia fisica continua de las instalaciones con alertas y revision."),
 adds=("acc.7 wants access to the data centre logged and the access list reviewed; cameras and continuous surveillance are not required, though they may serve as evidence.",
       "acc.7 quiere que el acceso al centro de datos se registre y que la lista de acceso se revise; las camaras y la vigilancia continua no se exigen, aunque pueden servir de evidencia."),
 close=("Nothing further for SOX beyond the access logs.",
        "Nada mas para SOX mas alla de los registros de acceso.")),
"7.5": dict(
 covers=("Protection designed against fire, flood, earthquake and other physical or environmental threats.",
         "Proteccion disenada frente a incendio, inundacion, terremoto y otras amenazas fisicas o ambientales."),
 adds=("ops.4 cares about environmental protection of the data centre only as it supports the recovery of financial systems (fire suppression, UPS, cooling), and often only when recovery is in SOX scope.",
       "ops.4 se ocupa de la proteccion ambiental del centro de datos solo en la medida en que soporta la recuperacion de los sistemas financieros (extincion, SAI, refrigeracion), y a menudo solo cuando la recuperacion esta en alcance SOX."),
 close=("Nothing further unless recovery is in scope; then evidence the environmental controls of the data centre.",
        "Nada mas salvo que la recuperacion este en alcance; entonces evidenciar los controles ambientales del centro de datos.")),
"7.6": dict(
 covers=("Rules of conduct inside secure areas.",
         "Reglas de conducta dentro de las areas seguras."),
 adds=("acc.7 controls who enters the data centre; behaviour inside is not tested.",
       "acc.7 controla quien entra en el centro de datos; el comportamiento dentro no se prueba."),
 close=("Nothing further for SOX.",
        "Nada mas para SOX.")),
"7.8": dict(
 covers=("Equipment sited to reduce environmental risk and unauthorised access.",
         "Equipos ubicados para reducir el riesgo ambiental y el acceso no autorizado."),
 adds=("acc.7 concerns the physical protection of the servers hosting financial systems, typically satisfied by their being in a controlled data centre; the siting of other equipment is out of scope.",
       "acc.7 concierne a la proteccion fisica de los servidores que alojan sistemas financieros, normalmente satisfecha por estar en un centro de datos controlado; la ubicacion de otros equipos queda fuera."),
 close=("Nothing further for SOX.",
        "Nada mas para SOX.")),
"7.10": dict(
 covers=("Storage media managed across their lifecycle according to classification.",
         "Soportes de almacenamiento gestionados durante todo su ciclo de vida segun la clasificacion."),
 adds=("ops.2 covers backup media: rotation, off-site storage, and the ability to restore financial data; media in general are not an ITGC.",
       "ops.2 cubre los soportes de copia: rotacion, custodia externa y capacidad de restaurar los datos financieros; los soportes en general no son un ITGC."),
 close=("Evidence off-site backup custody for the financial systems.",
        "Evidenciar la custodia externa de las copias de los sistemas financieros.")),
"7.11": dict(
 covers=("Protection against failure of power, cooling and other supporting utilities.",
         "Proteccion frente a fallos de energia, refrigeracion y otros suministros."),
 adds=("ops.4 expects power and environmental resilience only for the in-scope systems and only as part of recoverability; it is frequently out of SOX scope.",
       "ops.4 espera resiliencia electrica y ambiental solo para los sistemas en alcance y solo como parte de la recuperabilidad; con frecuencia queda fuera del alcance SOX."),
 close=("Nothing further unless recovery is in scope.",
        "Nada mas salvo que la recuperacion este en alcance.")),
"8.4": dict(
 covers=("Access to source code and development tools restricted and logged.",
         "Acceso al codigo fuente y a las herramientas de desarrollo restringido y registrado."),
 adds=("chg.3 tests that developers do not have access to migrate code into production and, ideally, no update access to production code, objects or data (or that a detective control such as a review of production changes compensates); access to the source code in the development environment is not restricted as such.",
       "chg.3 prueba que los desarrolladores no tienen acceso para migrar codigo a produccion y, a ser posible, ningun acceso de actualizacion al codigo, objetos o datos de produccion (o que un control detectivo, como una revision de los cambios en produccion, lo compensa); el acceso al codigo fuente en el entorno de desarrollo no se restringe como tal."),
 close=("Evidence that developer accounts have no migrate or update rights in production, or document the compensating review.",
        "Evidenciar que las cuentas de desarrollador no tienen derechos de migracion ni actualizacion en produccion, o documentar la revision compensatoria.")),
"8.8": dict(
 covers=("Vulnerability information obtained, exposure evaluated and measures taken.",
         "Informacion de vulnerabilidades obtenida, exposicion evaluada y medidas tomadas."),
 adds=("chg.5 tests that patches and configuration changes to in-scope infrastructure follow the change process — approval, testing where feasible, documented deployment; the identification and risk-ranking of vulnerabilities is not an ITGC and the auditor does not test scan results.",
       "chg.5 prueba que los parches y cambios de configuracion en la infraestructura en alcance siguen el proceso de cambios — aprobacion, pruebas cuando sea posible, despliegue documentado; la identificacion y clasificacion de vulnerabilidades no es un ITGC y el auditor no prueba los resultados de los analisis."),
 close=("Route patches to in-scope systems through change tickets with approval evidence.",
        "Canalizar los parches de los sistemas en alcance por tickets de cambio con evidencia de aprobacion.")),
"8.14": dict(
 covers=("Enough redundancy in processing facilities to meet availability requirements.",
         "Redundancia suficiente en las instalaciones de tratamiento para cumplir los requisitos de disponibilidad."),
 adds=("ops.4 expects a recovery capability for financial systems, tested periodically, when recovery is in scope; redundancy is one design that achieves it but is not tested as a control.",
       "ops.4 espera una capacidad de recuperacion de los sistemas financieros, probada periodicamente, cuando la recuperacion esta en alcance; la redundancia es un diseno que la logra pero no se prueba como control."),
 close=("Nothing further unless recovery is in scope; then evidence the recovery test.",
        "Nada mas salvo que la recuperacion este en alcance; entonces evidenciar la prueba de recuperacion.")),
"8.17": dict(
 covers=("All clocks synchronised to an approved time source.",
         "Todos los relojes sincronizados con una fuente de tiempo aprobada."),
 adds=("acc.8 relies on audit trails and logs whose timestamps can be trusted when the auditor traces a change or an access; clock synchronisation is assumed and rarely tested on its own.",
       "acc.8 se apoya en pistas de auditoria y registros cuyas marcas de tiempo sean fiables cuando el auditor rastrea un cambio o un acceso; la sincronizacion de relojes se da por supuesta y rara vez se prueba por si misma."),
 close=("Nothing further for SOX.",
        "Nada mas para SOX.")),
"8.26": dict(
 covers=("Security requirements specified and approved for developed or acquired applications.",
         "Requisitos de seguridad especificados y aprobados para las aplicaciones desarrolladas o adquiridas."),
 adds=("dev.1 expects the requirements of a new financial system to include the automated application controls (three-way match, tolerance checks, approval workflows), the key reports and the audit trails the financial process relies on, approved by the business owner; security requirements are a subset of what the auditor wants to see specified.",
       "dev.1 espera que los requisitos de un nuevo sistema financiero incluyan los controles automatizados de aplicacion (conciliacion a tres bandas, comprobaciones de tolerancia, flujos de aprobacion), los informes clave y las pistas de auditoria en que se apoya el proceso financiero, aprobados por el propietario de negocio; los requisitos de seguridad son un subconjunto de lo que el auditor quiere ver especificado."),
 close=("Add an 'automated controls and key reports' section to the requirements template for in-scope systems.",
        "Anadir una seccion de 'controles automatizados e informes clave' a la plantilla de requisitos de los sistemas en alcance.")),
"8.27": dict(
 covers=("Documented secure architecture and engineering principles applied to every design.",
         "Principios documentados de arquitectura e ingenieria segura aplicados a todo diseno."),
 adds=("dev.1 wants a methodology with phase approvals (requirements, design, build, test, deploy) evidenced for each in-scope project; architecture principles are not tested.",
       "dev.1 quiere una metodologia con aprobaciones por fase (requisitos, diseno, construccion, pruebas, despliegue) evidenciadas en cada proyecto en alcance; los principios de arquitectura no se prueban."),
 close=("Nothing further for SOX.",
        "Nada mas para SOX.")),
"8.28": dict(
 covers=("Secure coding rules, tooling and training applied to all code.",
         "Reglas de codificacion segura, herramientas y formacion aplicadas a todo el codigo."),
 adds=("dev.1 wants evidence that development followed the methodology and that the result was tested and approved; coding rules are not an ITGC.",
       "dev.1 quiere evidencia de que el desarrollo siguio la metodologia y de que el resultado se probo y aprobo; las reglas de codificacion no son un ITGC."),
 close=("Nothing further for SOX.",
        "Nada mas para SOX.")),
"8.30": dict(
 covers=("Outsourced development directed, monitored and reviewed.",
         "Desarrollo externalizado dirigido, supervisado y revisado."),
 adds=("dev.1 expects outsourced development of in-scope systems to follow the same methodology gates (approved requirements, UAT, go-live approval) with the entity's own approvals, and elc.5 a SOC 1 if the provider also operates the system; supervising the developer's security process is not the objective.",
       "dev.1 espera que el desarrollo externalizado de los sistemas en alcance siga los mismos hitos de la metodologia (requisitos aprobados, UAT, aprobacion de puesta en marcha) con las aprobaciones propias de la entidad, y elc.5 un SOC 1 si el proveedor ademas opera el sistema; supervisar el proceso de seguridad del desarrollador no es el objetivo."),
 close=("Keep the entity's own UAT sign-off and go-live approval for every outsourced delivery.",
        "Conservar la firma de UAT y la aprobacion de puesta en marcha propias de la entidad para cada entrega externalizada.")),
"8.33": dict(
 covers=("Test data selected, masked or anonymised, protected and deleted after use.",
         "Datos de prueba seleccionados, enmascarados o anonimizados, protegidos y borrados tras su uso."),
 adds=("chg.2 wants test evidence that is representative of the financial process (real scenarios, expected versus actual results), retained with the change record and accepted by the business; protecting or anonymising the test data is not the concern, though privacy rules may require it separately.",
       "chg.2 quiere evidencia de pruebas representativa del proceso financiero (escenarios reales, resultados esperados frente a obtenidos), conservada con el registro del cambio y aceptada por el negocio; proteger o anonimizar los datos de prueba no es la preocupacion, aunque las normas de privacidad puedan exigirlo por separado."),
 close=("Attach test results and business acceptance to every change on in-scope systems.",
        "Adjuntar los resultados de las pruebas y la aceptacion del negocio a cada cambio en los sistemas en alcance.")),
}
