D = {
"5.1": dict(
 covers=("An approved, published and reviewed security policy with the topic-specific policies under it — the documentary backbone of any ICT risk framework.",
         "Una politica de seguridad aprobada, publicada y revisada con las politicas especificas que dependen de ella: la columna documental de cualquier marco de riesgo TIC."),
 adds=("Art. 5 puts the whole ICT risk management framework under the management body, which must define, approve and oversee it, allocate budget, approve the third-party policy and keep its own ICT knowledge up to date through training. Art. 6 requires that framework to be documented, to include a digital operational resilience strategy, to be reviewed at least yearly and after major incidents, and to be audited internally. A security policy is one document inside that framework.",
       "El art. 5 pone todo el marco de gestion del riesgo TIC bajo el organo de direccion, que debe definirlo, aprobarlo y supervisarlo, asignar presupuesto, aprobar la politica de terceros y mantener sus propios conocimientos TIC mediante formacion. El art. 6 exige que ese marco este documentado, incluya una estrategia de resiliencia operativa digital, se revise al menos anualmente y tras incidentes graves, y se audite internamente. Una politica de seguridad es un documento dentro de ese marco."),
 close=("Build the framework document (strategy, policies, roles, review cycle) and have the board approve it and record its ICT training.",
        "Construir el documento del marco (estrategia, politicas, roles, ciclo de revision) y que el consejo lo apruebe y deje constancia de su formacion TIC.")),
"5.2": dict(
 covers=("Every security responsibility assigned to a named role and communicated.",
         "Cada responsabilidad de seguridad asignada a un rol concreto y comunicada."),
 adds=("Art. 5(2) makes the management body ultimately responsible and Art. 6(4) requires a control function for ICT risk that is independent from operations and from internal audit — the three-lines model — with the option of a simplified structure only for small entities. Assigning roles does not create an independent second line or place the accountability on the board.",
       "El art. 5.2 hace responsable ultimo al organo de direccion y el art. 6.4 exige una funcion de control del riesgo TIC independiente de las operaciones y de la auditoria interna — el modelo de tres lineas —, con opcion de una estructura simplificada solo para entidades pequenas. Asignar roles no crea una segunda linea independiente ni situa la responsabilidad en el consejo."),
 close=("Designate the ICT risk control function with a reporting line to the board and record the board's accountability in its rules.",
        "Designar la funcion de control del riesgo TIC con linea de reporte al consejo y recoger la responsabilidad del consejo en su reglamento.")),
"5.3": dict(
 covers=("Conflicting duties separated so that no one person can execute and conceal fraud or error.",
         "Funciones en conflicto separadas para que ninguna persona pueda ejecutar y ocultar por si sola un fraude o un error."),
 adds=("Art. 5 and RTS 2024/1774 Art. 2 require the segregation to follow the three lines of defence (ICT operations, ICT risk control, internal audit) with independence and appropriate seniority, and require ICT risk management roles to be separated from ICT operations. ISO's segregation is a general principle without a prescribed structure.",
       "El art. 5 y el art. 2 del RTS 2024/1774 exigen que la segregacion siga las tres lineas de defensa (operaciones TIC, control del riesgo TIC, auditoria interna) con independencia y rango adecuado, y que las funciones de gestion del riesgo TIC esten separadas de las operaciones TIC. La segregacion de ISO es un principio general sin estructura prescrita."),
 close=("Document the three lines with names, reporting lines and independence safeguards.",
        "Documentar las tres lineas con nombres, lineas de reporte y salvaguardas de independencia.")),
"5.5": dict(
 covers=("Authorities identified, contact persons named and the circumstances of contact defined.",
         "Autoridades identificadas, personas de contacto designadas y circunstancias del contacto definidas."),
 adds=("Art. 19 requires major ICT incidents to be reported to the competent authority through an initial notification (4 hours from classification, 24 from detection), an intermediate report (72 hours) and a final report (one month), using the templates of the ITS, plus voluntary notification of significant threats and information to clients. It is a reporting obligation with deadlines and formats, not a contact list.",
       "El art. 19 exige notificar los incidentes graves relacionados con las TIC a la autoridad competente mediante una notificacion inicial (4 horas desde la clasificacion, 24 desde la deteccion), un informe intermedio (72 horas) y un informe final (un mes), con las plantillas de la NTE, mas la notificacion voluntaria de ciberamenazas importantes y la informacion a los clientes. Es una obligacion de notificacion con plazos y formatos, no una lista de contactos."),
 close=("Add the major-incident classification (RTS 2024/1772) and the 4h/72h/1-month reporting steps to the incident procedure.",
        "Anadir al procedimiento de incidentes la clasificacion de incidente grave (RTS 2024/1772) y los pasos de notificacion a 4 h/72 h/1 mes.")),
"5.7": dict(
 covers=("A threat intelligence process that collects, analyses and turns threat information into control decisions.",
         "Un proceso de inteligencia de amenazas que recoge, analiza y convierte la informacion sobre amenazas en decisiones sobre controles."),
 adds=("Art. 13 requires the entity to learn from incidents (post-incident reviews of major incidents, root cause, lessons reported to the management body), to monitor the effectiveness of its strategy and to run awareness and training including for the board; Art. 45 allows exchanging threat intelligence with other entities under arrangements notified to the authority. ISO's threat intelligence is an input; DORA wants a learning loop and, optionally, sharing.",
       "El art. 13 exige a la entidad aprender de los incidentes (revisiones posteriores de los incidentes graves, causa raiz, lecciones reportadas al organo de direccion), supervisar la eficacia de su estrategia y realizar concienciacion y formacion incluida la del consejo; el art. 45 permite intercambiar inteligencia de amenazas con otras entidades mediante acuerdos notificados a la autoridad. La inteligencia de amenazas de ISO es una entrada; DORA quiere un bucle de aprendizaje y, opcionalmente, intercambio."),
 close=("Institute post-incident reviews reported to the board and, if joining a sharing arrangement, notify the authority.",
        "Instaurar revisiones posteriores a incidentes reportadas al consejo y, si se participa en un acuerdo de intercambio, notificarlo a la autoridad.")),
"5.8": dict(
 covers=("Security integrated into projects from initiation to closure, with risk assessment at each phase.",
         "Seguridad integrada en los proyectos de principio a fin, con evaluacion de riesgos en cada fase."),
 adds=("Art. 8 requires identifying and classifying all ICT-supported business functions, assets and dependencies, keeping an inventory, identifying sources of ICT risk and performing a risk assessment before every major change to infrastructure, processes or procedures; Art. 6 wants all that inside the framework. Projects are one moment where DORA expects the assessment, but the identification duty is continuous.",
       "El art. 8 exige identificar y clasificar todas las funciones de negocio, activos y dependencias soportados por TIC, mantener un inventario, identificar las fuentes de riesgo TIC y realizar una evaluacion de riesgos antes de cada cambio importante de infraestructura, procesos o procedimientos; el art. 6 quiere todo eso dentro del marco. Los proyectos son un momento en que DORA espera la evaluacion, pero el deber de identificacion es continuo."),
 close=("Keep the inventory of ICT-supported functions and dependencies up to date and record a risk assessment for every major change, project or not.",
        "Mantener actualizado el inventario de funciones y dependencias soportadas por TIC y registrar una evaluacion de riesgos en cada cambio importante, sea o no un proyecto.")),
"5.10": dict(
 covers=("Rules for the acceptable use of information and assets, communicated and acknowledged.",
         "Reglas de uso aceptable de la informacion y los activos, comunicadas y reconocidas."),
 adds=("Art. 9 requires policies and procedures that protect ICT systems, ensure data security across its lifecycle and prevent unauthorised access; acceptable use is one of those policies. RTS 2024/1774 asks for an information security policy with a defined set of contents (Art. 3) that goes well beyond user rules.",
       "El art. 9 exige politicas y procedimientos que protejan los sistemas TIC, aseguren los datos durante todo su ciclo de vida y eviten el acceso no autorizado; el uso aceptable es una de esas politicas. El RTS 2024/1774 pide una politica de seguridad de la informacion con un contenido definido (art. 3) que va mucho mas alla de las reglas de usuario."),
 close=("Fold the acceptable-use rules into the information security policy structured per RTS 2024/1774 Art. 3.",
        "Integrar las reglas de uso aceptable en la politica de seguridad de la informacion estructurada segun el art. 3 del RTS 2024/1774.")),
"5.11": dict(
 covers=("Equipment, information and access recovered from personnel and third parties when the relationship ends.",
         "Equipos, informacion y accesos recuperados del personal y los terceros cuando termina la relacion."),
 adds=("Art. 9 protects ICT assets and requires access to be managed; the return of assets on departure is not addressed specifically. RTS 2024/1774 Art. 21 (access control) implies revocation on termination but not the physical return.",
       "El art. 9 protege los activos TIC y exige gestionar los accesos; la devolucion de activos al marcharse no se trata de forma especifica. El art. 21 del RTS 2024/1774 (control de acceso) implica la revocacion al cesar pero no la devolucion fisica."),
 close=("Link the leaver checklist to the access revocation evidence required under the RTS.",
        "Enlazar la lista de comprobacion de bajas con la evidencia de revocacion de accesos exigida por el RTS.")),
"5.12": dict(
 covers=("Information classified by its confidentiality, integrity and availability needs, with handling rules per level.",
         "Informacion clasificada segun sus necesidades de confidencialidad, integridad y disponibilidad, con reglas de manejo por nivel."),
 adds=("Art. 8 requires identifying, classifying and documenting all ICT-supported business functions, roles, information assets and ICT assets, their configurations and interdependencies, and rating their criticality; RTS 2024/1774 Art. 4 adds a classification of information and ICT assets by criticality of the functions they support. DORA classifies functions and assets by business criticality; ISO classifies information by protection need. Both are needed.",
       "El art. 8 exige identificar, clasificar y documentar todas las funciones de negocio, roles, activos de informacion y activos TIC soportados por TIC, sus configuraciones e interdependencias, y valorar su criticidad; el art. 4 del RTS 2024/1774 anade una clasificacion de la informacion y los activos TIC por la criticidad de las funciones que soportan. DORA clasifica funciones y activos por criticidad de negocio; ISO clasifica la informacion por necesidad de proteccion. Hacen falta ambas."),
 close=("Add a criticality rating (critical or important function: yes/no) to the asset inventory alongside the CIA classification.",
        "Anadir al inventario de activos una valoracion de criticidad (funcion esencial o importante: si/no) junto a la clasificacion CID.")),
"5.13": dict(
 covers=("Classification made visible through labels on documents, media and systems.",
         "Clasificacion visible mediante etiquetas en documentos, soportes y sistemas."),
 adds=("Art. 8 wants assets identified, classified and documented in an inventory; labelling is not required. The ISO control exceeds DORA.",
       "El art. 8 quiere activos identificados, clasificados y documentados en un inventario; el etiquetado no se exige. El control ISO supera a DORA."),
 close=("Nothing more for DORA beyond keeping the Art. 8 inventory.",
        "Nada mas para DORA mas alla de mantener el inventario del art. 8.")),
"5.14": dict(
 covers=("Rules and agreements for transferring information through any channel, with encryption and non-repudiation where needed.",
         "Reglas y acuerdos para transferir informacion por cualquier canal, con cifrado y no repudio cuando haga falta."),
 adds=("Art. 9 requires securing the means of transfer of data and preventing leakage, and Art. 14 requires crisis communication plans: responsible disclosure of major incidents to clients and counterparts, internal communication, a spokesperson and media policy. ISO's transfer policy is broader in channels; DORA adds the obligation to communicate outward during an incident.",
       "El art. 9 exige proteger los medios de transferencia de datos y prevenir fugas, y el art. 14 exige planes de comunicacion de crisis: divulgacion responsable de los incidentes graves a clientes y contrapartes, comunicacion interna, un portavoz y una politica de medios. La politica de transferencia de ISO es mas amplia en canales; DORA anade la obligacion de comunicar hacia fuera durante un incidente."),
 close=("Write the crisis communication plan of Art. 14 with a designated spokesperson and client-notification templates.",
        "Redactar el plan de comunicacion de crisis del art. 14 con un portavoz designado y plantillas de notificacion a clientes.")),
"5.19": dict(
 covers=("A supplier security process: risk-based selection, requirements, monitoring and termination.",
         "Un proceso de seguridad de proveedores: seleccion basada en riesgo, requisitos, seguimiento y terminacion."),
 adds=("Art. 28 requires a strategy on ICT third-party risk with a policy on services supporting critical or important functions (RTS 2024/1773), a register of information on all contractual arrangements reported yearly to the authority in the ITS 2024/2956 templates, pre-contract due diligence and risk assessment, exit strategies, and notification to the authority before contracting for critical functions. The supplier process ISO describes is the starting point of a far heavier regime.",
       "El art. 28 exige una estrategia de riesgo de terceros TIC con una politica sobre los servicios que soportan funciones esenciales o importantes (RTS 2024/1773), un registro de informacion de todos los acuerdos contractuales reportado anualmente a la autoridad con las plantillas de la NTE 2024/2956, diligencia debida y evaluacion de riesgos precontractuales, estrategias de salida y notificacion a la autoridad antes de contratar para funciones esenciales. El proceso de proveedores que describe ISO es el punto de partida de un regimen mucho mas pesado."),
 close=("Build the register of information in the ITS format and adopt the critical-function policy per RTS 2024/1773.",
        "Construir el registro de informacion en el formato de la NTE y adoptar la politica de funciones esenciales segun el RTS 2024/1773.")),
"5.20": dict(
 covers=("Security requirements written into supplier agreements: incident reporting, audit rights, subcontracting, termination.",
         "Requisitos de seguridad recogidos en los acuerdos con proveedores: notificacion de incidentes, derechos de auditoria, subcontratacion, terminacion."),
 adds=("Art. 30 fixes the mandatory content of contracts for ICT services: full service description, data locations and processing, availability and integrity provisions, access and recovery of data on termination, service levels, incident assistance, cooperation with authorities, termination rights and — for critical functions — audit and inspection rights, exit strategies and participation in TLPT. ISO leaves the content to the organisation; DORA lists it.",
       "El art. 30 fija el contenido obligatorio de los contratos de servicios TIC: descripcion completa del servicio, ubicaciones y tratamiento de datos, disposiciones de disponibilidad e integridad, acceso y recuperacion de datos al terminar, niveles de servicio, asistencia en incidentes, cooperacion con las autoridades, derechos de terminacion y — para funciones esenciales — derechos de auditoria e inspeccion, estrategias de salida y participacion en TLPT. ISO deja el contenido a la organizacion; DORA lo enumera."),
 close=("Run a contract gap analysis against Art. 30 for every ICT provider and remediate through addenda.",
        "Hacer un analisis de brechas contractuales contra el art. 30 para cada proveedor TIC y remediarlas mediante adendas.")),
"5.21": dict(
 covers=("Supply-chain risks addressed: provenance, components, subcontractors, assurance from the supplier about its own suppliers.",
         "Riesgos de la cadena de suministro tratados: procedencia, componentes, subcontratistas, garantias del proveedor sobre sus propios proveedores."),
 adds=("Art. 28 and RTS 2025/532 regulate subcontracting of services supporting critical or important functions: the entity must assess the whole subcontracting chain before contracting, define conditions under which subcontracting is allowed, keep the right to be informed of and object to material changes, and monitor the chain. ISO's supply-chain control has no such reach into the subcontractors of the provider.",
       "El art. 28 y el RTS 2025/532 regulan la subcontratacion de servicios que soportan funciones esenciales o importantes: la entidad debe evaluar toda la cadena de subcontratacion antes de contratar, definir las condiciones en que se permite subcontratar, conservar el derecho a ser informada y a oponerse a cambios materiales, y supervisar la cadena. El control de cadena de suministro de ISO no alcanza asi a los subcontratistas del proveedor."),
 close=("Add subcontracting conditions and a right of objection to critical-function contracts and record the chain in the register.",
        "Anadir condiciones de subcontratacion y un derecho de oposicion a los contratos de funciones esenciales y registrar la cadena en el registro de informacion.")),
"5.22": dict(
 covers=("Supplier services monitored and reviewed, with changes assessed for their security impact.",
         "Servicios de proveedores supervisados y revisados, con los cambios evaluados por su impacto en la seguridad."),
 adds=("Art. 28 requires ongoing monitoring plus an annual report to the management body, and Art. 29 a preliminary assessment of ICT concentration risk: dependency on a provider that is not easily substitutable, multiple contracts with the same provider or group, and the risks of subcontracting to third countries. Monitoring delivery does not answer the concentration question.",
       "El art. 28 exige seguimiento continuo mas un informe anual al organo de direccion, y el art. 29 una evaluacion preliminar del riesgo de concentracion de TIC: dependencia de un proveedor dificilmente sustituible, multiples contratos con el mismo proveedor o grupo, y los riesgos de subcontratar en terceros paises. Supervisar la prestacion no responde a la pregunta de la concentracion."),
 close=("Perform and document the concentration assessment of Art. 29 for every critical-function provider.",
        "Realizar y documentar la evaluacion de concentracion del art. 29 para cada proveedor de funciones esenciales.")),
"5.23": dict(
 covers=("A cloud policy on the customer side: risk assessment, shared responsibilities, data location, exit plan.",
         "Una politica de nube del lado del cliente: evaluacion de riesgos, responsabilidades compartidas, ubicacion de datos, plan de salida."),
 adds=("Art. 28 and Art. 30 apply to cloud as to any ICT third-party service — register of information, due diligence, mandatory clauses, exit strategy — and Chapter V Section II subjects critical ICT third-party providers to direct EU oversight (lead overseer, inspections, recommendations). The customer's cloud policy is necessary but is only one part of DORA's regime for that provider.",
       "Los arts. 28 y 30 se aplican a la nube como a cualquier servicio TIC de terceros — registro de informacion, diligencia debida, clausulas obligatorias, estrategia de salida — y la seccion II del capitulo V somete a los proveedores terceros esenciales de servicios TIC a supervision directa de la UE (supervisor principal, inspecciones, recomendaciones). La politica de nube del cliente es necesaria pero es solo una parte del regimen de DORA para ese proveedor."),
 close=("Treat each cloud contract under Art. 30, document the exit strategy and check whether the provider is designated as critical.",
        "Tratar cada contrato de nube bajo el art. 30, documentar la estrategia de salida y comprobar si el proveedor esta designado como esencial.")),
"5.28": dict(
 covers=("Evidence identified, collected and preserved with chain of custody so that it is admissible.",
         "Evidencias identificadas, recogidas y preservadas con cadena de custodia para que sean admisibles."),
 adds=("Art. 12 requires logs and backup policies that allow restoration, and Art. 17 an incident management process that records all incidents, identifies root causes and keeps the evidence needed for the reports of Art. 19; RTS 2024/1774 Art. 12 asks for logging with integrity protection. The forensic handling procedure itself is not spelled out.",
       "El art. 12 exige politicas de registro y copias que permitan la restauracion, y el art. 17 un proceso de gestion de incidentes que registre todos los incidentes, identifique las causas raiz y conserve las evidencias necesarias para los informes del art. 19; el art. 12 del RTS 2024/1774 pide registro con proteccion de integridad. El procedimiento de manejo forense en si no se detalla."),
 close=("Reference the forensic procedure from the Art. 17 incident process and make the root-cause record part of the final report.",
        "Referenciar el procedimiento forense desde el proceso de incidentes del art. 17 y hacer del registro de causa raiz parte del informe final.")),
"5.31": dict(
 covers=("Legal, regulatory and contractual requirements identified, documented and assigned.",
         "Requisitos legales, reglamentarios y contractuales identificados, documentados y asignados."),
 adds=("Art. 5 and Art. 6 make the management body accountable for the framework and for compliance with it; DORA is a directly applicable regulation supervised by the sectoral authority (CNMV, Banco de Espana, DGSFP), with reporting duties, testing duties and a sanctioning regime. Identifying DORA as applicable is the first line of the inventory, not compliance.",
       "Los arts. 5 y 6 hacen responsable al organo de direccion del marco y de su cumplimiento; DORA es un reglamento directamente aplicable supervisado por la autoridad sectorial (CNMV, Banco de Espana, DGSFP), con deberes de informacion, de pruebas y un regimen sancionador. Identificar DORA como aplicable es la primera linea del inventario, no el cumplimiento."),
 close=("Map every DORA article to an owner and a piece of evidence and report the status to the board at least yearly.",
        "Asociar cada articulo de DORA a un responsable y una evidencia y reportar el estado al consejo al menos anualmente.")),
"5.33": dict(
 covers=("Records protected for their retention period against loss, tampering and unauthorised access.",
         "Registros protegidos durante su periodo de conservacion frente a perdida, manipulacion y acceso no autorizado."),
 adds=("Art. 12 concerns backup and restoration policies and procedures, tested and with segregated backup systems; DORA has no general records-protection duty. Retention of financial and contractual records comes from sectoral law (MiFID, AML, company law), not from DORA.",
       "El art. 12 se refiere a politicas y procedimientos de copias y restauracion, probados y con sistemas de copia segregados; DORA no tiene un deber general de proteccion de registros. La conservacion de registros financieros y contractuales viene de la normativa sectorial (MiFID, PBC, ley de sociedades), no de DORA."),
 close=("Evidence the tested backup and segregated backup systems Art. 12 requires; the rest of records management is outside DORA.",
        "Evidenciar las copias probadas y los sistemas de copia segregados que exige el art. 12; el resto de la gestion de registros queda fuera de DORA.")),
"5.35": dict(
 covers=("Independent review of the security approach at planned intervals and after significant change, reported to management.",
         "Revision independiente del enfoque de seguridad a intervalos planificados y tras cambios significativos, reportada a la direccion."),
 adds=("Art. 6(6) requires the framework to be audited periodically by internal auditors with sufficient ICT knowledge, with a formal follow-up process for findings; Art. 24 requires a digital operational resilience testing programme, reviewed at least yearly, covering all critical systems with the tests of Art. 25 and, for designated entities, TLPT every three years. ISO sets neither the auditor's profile nor the frequency nor a testing programme.",
       "El art. 6.6 exige auditar el marco periodicamente por auditores internos con conocimientos TIC suficientes, con un proceso formal de seguimiento de los hallazgos; el art. 24 exige un programa de pruebas de resiliencia operativa digital, revisado al menos anualmente, que cubra todos los sistemas esenciales con las pruebas del art. 25 y, para las entidades designadas, TLPT cada tres anos. ISO no fija ni el perfil del auditor ni la frecuencia ni un programa de pruebas."),
 close=("Add the framework to the internal audit plan and write the yearly testing programme with the Art. 25 test types.",
        "Incluir el marco en el plan de auditoria interna y redactar el programa anual de pruebas con los tipos de prueba del art. 25.")),
"5.36": dict(
 covers=("Managers periodically check compliance with policies and standards and correct deviations.",
         "Los responsables comprueban periodicamente el cumplimiento de politicas y normas y corrigen las desviaciones."),
 adds=("Art. 6(6) requires a formal follow-up process for internal audit findings, including verification of remediation and rules for timely correction of critical findings; Art. 6(5) requires the framework to be reviewed yearly and after major incidents, with a report to the authority on request. Management review is informal by comparison.",
       "El art. 6.6 exige un proceso formal de seguimiento de los hallazgos de auditoria interna, incluida la verificacion de la remediacion y reglas para corregir a tiempo los hallazgos criticos; el art. 6.5 exige revisar el marco anualmente y tras incidentes graves, con informe a la autoridad a peticion. La revision de la direccion es informal en comparacion."),
 close=("Keep a findings register with owners and deadlines and a yearly framework review minute.",
        "Llevar un registro de hallazgos con responsables y plazos y un acta de revision anual del marco.")),
"5.37": dict(
 covers=("Operating procedures documented and available to those who run the systems.",
         "Procedimientos operativos documentados y disponibles para quienes operan los sistemas."),
 adds=("Art. 6 requires the entire ICT risk management framework — strategies, policies, procedures, protocols and tools — to be documented and reviewed; RTS 2024/1774 lists the policies and procedures it must contain (security, asset, encryption, operations, capacity, vulnerability, logging, access, incident, continuity). Operating procedures are a subset of that documentation.",
       "El art. 6 exige documentar y revisar todo el marco de gestion del riesgo TIC — estrategias, politicas, procedimientos, protocolos y herramientas —; el RTS 2024/1774 enumera las politicas y procedimientos que debe contener (seguridad, activos, cifrado, operaciones, capacidad, vulnerabilidades, registro, acceso, incidentes, continuidad). Los procedimientos operativos son un subconjunto de esa documentacion."),
 close=("Check the procedure set against the RTS 2024/1774 list and fill the gaps (capacity, vulnerability, logging policies are the usual ones).",
        "Contrastar el conjunto de procedimientos con la lista del RTS 2024/1774 y cubrir los huecos (capacidad, vulnerabilidades y registro suelen ser los habituales).")),
"6.1": dict(
 covers=("Background checks on candidates proportionate to the role.",
         "Verificacion de antecedentes de los candidatos proporcional al puesto."),
 adds=("Art. 5(4) requires the management body to keep sufficient knowledge and skills to understand ICT risk, through regular training; RTS 2024/1774 Art. 19 requires HR policies on ICT security responsibilities. Screening of personnel is not a DORA requirement.",
       "El art. 5.4 exige que el organo de direccion mantenga conocimientos y competencias suficientes para entender el riesgo TIC, mediante formacion regular; el art. 19 del RTS 2024/1774 exige politicas de RR. HH. sobre responsabilidades de seguridad TIC. La investigacion de antecedentes no es un requisito DORA."),
 close=("Record the board's ICT training; screening is an ISO extra.",
        "Registrar la formacion TIC del consejo; la investigacion de antecedentes es un extra de ISO.")),
"6.2": dict(
 covers=("Security responsibilities stated in employment contracts.",
         "Responsabilidades de seguridad recogidas en los contratos de trabajo."),
 adds=("Art. 5 assigns responsibilities to the management body; RTS 2024/1774 Art. 19 requires the HR policy to state ICT security responsibilities of staff and their obligations on termination. The contractual terms of ordinary employees are not regulated by DORA beyond that.",
       "El art. 5 asigna responsabilidades al organo de direccion; el art. 19 del RTS 2024/1774 exige que la politica de RR. HH. recoja las responsabilidades de seguridad TIC del personal y sus obligaciones al cesar. Los terminos contractuales de los empleados ordinarios no los regula DORA mas alla de eso."),
 close=("Cite the employment clauses as the HR-policy evidence the RTS requires.",
        "Citar las clausulas laborales como evidencia de la politica de RR. HH. que exige el RTS.")),
"6.6": dict(
 covers=("Confidentiality agreements signed by personnel and third parties, with defined content.",
         "Acuerdos de confidencialidad firmados por el personal y los terceros, con contenido definido."),
 adds=("Art. 30 requires contracts with ICT providers to include provisions on confidentiality, integrity, availability of data and data protection; agreements with employees are not addressed.",
       "El art. 30 exige que los contratos con proveedores TIC incluyan disposiciones de confidencialidad, integridad y disponibilidad de los datos y de proteccion de datos; los acuerdos con los empleados no se tratan."),
 close=("Verify that every ICT provider contract carries the Art. 30 confidentiality provisions.",
        "Verificar que todo contrato con proveedores TIC lleva las disposiciones de confidencialidad del art. 30.")),
"6.7": dict(
 covers=("A remote-working policy covering environment, device, connection, rules and support.",
         "Una politica de trabajo a distancia que cubre entorno, dispositivo, conexion, reglas y soporte."),
 adds=("Art. 9 requires strong authentication and secure connection for remote access to ICT systems; RTS 2024/1774 Art. 21 asks for access rights and remote access managed and logged. DORA protects the access path, not the working arrangement.",
       "El art. 9 exige autenticacion robusta y conexion segura para el acceso remoto a los sistemas TIC; el art. 21 del RTS 2024/1774 pide gestionar y registrar los derechos de acceso y el acceso remoto. DORA protege la via de acceso, no el regimen de trabajo."),
 close=("Evidence MFA and logging on remote access; the organisational side is ISO only.",
        "Evidenciar MFA y registro en el acceso remoto; la parte organizativa es solo ISO.")),
"6.8": dict(
 covers=("A channel for anyone to report security events quickly.",
         "Un canal para que cualquiera notifique con rapidez los eventos de seguridad."),
 adds=("Art. 17 requires an incident management process with early warning indicators, procedures to identify, track, log, categorise and classify incidents, escalation to senior staff and the management body, and the reporting of Art. 19. Staff reporting is an assumed input; DORA does not regulate the internal channel.",
       "El art. 17 exige un proceso de gestion de incidentes con indicadores de alerta temprana, procedimientos para identificar, seguir, registrar, categorizar y clasificar los incidentes, escalado a la alta direccion y al organo de direccion, y la notificacion del art. 19. La notificacion por el personal es una entrada supuesta; DORA no regula el canal interno."),
 close=("Document the channel as an early warning indicator in the Art. 17 process.",
        "Documentar el canal como indicador de alerta temprana en el proceso del art. 17.")),
"7.1": dict(
 covers=("Defined physical perimeters around areas holding information and assets.",
         "Perimetros fisicos definidos alrededor de las areas que albergan informacion y activos."),
 adds=("Art. 9(2) and RTS 2024/1774 Art. 18 require physical and environmental security measures for ICT assets proportionate to their criticality; perimeters as a named control are not required, only the outcome.",
       "El art. 9.2 y el art. 18 del RTS 2024/1774 exigen medidas de seguridad fisica y ambiental para los activos TIC proporcionales a su criticidad; los perimetros como control nombrado no se exigen, solo el resultado."),
 close=("Cite the perimeters as the physical security measure of RTS Art. 18 for the critical ICT assets.",
        "Citar los perimetros como la medida de seguridad fisica del art. 18 del RTS para los activos TIC esenciales.")),
"7.2": dict(
 covers=("Entry controls so that only authorised people enter secure areas, with logs.",
         "Controles de entrada para que solo personas autorizadas accedan a las areas seguras, con registros."),
 adds=("Art. 9 mentions physical access control among protection measures and RTS Art. 18 asks for it to be based on the criticality of the premises; there is no detail on the mechanism or logging.",
       "El art. 9 menciona el control de acceso fisico entre las medidas de proteccion y el art. 18 del RTS pide que se base en la criticidad de las instalaciones; no hay detalle sobre el mecanismo ni el registro."),
 close=("Evidence access logs for the data centre and critical rooms.",
        "Evidenciar los registros de acceso al centro de datos y a las salas esenciales.")),
"7.3": dict(
 covers=("Offices, rooms and facilities physically secured.",
         "Oficinas, salas e instalaciones protegidas fisicamente."),
 adds=("Art. 9 and RTS Art. 18 address physical protection generically, proportionate to criticality; securing ordinary offices is not itemised.",
       "El art. 9 y el art. 18 del RTS tratan la proteccion fisica de forma generica, proporcional a la criticidad; la seguridad de las oficinas ordinarias no se detalla."),
 close=("Nothing further for DORA beyond the critical premises.",
        "Nada mas para DORA mas alla de las instalaciones esenciales.")),
"7.4": dict(
 covers=("Continuous physical monitoring of premises with alerts and review.",
         "Vigilancia fisica continua de las instalaciones con alertas y revision."),
 adds=("Art. 10 requires mechanisms to promptly detect anomalous activities in ICT systems and networks, with alert thresholds and multi-layered control; it is about ICT detection, not physical surveillance. Physical monitoring falls, if anywhere, under RTS Art. 18.",
       "El art. 10 exige mecanismos para detectar con rapidez actividades anomalas en los sistemas y redes TIC, con umbrales de alerta y control multicapa; trata de deteccion TIC, no de vigilancia fisica. La vigilancia fisica cae, si acaso, bajo el art. 18 del RTS."),
 close=("Evidence the ICT detection mechanisms of Art. 10 separately; physical monitoring is an ISO extra.",
        "Evidenciar por separado los mecanismos de deteccion TIC del art. 10; la vigilancia fisica es un extra de ISO.")),
"7.5": dict(
 covers=("Protection designed against fire, flood, earthquake, unrest and other physical or environmental threats.",
         "Proteccion disenada frente a incendio, inundacion, terremoto, disturbios y otras amenazas fisicas o ambientales."),
 adds=("Art. 9 asks for ICT systems to be resilient against physical and environmental events and RTS Art. 18 for environmental measures proportionate to criticality; the design of specific protections is left to the entity.",
       "El art. 9 pide que los sistemas TIC sean resilientes frente a eventos fisicos y ambientales y el art. 18 del RTS medidas ambientales proporcionales a la criticidad; el diseno de las protecciones concretas se deja a la entidad."),
 close=("Document the environmental protections of critical sites as RTS Art. 18 evidence.",
        "Documentar las protecciones ambientales de las sedes esenciales como evidencia del art. 18 del RTS.")),
"7.8": dict(
 covers=("Equipment sited to reduce environmental risk and unauthorised access.",
         "Equipos ubicados para reducir el riesgo ambiental y el acceso no autorizado."),
 adds=("Art. 9 covers physical protection generically; siting is not addressed.",
       "El art. 9 cubre la proteccion fisica de forma generica; la ubicacion no se trata."),
 close=("Nothing further for DORA.",
        "Nada mas para DORA.")),
"7.9": dict(
 covers=("Assets used off-site protected: authorisation, encryption, custody.",
         "Activos usados fuera de las instalaciones protegidos: autorizacion, cifrado, custodia."),
 adds=("Art. 9 protects ICT assets generally; off-site use is not addressed separately, though encryption of data at rest on mobile devices falls under RTS Art. 6 (encryption).",
       "El art. 9 protege los activos TIC en general; el uso fuera de las instalaciones no se trata por separado, aunque el cifrado de datos en reposo en dispositivos moviles cae bajo el art. 6 del RTS (cifrado)."),
 close=("Evidence encryption of mobile devices under the RTS encryption policy.",
        "Evidenciar el cifrado de los dispositivos moviles bajo la politica de cifrado del RTS.")),
"7.10": dict(
 covers=("Storage media managed across their lifecycle according to classification.",
         "Soportes de almacenamiento gestionados durante todo su ciclo de vida segun la clasificacion."),
 adds=("Art. 9 protects data at rest, in use and in transit and RTS Art. 6 requires encryption of data at rest according to classification; the lifecycle of media as such is not addressed.",
       "El art. 9 protege los datos en reposo, en uso y en transito y el art. 6 del RTS exige cifrar los datos en reposo segun su clasificacion; el ciclo de vida de los soportes como tal no se trata."),
 close=("Evidence encryption of media holding critical data; the rest is ISO only.",
        "Evidenciar el cifrado de los soportes con datos esenciales; el resto es solo ISO.")),
"7.11": dict(
 covers=("Protection against failure of power, cooling, telecoms and other supporting utilities.",
         "Proteccion frente a fallos de energia, refrigeracion, telecomunicaciones y otros suministros."),
 adds=("Art. 9 and Art. 12 require ICT systems to be resilient and recoverable; supporting utilities are not itemised, they are implied by the availability requirements and the continuity plans.",
       "Los arts. 9 y 12 exigen que los sistemas TIC sean resilientes y recuperables; los suministros no se detallan, se implican en los requisitos de disponibilidad y en los planes de continuidad."),
 close=("Reference the utilities protection from the ICT continuity plan of Art. 11.",
        "Referenciar la proteccion de suministros desde el plan de continuidad TIC del art. 11.")),
"7.13": dict(
 covers=("Equipment maintained by authorised personnel with records and data protected during repair.",
         "Equipos mantenidos por personal autorizado con registros y datos protegidos durante las reparaciones."),
 adds=("Art. 9 requires ICT systems to be kept updated and patched (RTS Art. 10, vulnerability and patch management); physical maintenance of hardware is not covered.",
       "El art. 9 exige mantener los sistemas TIC actualizados y parcheados (art. 10 del RTS, gestion de vulnerabilidades y parches); el mantenimiento fisico del hardware no se cubre."),
 close=("Nothing further for DORA on the hardware side.",
        "Nada mas para DORA en la parte de hardware.")),
"7.14": dict(
 covers=("Equipment verified and data erased or media destroyed before disposal or re-use.",
         "Equipos verificados y datos borrados o soportes destruidos antes de eliminarlos o reutilizarlos."),
 adds=("Art. 9 protects data across its lifecycle and RTS Art. 11 (ICT operations) mentions secure disposal of ICT assets and the data on them; the verification of erasure is not detailed.",
       "El art. 9 protege los datos durante todo su ciclo de vida y el art. 11 del RTS (operaciones TIC) menciona la eliminacion segura de los activos TIC y de sus datos; la verificacion del borrado no se detalla."),
 close=("Keep the disposal certificates as RTS Art. 11 evidence.",
        "Conservar los certificados de destruccion como evidencia del art. 11 del RTS.")),
"8.1": dict(
 covers=("An endpoint policy: hardening, encryption, patching, malware protection, remote wipe, BYOD, user responsibilities.",
         "Una politica de dispositivos de usuario: bastionado, cifrado, parcheo, proteccion antimalware, borrado remoto, BYOD, responsabilidades del usuario."),
 adds=("Art. 9 protects ICT assets in general and RTS 2024/1774 spreads endpoint expectations across several articles (encryption Art. 6, network security Art. 13, ICT operations Art. 11); there is no endpoint policy requirement as such.",
       "El art. 9 protege los activos TIC en general y el RTS 2024/1774 reparte las expectativas sobre dispositivos entre varios articulos (cifrado art. 6, seguridad de red art. 13, operaciones TIC art. 11); no hay un requisito de politica de dispositivos como tal."),
 close=("Map the endpoint policy sections to the RTS articles they satisfy.",
        "Asociar las secciones de la politica de dispositivos a los articulos del RTS que satisfacen.")),
"8.4": dict(
 covers=("Access to source code and development tools restricted and logged.",
         "Acceso al codigo fuente y a las herramientas de desarrollo restringido y registrado."),
 adds=("Art. 9 requires access control to ICT systems and RTS Art. 21 access rights management; source code is not singled out, and RTS Art. 16 (acquisition, development, maintenance) covers the development process rather than repository access.",
       "El art. 9 exige control de acceso a los sistemas TIC y el art. 21 del RTS gestion de derechos de acceso; el codigo fuente no se singulariza, y el art. 16 del RTS (adquisicion, desarrollo, mantenimiento) cubre el proceso de desarrollo mas que el acceso al repositorio."),
 close=("Include the repositories in the access reviews of RTS Art. 21.",
        "Incluir los repositorios en las revisiones de acceso del art. 21 del RTS.")),
"8.6": dict(
 covers=("Capacity monitored and planned against demand.",
         "Capacidad supervisada y planificada frente a la demanda."),
 adds=("Art. 7 requires ICT systems that are reliable, with sufficient capacity, technologically resilient and able to handle peak demand; RTS Art. 9 requires a capacity and performance management procedure with monitoring and forecasting. It is a specific, documented procedure DORA wants, not just monitoring.",
       "El art. 7 exige sistemas TIC fiables, con capacidad suficiente, tecnologicamente resilientes y capaces de gestionar picos de demanda; el art. 9 del RTS exige un procedimiento de gestion de capacidad y rendimiento con monitorizacion y prevision. DORA quiere un procedimiento concreto y documentado, no solo monitorizacion."),
 close=("Write the capacity and performance management procedure with thresholds and forecasting per RTS Art. 9.",
        "Redactar el procedimiento de gestion de capacidad y rendimiento con umbrales y previsiones segun el art. 9 del RTS.")),
"8.10": dict(
 covers=("Information deleted when no longer needed, by approved methods, with records.",
         "Informacion borrada cuando ya no se necesita, por metodos aprobados, con registro."),
 adds=("Art. 9 protects data across its lifecycle; deletion at end of retention is not required as a control, only implied by data-protection law and by RTS Art. 11's secure disposal.",
       "El art. 9 protege los datos durante todo su ciclo de vida; el borrado al fin de la retencion no se exige como control, solo se implica en la normativa de proteccion de datos y en la eliminacion segura del art. 11 del RTS."),
 close=("Nothing further for DORA.",
        "Nada mas para DORA.")),
"8.12": dict(
 covers=("Data-leakage prevention across endpoints, e-mail, web and cloud.",
         "Prevencion de fugas de datos en puestos, correo, web y nube."),
 adds=("Art. 9(3)(c) requires policies that limit physical or logical access and prevent data leakage; RTS Art. 13 (network security) and Art. 6 (encryption) are the vehicles. DLP as a technology is not named, but leakage prevention as an outcome is.",
       "El art. 9.3.c exige politicas que limiten el acceso fisico o logico y eviten la fuga de datos; el art. 13 del RTS (seguridad de red) y el art. 6 (cifrado) son los vehiculos. DLP como tecnologia no se nombra, pero la prevencion de fugas como resultado si."),
 close=("Cite the DLP controls as the Art. 9(3)(c) leakage prevention measure.",
        "Citar los controles DLP como la medida de prevencion de fugas del art. 9.3.c.")),
"8.17": dict(
 covers=("All clocks synchronised to an approved time source.",
         "Todos los relojes sincronizados con una fuente de tiempo aprobada."),
 adds=("Art. 10 requires detection mechanisms and multi-layered control with alert thresholds; RTS Art. 12 requires logs to be time-stamped with synchronised clocks. It is in the RTS, not the regulation, that the requirement appears.",
       "El art. 10 exige mecanismos de deteccion y control multicapa con umbrales de alerta; el art. 12 del RTS exige que los registros lleven marcas de tiempo con relojes sincronizados. Es en el RTS, no en el reglamento, donde aparece el requisito."),
 close=("Cite RTS 2024/1774 Art. 12 as the DORA basis and evidence the time source.",
        "Citar el art. 12 del RTS 2024/1774 como base DORA y evidenciar la fuente de tiempo.")),
"8.18": dict(
 covers=("Privileged utilities restricted, logged and removed where unnecessary.",
         "Utilidades privilegiadas restringidas, registradas y eliminadas cuando no son necesarias."),
 adds=("Art. 9 requires access control policies and RTS Art. 21 the management of privileged accounts with logging; utility programs are not addressed as such.",
       "El art. 9 exige politicas de control de acceso y el art. 21 del RTS la gestion de cuentas privilegiadas con registro; los programas de utilidad no se tratan como tales."),
 close=("List the utilities in the privileged access procedure of RTS Art. 21.",
        "Listar las utilidades en el procedimiento de acceso privilegiado del art. 21 del RTS.")),
"8.19": dict(
 covers=("Software installed on production only through a controlled process.",
         "Software instalado en produccion solo mediante un proceso controlado."),
 adds=("Art. 9 requires ICT change management and RTS Art. 17 a change management procedure with testing, approval, rollback and emergency changes; software installation on production is one case within it.",
       "El art. 9 exige gestion de cambios TIC y el art. 17 del RTS un procedimiento de gestion de cambios con pruebas, aprobacion, marcha atras y cambios de emergencia; la instalacion de software en produccion es un caso dentro de el."),
 close=("Route every production install through the RTS Art. 17 change procedure.",
        "Canalizar toda instalacion en produccion por el procedimiento de cambios del art. 17 del RTS.")),
"8.21": dict(
 covers=("Security mechanisms, service levels and requirements of network services identified and monitored, including outsourced ones.",
         "Mecanismos de seguridad, niveles de servicio y requisitos de los servicios de red identificados y supervisados, incluidos los externalizados."),
 adds=("Art. 9 and RTS Art. 13 require network security (segmentation, encryption, secured connections, regular review); network services bought from third parties fall under the third-party regime of Art. 28-30, with the register and the mandatory clauses.",
       "El art. 9 y el art. 13 del RTS exigen seguridad de red (segmentacion, cifrado, conexiones protegidas, revision regular); los servicios de red contratados a terceros caen bajo el regimen de terceros de los arts. 28-30, con el registro y las clausulas obligatorias."),
 close=("Register telecom and network providers in the register of information and check their contracts against Art. 30.",
        "Registrar a los proveedores de telecomunicaciones y red en el registro de informacion y contrastar sus contratos con el art. 30.")),
"8.23": dict(
 covers=("Web access filtered against malicious and inappropriate sites.",
         "Acceso web filtrado frente a sitios maliciosos e inapropiados."),
 adds=("Art. 9 requires protection against unauthorised access and malicious code; web filtering is not named, it is one of the network security measures of RTS Art. 13.",
       "El art. 9 exige proteccion frente al acceso no autorizado y el codigo malicioso; el filtrado web no se nombra, es una de las medidas de seguridad de red del art. 13 del RTS."),
 close=("Cite the web filter under RTS Art. 13.",
        "Citar el filtro web bajo el art. 13 del RTS.")),
"8.25": dict(
 covers=("Rules for secure development across the lifecycle: requirements, design, coding, testing, deployment.",
         "Reglas para el desarrollo seguro en todo el ciclo de vida: requisitos, diseno, codificacion, pruebas, despliegue."),
 adds=("Art. 9 and RTS 2024/1774 Art. 16 require a policy on acquisition, development and maintenance of ICT systems with security requirements at each stage, testing before deployment, source code review for critical functions, protection of test data and a specific process for changes; entities must apply it to ICT provided by third parties too. ISO's lifecycle control is less prescriptive about testing and code review.",
       "El art. 9 y el art. 16 del RTS 2024/1774 exigen una politica de adquisicion, desarrollo y mantenimiento de sistemas TIC con requisitos de seguridad en cada fase, pruebas antes del despliegue, revision del codigo fuente en funciones esenciales, proteccion de los datos de prueba y un proceso especifico para los cambios; las entidades deben aplicarla tambien a las TIC provistas por terceros. El control de ciclo de vida de ISO es menos prescriptivo sobre pruebas y revision de codigo."),
 close=("Align the SDLC policy with RTS Art. 16 and evidence source code review for systems supporting critical functions.",
        "Alinear la politica de desarrollo con el art. 16 del RTS y evidenciar la revision de codigo fuente en los sistemas que soportan funciones esenciales.")),
"8.26": dict(
 covers=("Security requirements specified and approved for developed or acquired applications.",
         "Requisitos de seguridad especificados y aprobados para las aplicaciones desarrolladas o adquiridas."),
 adds=("Art. 9 asks for security to be considered in ICT systems generally; RTS Art. 16 requires security requirements in the acquisition and development policy but does not itemise application-level requirements.",
       "El art. 9 pide considerar la seguridad en los sistemas TIC en general; el art. 16 del RTS exige requisitos de seguridad en la politica de adquisicion y desarrollo pero no detalla los requisitos a nivel de aplicacion."),
 close=("Keep the requirements checklist as RTS Art. 16 evidence.",
        "Conservar la lista de requisitos como evidencia del art. 16 del RTS.")),
"8.27": dict(
 covers=("Documented secure architecture and engineering principles applied to every design.",
         "Principios documentados de arquitectura e ingenieria segura aplicados a todo diseno."),
 adds=("Art. 6 requires the framework and Art. 7 reliable, resilient, up-to-date ICT systems appropriate to the entity's size and activity; secure architecture principles are implied by 'resilient' but not required as a document.",
       "El art. 6 exige el marco y el art. 7 sistemas TIC fiables, resilientes y actualizados adecuados al tamano y actividad de la entidad; los principios de arquitectura segura se implican en 'resilientes' pero no se exigen como documento."),
 close=("Reference the principles from the framework document.",
        "Referenciar los principios desde el documento del marco.")),
"8.28": dict(
 covers=("Secure coding rules, tooling and training applied to all code.",
         "Reglas de codificacion segura, herramientas y formacion aplicadas a todo el codigo."),
 adds=("Art. 9 requires secure development; RTS Art. 16 requires secure coding practices and code review for critical functions without defining coding rules.",
       "El art. 9 exige desarrollo seguro; el art. 16 del RTS exige practicas de codificacion segura y revision de codigo en funciones esenciales sin definir las reglas de codificacion."),
 close=("Cite the coding standard and static analysis as RTS Art. 16 evidence.",
        "Citar la norma de codificacion y el analisis estatico como evidencia del art. 16 del RTS.")),
"8.30": dict(
 covers=("Outsourced development directed, monitored and reviewed.",
         "Desarrollo externalizado dirigido, supervisado y revisado."),
 adds=("Art. 28 and Art. 30 apply the third-party regime to the developer — register of information, due diligence, mandatory clauses, audit rights for critical functions — and RTS Art. 16 requires the development policy to apply to third-party-provided ICT; supervising the developer's process specifically is the entity's own control.",
       "Los arts. 28 y 30 aplican el regimen de terceros al desarrollador — registro de informacion, diligencia debida, clausulas obligatorias, derechos de auditoria en funciones esenciales — y el art. 16 del RTS exige que la politica de desarrollo se aplique a las TIC provistas por terceros; supervisar especificamente el proceso del desarrollador es un control propio de la entidad."),
 close=("Register the developer, apply Art. 30 clauses and evidence that the RTS Art. 16 policy was imposed on it.",
        "Registrar al desarrollador, aplicar las clausulas del art. 30 y evidenciar que se le impuso la politica del art. 16 del RTS.")),
"8.31": dict(
 covers=("Development, test and production separated with controlled promotion.",
         "Desarrollo, pruebas y produccion separados con promocion controlada."),
 adds=("Art. 9 requires production environments to be separated from development and testing; RTS Art. 16 details it: separate environments, no production data in test unless anonymised, controlled promotion, and — for critical functions — testing in an environment that mirrors production.",
       "El art. 9 exige separar los entornos de produccion de los de desarrollo y prueba; el art. 16 del RTS lo detalla: entornos separados, sin datos de produccion en pruebas salvo anonimizados, promocion controlada y — en funciones esenciales — pruebas en un entorno que replique produccion."),
 close=("Evidence the mirrored test environment for critical-function systems.",
        "Evidenciar el entorno de pruebas replica de produccion para los sistemas de funciones esenciales.")),
"8.34": dict(
 covers=("Audit tests on production agreed and controlled.",
         "Pruebas de auditoria sobre produccion acordadas y controladas."),
 adds=("Art. 6 requires internal audits of the framework and Art. 24-25 a testing programme executed by independent parties on production or production-like systems; how those tests are kept from disturbing production is left to the test methodology, not regulated.",
       "El art. 6 exige auditorias internas del marco y los arts. 24-25 un programa de pruebas ejecutado por partes independientes sobre sistemas de produccion o equivalentes; como se evita que esas pruebas perturben produccion se deja a la metodologia, no se regula."),
 close=("Include the ISO test-protection rules in the testing programme's methodology.",
        "Incluir las reglas ISO de proteccion de pruebas en la metodologia del programa de pruebas.")),
}
