D = {
"5.2": dict(
 covers=("A documented allocation of information security responsibilities to named roles, communicated to the organisation, which is what org.1 expects to see inside the policy.",
         "Una asignacion documentada de las responsabilidades de seguridad a roles concretos, comunicada a la organizacion, que es lo que org.1 espera ver dentro de la politica."),
 adds=("org.3 requires a formal authorisation procedure: who may approve the entry of new systems, changes, use of equipment, external connections and media, with the responsible person named for each kind of decision and the decision recorded. Assigning roles does not create that procedure.",
       "org.3 exige un procedimiento formal de autorizacion: quien puede aprobar la entrada de sistemas nuevos, los cambios, el uso de equipos, las conexiones externas y los soportes, con el responsable designado para cada tipo de decision y la decision registrada. Asignar roles no crea ese procedimiento."),
 close=("Write the authorisation procedure as a table of decision types versus responsible roles, and keep the signed authorisations as evidence for the ENS audit.",
        "Redactar el procedimiento de autorizacion como una tabla de tipos de decision frente a roles responsables, y conservar las autorizaciones firmadas como evidencia para la auditoria ENS.")),
"5.4": dict(
 covers=("Visible management commitment: security is required of everyone, resourced and enforced, which is the spirit of org.1.",
         "Compromiso visible de la direccion: la seguridad se exige a todos, se dota de recursos y se hace cumplir, que es el espiritu de org.1."),
 adds=("org.1 makes the policy a formal act: it must be approved by the highest governing body, state the objectives and the legal framework, define the roles of the ENS (responsible for information, for the service, for security and for the system) and the procedure to resolve conflicts between them, and set a review cycle. Management support without that document does not meet the measure.",
       "org.1 hace de la politica un acto formal: la debe aprobar el organo superior, enunciar los objetivos y el marco legal, definir los roles del ENS (responsable de la informacion, del servicio, de la seguridad y del sistema) y el procedimiento para resolver conflictos entre ellos, y fijar un ciclo de revision. El respaldo de la direccion sin ese documento no cumple la medida."),
 close=("Have the security policy formally approved at board or governing body level, naming the four ENS roles and their conflict-resolution rule.",
        "Aprobar formalmente la politica de seguridad al nivel del organo de gobierno, nombrando los cuatro roles del ENS y su regla de resolucion de conflictos.")),
"5.5": dict(
 covers=("A list of the authorities to contact, the person responsible for the contact and the circumstances in which it happens.",
         "Una lista de las autoridades con las que contactar, la persona responsable del contacto y las circunstancias en que ocurre."),
 adds=("op.exp.7 and Article 33 of RD 311/2022 impose a duty: incidents with a significant impact must be notified to the CCN-CERT (or the competent CSIRT for private suppliers) through the channel and with the information the CCN prescribes, and the entity must follow the CCN's instructions during the response. Knowing whom to call is the precondition; notifying is the obligation.",
       "op.exp.7 y el articulo 33 del RD 311/2022 imponen un deber: los incidentes con impacto significativo deben notificarse al CCN-CERT (o al CSIRT competente en el caso de proveedores privados) por el canal y con la informacion que prescribe el CCN, y la entidad debe seguir las instrucciones del CCN durante la respuesta. Saber a quien llamar es la condicion previa; notificar es la obligacion."),
 close=("Add the CCN-CERT notification step, with its criteria and template, to the incident procedure, and record each notification made.",
        "Anadir al procedimiento de incidentes el paso de notificacion al CCN-CERT, con sus criterios y plantilla, y registrar cada notificacion realizada.")),
"5.7": dict(
 covers=("A process that collects information about threats from internal and external sources, analyses it and turns it into decisions about controls.",
         "Un proceso que recoge informacion sobre amenazas de fuentes internas y externas, la analiza y la convierte en decisiones sobre los controles."),
 adds=("op.mon.3 is an operational measure that grows with the category: it asks for surveillance of the system, the collection of security events, the integration of threat feeds into the detection tools and, at higher categories, a security operations capability. The ISO control is an analytical process; the ENS wants it wired into monitoring.",
       "op.mon.3 es una medida operativa que crece con la categoria: pide vigilancia del sistema, recogida de eventos de seguridad, integracion de fuentes de amenazas en las herramientas de deteccion y, en categorias altas, una capacidad de operacion de seguridad. El control ISO es un proceso analitico; el ENS lo quiere conectado a la monitorizacion."),
 close=("Feed the threat intelligence into the SIEM or monitoring tool and document how detected threats change detection rules.",
        "Conectar la inteligencia de amenazas al SIEM o herramienta de monitorizacion y documentar como las amenazas detectadas cambian las reglas de deteccion.")),
"5.8": dict(
 covers=("Security requirements and risk considered in every project from start to finish, whatever the project is about.",
         "Requisitos de seguridad y riesgo considerados en todo proyecto de principio a fin, sea cual sea su objeto."),
 adds=("op.pl.2 asks for a documented security architecture (physical, logical, administrative) that new systems must fit, and org.4 for an authorisation process before a system enters service; the ENS looks at the system, not at the project. Neither measure is satisfied merely because projects consider security.",
       "op.pl.2 pide una arquitectura de seguridad documentada (fisica, logica, administrativa) en la que deben encajar los sistemas nuevos, y org.4 un proceso de autorizacion antes de que un sistema entre en servicio; el ENS mira al sistema, no al proyecto. Ninguna de las dos medidas se satisface solo porque los proyectos consideren la seguridad."),
 close=("Maintain the security architecture document and make the go-live authorisation a formal gate in the project method.",
        "Mantener el documento de arquitectura de seguridad y hacer de la autorizacion de puesta en servicio un hito formal del metodo de proyectos.")),
"5.10": dict(
 covers=("A documented acceptable-use policy for information and assets, communicated to users and third parties.",
         "Una politica documentada de uso aceptable de la informacion y los activos, comunicada a usuarios y terceros."),
 adds=("mp.per.2 requires each person's security duties and obligations to be stated and signed, including the disciplinary consequences, and mp.eq.1 a clear desk rule; the ENS does not have a general acceptable-use measure and does not accept a policy nobody has signed.",
       "mp.per.2 exige que los deberes y obligaciones de seguridad de cada persona esten enunciados y firmados, incluidas las consecuencias disciplinarias, y mp.eq.1 una regla de puesto despejado; el ENS no tiene una medida general de uso aceptable y no acepta una politica que nadie haya firmado."),
 close=("Turn the policy into a signed acknowledgement per person and add the clear desk rule explicitly.",
        "Convertir la politica en un reconocimiento firmado por persona y anadir explicitamente la regla de puesto despejado.")),
"5.11": dict(
 covers=("A procedure that recovers equipment, information, credentials and access when a person or supplier leaves.",
         "Un procedimiento que recupera equipos, informacion, credenciales y accesos cuando una persona o proveedor se va."),
 adds=("mp.if.7 registers every piece of equipment that enters or leaves the premises, at any time, not only on departure; it is a physical control on the movement of assets, not a leaver process. The ENS handles the leaver side through op.acc (access revocation).",
       "mp.if.7 registra cada equipo que entra o sale de las instalaciones, en cualquier momento y no solo al cesar; es un control fisico sobre el movimiento de activos, no un proceso de baja. El ENS trata la baja por la via de op.acc (revocacion de accesos)."),
 close=("Keep an entry/exit register of equipment (who, what, when, authorised by whom) and link the leaver checklist to it.",
        "Llevar un registro de entrada y salida de equipos (quien, que, cuando, autorizado por quien) y enlazar a el la lista de comprobacion de bajas.")),
"5.14": dict(
 covers=("One policy with rules and agreements for transferring information by any means: electronic, physical media, verbal.",
         "Una politica con reglas y acuerdos para transferir informacion por cualquier medio: electronico, soportes fisicos, verbal."),
 adds=("The ENS decomposes it into measures with concrete, category-dependent requirements: mp.com.2 confidentiality on the network (VPN, approved algorithms), mp.com.3 integrity and authenticity of communications, mp.s.1 e-mail protection (anti-spam, anti-malware, sender authentication), mp.si.4 encrypted media in transport with a register of shipments. An ISO policy states principles; the ENS demands specific mechanisms.",
       "El ENS lo descompone en medidas con exigencias concretas y dependientes de la categoria: mp.com.2 confidencialidad en la red (VPN, algoritmos aprobados), mp.com.3 integridad y autenticidad de las comunicaciones, mp.s.1 proteccion del correo (antispam, antimalware, autenticacion del remitente), mp.si.4 soportes cifrados en transporte con registro de envios. Una politica ISO enuncia principios; el ENS exige mecanismos concretos."),
 close=("Map each transfer channel to the ENS measure and its mechanism for the system's category (algorithms per CCN-STIC 807, e-mail filters, encrypted media and shipment log).",
        "Asociar cada canal de transferencia a la medida ENS y a su mecanismo segun la categoria del sistema (algoritmos segun CCN-STIC 807, filtros de correo, soportes cifrados y registro de envios).")),
"5.31": dict(
 covers=("An up-to-date inventory of legal, regulatory and contractual requirements affecting security, with an owner for each.",
         "Un inventario actualizado de los requisitos legales, reglamentarios y contractuales que afectan a la seguridad, con un responsable para cada uno."),
 adds=("org.2 wants the requirements turned into internal security regulations (what is allowed, what is forbidden, sanctions) and mp.info.1 the personal-data obligations applied; but the ENS is itself a legal obligation with its own conformity regime (Art. 27-31: self-assessment or certification, published Declaration or Certificate, biennial audit). Knowing that the ENS applies is not being conformant.",
       "org.2 quiere que los requisitos se conviertan en normativa interna de seguridad (que se permite, que se prohibe, sanciones) y mp.info.1 que se apliquen las obligaciones de datos personales; pero el ENS es en si mismo una obligacion legal con su propio regimen de conformidad (arts. 27-31: autoevaluacion o certificacion, Declaracion o Certificacion publicada, auditoria bienal). Saber que el ENS aplica no es ser conforme."),
 close=("Determine the system's category, run the ENS conformity process and publish the Declaration or Certificate of Conformity.",
        "Determinar la categoria del sistema, ejecutar el proceso de conformidad ENS y publicar la Declaracion o Certificacion de Conformidad.")),
"5.33": dict(
 covers=("Records identified, classified and protected against loss, tampering and unauthorised access for their retention period.",
         "Registros identificados, clasificados y protegidos frente a perdida, manipulacion y acceso no autorizado durante su periodo de conservacion."),
 adds=("The ENS has no general measure on records: op.exp.8 protects the activity logs (retention, integrity, access restricted to the security role) and mp.info.6 the backups. Retention periods for administrative records come from the entity's own regulations (archive law, procedure law), not from the ENS.",
       "El ENS no tiene una medida general sobre registros: op.exp.8 protege los registros de actividad (conservacion, integridad, acceso restringido al rol de seguridad) y mp.info.6 las copias de seguridad. Los plazos de conservacion de los registros administrativos vienen de la normativa propia de la entidad (ley de archivos, ley de procedimiento), no del ENS."),
 close=("Set and document the retention of activity logs and backups per op.exp.8/mp.info.6, and cross-reference the archive rules for the rest.",
        "Fijar y documentar la conservacion de los registros de actividad y las copias segun op.exp.8/mp.info.6, y remitir a las normas de archivo para el resto.")),
"5.35": dict(
 covers=("A periodic independent review of the security approach and its implementation, by internal audit or an external party, with findings reported to management.",
         "Una revision independiente periodica del enfoque de seguridad y de su implantacion, por auditoria interna o un tercero, con hallazgos reportados a la direccion."),
 adds=("Article 31 and Annex III fix the shape: a formal audit at least every two years (and after significant changes) for medium and high systems, against the Annex II measures, by an accredited certification body when the outcome is a Certificate; basic systems may self-assess. op.pl.1 provides the risk analysis and op.mon.2 the metrics the audit relies on. ISO sets neither the cycle nor the auditor's accreditation.",
       "El articulo 31 y el Anexo III fijan la forma: una auditoria formal al menos cada dos anos (y tras cambios significativos) para sistemas de categoria media y alta, contra las medidas del Anexo II, por una entidad de certificacion acreditada cuando el resultado es una Certificacion; los sistemas basicos pueden autoevaluarse. op.pl.1 aporta el analisis de riesgos y op.mon.2 las metricas en que se apoya la auditoria. ISO no fija ni el ciclo ni la acreditacion del auditor."),
 close=("Schedule the biennial ENS audit with an ENAC-accredited body (or the self-assessment for basic category) and keep the risk analysis and metrics current for it.",
        "Programar la auditoria ENS bienal con una entidad acreditada por ENAC (o la autoevaluacion en categoria basica) y mantener al dia el analisis de riesgos y las metricas para ella.")),
"5.36": dict(
 covers=("Managers regularly check that their areas comply with the security policy and standards, and correct deviations.",
         "Los responsables comprueban regularmente que sus areas cumplen la politica y las normas de seguridad, y corrigen las desviaciones."),
 adds=("org.2 and org.4 provide the internal regulations and the authorisation process, but the ENS verifies compliance through a defined instrument: the Declaration of Conformity (basic) or the Certificate (medium/high), published on the entity's electronic office. A management review has no such external effect.",
       "org.2 y org.4 aportan la normativa interna y el proceso de autorizacion, pero el ENS verifica el cumplimiento mediante un instrumento definido: la Declaracion de Conformidad (basica) o la Certificacion (media/alta), publicada en la sede electronica de la entidad. Una revision de la direccion no tiene ese efecto externo."),
 close=("Feed the management reviews into the conformity file and publish the Declaration or Certificate as Art. 38 requires.",
        "Alimentar con las revisiones de la direccion el expediente de conformidad y publicar la Declaracion o Certificacion como exige el art. 38.")),
"6.5": dict(
 covers=("Security duties that continue after leaving or changing role — confidentiality, return of assets, revocation — communicated and enforced.",
         "Deberes de seguridad que continuan tras el cese o cambio de puesto — confidencialidad, devolucion de activos, revocacion — comunicados y exigidos."),
 adds=("mp.per.2 states the duties and obligations of personnel while in post (including third parties) and their disciplinary consequences; it does not deal with the period after the relationship ends. The ENS covers that indirectly through op.acc (access removal) and mp.if.7 (equipment leaving), not as a personnel measure.",
       "mp.per.2 recoge los deberes y obligaciones del personal mientras esta en el puesto (terceros incluidos) y sus consecuencias disciplinarias; no trata el periodo posterior al fin de la relacion. El ENS lo cubre de forma indirecta por op.acc (retirada de accesos) y mp.if.7 (salida de equipos), no como medida de personal."),
 close=("Include the post-employment obligations in the signed duties document required by mp.per.2 so the ENS evidence covers both.",
        "Incluir las obligaciones posteriores al empleo en el documento de deberes firmado que exige mp.per.2 para que la evidencia ENS cubra ambas cosas.")),
"6.7": dict(
 covers=("A remote-working policy: authorised environments, device requirements, secure connection, rules of conduct and support.",
         "Una politica de trabajo a distancia: entornos autorizados, requisitos del dispositivo, conexion segura, reglas de conducta y soporte."),
 adds=("mp.eq.3 imposes concrete protections on portable devices (inventory, encryption, remote lock or wipe, no storage of high-category data) and op.acc.5 the authentication mechanism for external users, both escalating with the category; the ENS says nothing about the remote-working arrangement itself. An ISO policy without those device and authentication mechanisms does not meet the measures.",
       "mp.eq.3 impone protecciones concretas a los dispositivos portatiles (inventario, cifrado, bloqueo o borrado remoto, no almacenar informacion de categoria alta) y op.acc.5 el mecanismo de autenticacion para usuarios externos, ambos crecientes con la categoria; el ENS no dice nada del regimen de trabajo a distancia en si. Una politica ISO sin esos mecanismos de dispositivo y autenticacion no cumple las medidas."),
 close=("Enforce disk encryption and remote wipe on every portable device and two-factor authentication for external access at medium category and above.",
        "Aplicar cifrado de disco y borrado remoto en todo dispositivo portatil y autenticacion de dos factores para el acceso externo desde categoria media.")),
"6.8": dict(
 covers=("A known, easy channel for anyone to report security events, and the obligation to use it promptly.",
         "Un canal conocido y sencillo para que cualquiera notifique eventos de seguridad, y la obligacion de usarlo con prontitud."),
 adds=("op.exp.7 asks for the incident management process: detection, recording, classification, response, escalation to the CCN-CERT and closure. The internal reporting channel for personnel is assumed as an input to that process but is not a requirement in its own right.",
       "op.exp.7 pide el proceso de gestion de incidentes: deteccion, registro, clasificacion, respuesta, escalado al CCN-CERT y cierre. El canal interno de notificacion para el personal se da por supuesto como entrada de ese proceso, pero no es un requisito por si mismo."),
 close=("Document the reporting channel as the first step of the op.exp.7 procedure and count reports received as one of its metrics.",
        "Documentar el canal de notificacion como primer paso del procedimiento de op.exp.7 y contar las notificaciones recibidas entre sus metricas.")),
"7.4": dict(
 covers=("Continuous surveillance of premises: alarms, cameras, guards, with alerts and recordings reviewed.",
         "Vigilancia continua de las instalaciones: alarmas, camaras, vigilantes, con alertas y grabaciones revisadas."),
 adds=("mp.if.2 only requires that people entering the facility be identified and registered (who, when, why) and that visitors be escorted where applicable; continuous monitoring is not an ENS measure, though it may be a compensating control at high category.",
       "mp.if.2 solo exige que las personas que entran en la instalacion se identifiquen y registren (quien, cuando, para que) y que los visitantes vayan acompanados cuando proceda; la vigilancia continua no es una medida del ENS, aunque puede ser un control compensatorio en categoria alta."),
 close=("Keep the entry register mp.if.2 asks for; surveillance recordings can supplement it but do not replace it.",
        "Llevar el registro de entradas que pide mp.if.2; las grabaciones de vigilancia pueden complementarlo pero no lo sustituyen.")),
"7.6": dict(
 covers=("Rules for working inside secure areas: no unsupervised work, no recording devices, activity logged, areas locked when unattended.",
         "Reglas para trabajar dentro de las areas seguras: sin trabajo sin supervision, sin dispositivos de grabacion, actividad registrada, areas cerradas cuando estan vacias."),
 adds=("mp.if.1 requires the premises to be divided into separated areas with controlled entry between them; once inside, the ENS has no rules of conduct. The ISO control fills a gap the ENS leaves.",
       "mp.if.1 exige dividir las instalaciones en areas separadas con entrada controlada entre ellas; una vez dentro, el ENS no tiene reglas de conducta. El control ISO cubre un hueco que el ENS deja."),
 close=("Nothing more for the ENS; keep the ISO rules as good practice and cite mp.if.1 for the area separation.",
        "Nada mas para el ENS; mantener las reglas ISO como buena practica y citar mp.if.1 para la separacion de areas.")),
"7.12": dict(
 covers=("Power and data cabling protected against interception, interference and damage: conduits, separation, labelling, locked patch rooms.",
         "Cableado de energia y datos protegido frente a interceptacion, interferencias y danos: canalizaciones, separacion, etiquetado, salas de parcheo cerradas."),
 adds=("mp.if.3 conditions the premises generically — power, temperature, cabling and its protection as part of fitting-out — without addressing interception or interference on the cables as a threat; the ENS treats cabling as an installation matter.",
       "mp.if.3 acondiciona los locales de forma generica — energia, temperatura, cableado y su proteccion como parte del acondicionamiento — sin tratar la interceptacion o la interferencia en los cables como amenaza; el ENS trata el cableado como cuestion de instalacion."),
 close=("Document the cabling protection in the premises conditioning evidence for mp.if.3; the ISO measures already exceed it.",
        "Documentar la proteccion del cableado en la evidencia de acondicionamiento de mp.if.3; las medidas ISO ya lo superan.")),
"7.13": dict(
 covers=("Equipment maintained per the manufacturer's schedule, by authorised personnel, with records and with data protected during off-site repair.",
         "Equipos mantenidos segun el calendario del fabricante, por personal autorizado, con registros y con los datos protegidos durante las reparaciones externas."),
 adds=("op.exp.4 is about software maintenance: applying manufacturer updates and security patches on a defined schedule, with a procedure for urgent ones. Physical maintenance of hardware and the confidentiality of data on equipment sent for repair are not addressed by the ENS.",
       "op.exp.4 trata del mantenimiento del software: aplicar las actualizaciones del fabricante y los parches de seguridad con un calendario definido, con un procedimiento para los urgentes. El mantenimiento fisico del hardware y la confidencialidad de los datos en equipos enviados a reparar no los trata el ENS."),
 close=("Keep a patch schedule and record of applied updates for op.exp.4; the hardware side is covered by the ISO procedure alone.",
        "Llevar un calendario de parches y un registro de actualizaciones aplicadas para op.exp.4; la parte de hardware la cubre solo el procedimiento ISO.")),
"8.4": dict(
 covers=("Read and write access to source code, libraries and development tools restricted, logged and reviewed.",
         "Acceso de lectura y escritura al codigo fuente, las bibliotecas y las herramientas de desarrollo restringido, registrado y revisado."),
 adds=("mp.sw.1 sets conditions for developing applications (separate environment, methodology, no test on production data, security requirements); it does not restrict who can read or modify the source code. The ENS relies on op.acc for access in general.",
       "mp.sw.1 fija condiciones para el desarrollo de aplicaciones (entorno separado, metodologia, sin pruebas con datos de produccion, requisitos de seguridad); no restringe quien puede leer o modificar el codigo fuente. El ENS se apoya en op.acc para el acceso en general."),
 close=("Treat the code repository as an ENS asset under op.acc.2/op.acc.4 (rights per role, periodic review) and cite that for the audit.",
        "Tratar el repositorio de codigo como activo ENS bajo op.acc.2/op.acc.4 (derechos por rol, revision periodica) y citarlo para la auditoria.")),
"8.12": dict(
 covers=("Measures that detect and block the exfiltration of sensitive information: DLP on endpoints, e-mail and web, classification-based rules.",
         "Medidas que detectan y bloquean la exfiltracion de informacion sensible: DLP en puestos, correo y web, reglas basadas en la clasificacion."),
 adds=("mp.info.5 requires cleaning metadata and hidden content from documents before they leave, and mp.com.2 protects confidentiality on the network by encryption; neither is a leakage detection or blocking measure. The ENS has no DLP requirement.",
       "mp.info.5 exige limpiar los metadatos y el contenido oculto de los documentos antes de que salgan, y mp.com.2 protege la confidencialidad en la red mediante cifrado; ninguna es una medida de deteccion o bloqueo de fugas. El ENS no tiene un requisito de DLP."),
 close=("Add document sanitisation to the DLP policy so mp.info.5 is met; the rest is beyond the ENS.",
        "Anadir la limpieza de documentos a la politica DLP para cumplir mp.info.5; el resto queda mas alla del ENS.")),
"8.18": dict(
 covers=("Utility programs able to bypass controls identified, restricted to authorised users, logged and removed when not needed.",
         "Programas de utilidad capaces de eludir los controles identificados, restringidos a usuarios autorizados, registrados y eliminados cuando no son necesarios."),
 adds=("op.acc.4 manages access rights by need and op.exp.2 requires secure configuration (unnecessary functions removed, least privilege); the ENS does not single out privileged utilities as a control, so their restriction has to be evidenced under those two measures.",
       "op.acc.4 gestiona los derechos de acceso por necesidad y op.exp.2 exige configuracion segura (funciones innecesarias eliminadas, minimo privilegio); el ENS no singulariza las utilidades privilegiadas como control, asi que su restriccion se evidencia bajo esas dos medidas."),
 close=("List the privileged utilities in the secure configuration baseline and their authorised users in the rights register.",
        "Listar las utilidades privilegiadas en la linea base de configuracion segura y sus usuarios autorizados en el registro de derechos.")),
"8.28": dict(
 covers=("Secure coding standards per language, tooling (static analysis, dependency checks) and developer training, applied to in-house and acquired code.",
         "Normas de codificacion segura por lenguaje, herramientas (analisis estatico, revision de dependencias) y formacion de desarrolladores, aplicadas al codigo propio y adquirido."),
 adds=("mp.sw.1 asks for a recognised secure development methodology and for security to be considered in the whole lifecycle; it does not prescribe coding rules or their verification. The ISO control is more specific than the ENS measure.",
       "mp.sw.1 pide una metodologia de desarrollo seguro reconocida y que la seguridad se considere en todo el ciclo de vida; no prescribe reglas de codificacion ni su verificacion. El control ISO es mas especifico que la medida ENS."),
 close=("Reference the coding standards and analysis tools as part of the methodology evidence for mp.sw.1.",
        "Referenciar las normas de codificacion y las herramientas de analisis como parte de la evidencia de metodologia para mp.sw.1.")),
"8.30": dict(
 covers=("Outsourced development directed and reviewed: requirements, licensing, testing, access to code, evidence of secure practices.",
         "Desarrollo externalizado dirigido y revisado: requisitos, licencias, pruebas, acceso al codigo, evidencia de practicas seguras."),
 adds=("mp.sw.1 applies its development conditions to whoever develops, and op.ext.1 requires contracts with service levels, responsibilities and the security measures the supplier must apply; but supervising the external developer's process (code reviews, test evidence, escrow) is not required as such.",
       "mp.sw.1 aplica sus condiciones de desarrollo a quien desarrolle, y op.ext.1 exige contratos con niveles de servicio, responsabilidades y las medidas de seguridad que debe aplicar el proveedor; pero supervisar el proceso del desarrollador externo (revisiones de codigo, evidencia de pruebas, escrow) no se exige como tal."),
 close=("Put the mp.sw.1 conditions in the development contract under op.ext.1 and keep the review evidence.",
        "Incluir las condiciones de mp.sw.1 en el contrato de desarrollo bajo op.ext.1 y conservar la evidencia de revision.")),
"8.31": dict(
 covers=("Separate development, test and production environments, with controlled promotion, different credentials and no production data in test.",
         "Entornos de desarrollo, prueba y produccion separados, con promocion controlada, credenciales distintas y sin datos de produccion en pruebas."),
 adds=("mp.sw.2 requires acceptance testing before going live, in an environment other than production and without real data; the separation of the three environments is stated explicitly only for medium and high categories. For a basic system the ISO control exceeds the ENS.",
       "mp.sw.2 exige pruebas de aceptacion antes de la puesta en servicio, en un entorno distinto de produccion y sin datos reales; la separacion de los tres entornos se enuncia de forma explicita solo para las categorias media y alta. En un sistema basico el control ISO supera al ENS."),
 close=("Evidence the acceptance test and the non-production environment used for it; that satisfies mp.sw.2 at any category.",
        "Evidenciar la prueba de aceptacion y el entorno no productivo usado para ella; eso satisface mp.sw.2 en cualquier categoria.")),
"8.33": dict(
 covers=("Test data selected, anonymised or masked, protected and deleted after use, with authorisation when production data is copied.",
         "Datos de prueba seleccionados, anonimizados o enmascarados, protegidos y borrados tras su uso, con autorizacion cuando se copian datos de produccion."),
 adds=("mp.sw.2 (and mp.sw.1) forbid testing with real production data unless the test environment has the same security as production; the ENS says nothing about masking or protecting the test data itself.",
       "mp.sw.2 (y mp.sw.1) prohiben probar con datos reales de produccion salvo que el entorno de pruebas tenga la misma seguridad que produccion; el ENS no dice nada de enmascarar ni proteger los propios datos de prueba."),
 close=("Record for each test cycle that real data were not used, or that the test environment matched production security.",
        "Dejar constancia en cada ciclo de pruebas de que no se usaron datos reales, o de que el entorno de pruebas tenia la seguridad de produccion.")),
"8.34": dict(
 covers=("Audit and assurance tests on production agreed with management: scope, read-only access, timing, tools, and the data collected protected.",
         "Pruebas de auditoria y aseguramiento sobre produccion acordadas con la direccion: alcance, acceso de solo lectura, momento, herramientas, y los datos recogidos protegidos."),
 adds=("op.pl.1 plans and updates the risk analysis; protecting production systems during audit tests is not an ENS measure. The closest ENS expectation is that the biennial audit does not disturb the service, which is left to the auditor's method.",
       "op.pl.1 planifica y actualiza el analisis de riesgos; proteger los sistemas en produccion durante las pruebas de auditoria no es una medida del ENS. La expectativa ENS mas cercana es que la auditoria bienal no perturbe el servicio, lo que se deja al metodo del auditor."),
 close=("Include the ISO test-protection rules in the engagement letter of the ENS audit; nothing else is needed.",
        "Incluir las reglas ISO de proteccion de pruebas en la carta de encargo de la auditoria ENS; no hace falta nada mas.")),
}
