D = {
"5.3": dict(
 covers=("Conflicting duties identified and separated so that no one person can request, approve and execute a sensitive action alone.",
         "Funciones en conflicto identificadas y separadas para que ninguna persona pueda solicitar, aprobar y ejecutar sola una accion sensible."),
 adds=("cir.1.2 asks the entity to assign roles and responsibilities for security and communicate them; segregation of duties is not among the 2024/2690 requirements. It reappears only implicitly in cir.11 (privileged accounts kept separate, admin systems isolated).",
       "cir.1.2 pide a la entidad asignar y comunicar los roles y responsabilidades de seguridad; la segregacion de funciones no esta entre los requisitos del 2024/2690. Reaparece solo de forma implicita en cir.11 (cuentas privilegiadas separadas, sistemas de administracion aislados)."),
 close=("Show the role assignment cir.1.2 wants and cite the separation of privileged accounts under cir.11.3 as where segregation is evidenced.",
        "Mostrar la asignacion de roles que quiere cir.1.2 y citar la separacion de cuentas privilegiadas de cir.11.3 como el lugar donde se evidencia la segregacion.")),
"5.5": dict(
 covers=("Contacts with the CSIRT, the competent authority and law enforcement identified, with the trigger and the responsible person.",
         "Contactos con el CSIRT, la autoridad competente y las fuerzas de seguridad identificados, con el disparador y el responsable."),
 adds=("Article 23 is a binding reporting chain for significant incidents: early warning within 24 hours, incident notification within 72 hours with an initial assessment, intermediate reports on request and a final report within one month, to the CSIRT or competent authority, plus informing affected recipients of services. cir.3.3 is the internal event-reporting channel that feeds it. Having the contacts is the precondition; meeting the deadlines is the obligation, and it is sanctionable.",
       "El articulo 23 es una cadena de notificacion vinculante para los incidentes significativos: alerta temprana en 24 horas, notificacion del incidente en 72 horas con una evaluacion inicial, informes intermedios a peticion y un informe final en un mes, al CSIRT o a la autoridad competente, mas informar a los destinatarios de servicios afectados. cir.3.3 es el canal interno de notificacion de eventos que la alimenta. Tener los contactos es la condicion previa; cumplir los plazos es la obligacion, y es sancionable."),
 close=("Add the 24h/72h/1-month steps, the significance criteria and the templates to the incident procedure, and rehearse them.",
        "Anadir al procedimiento de incidentes los pasos de 24 h/72 h/1 mes, los criterios de significatividad y las plantillas, y ensayarlos.")),
"5.7": dict(
 covers=("Threat information collected, analysed and used to adjust controls and detection, from external feeds and internal events.",
         "Informacion sobre amenazas recogida, analizada y usada para ajustar los controles y la deteccion, de fuentes externas y eventos internos."),
 adds=("cir.2.1 wants a risk management framework fed by current threats, reviewed at least yearly and after significant incidents; Article 29 promotes participation in cybersecurity information-sharing arrangements with peers and authorities. ISO's threat intelligence is inward-looking; NIS2 expects it to update the risk assessment and, ideally, to be shared.",
       "cir.2.1 quiere un marco de gestion de riesgos alimentado por las amenazas actuales, revisado al menos anualmente y tras incidentes significativos; el articulo 29 promueve la participacion en acuerdos de intercambio de informacion de ciberseguridad con pares y autoridades. La inteligencia de amenazas de ISO mira hacia dentro; NIS2 espera que actualice la evaluacion de riesgos y, a ser posible, que se comparta."),
 close=("Document how threat intelligence feeds the yearly risk review, and join a sectoral ISAC or CSIRT sharing arrangement.",
        "Documentar como la inteligencia de amenazas alimenta la revision anual de riesgos, y participar en un ISAC sectorial o en un acuerdo de intercambio con el CSIRT.")),
"5.8": dict(
 covers=("Security requirements, risk assessment and review points built into every project, IT or not.",
         "Requisitos de seguridad, evaluacion de riesgos y puntos de revision integrados en todo proyecto, sea o no de TI."),
 adds=("cir.6.1 requires security requirements and a risk assessment before acquiring ICT services or products, and cir.6.2 a secure development lifecycle with defined rules; both target network and information systems specifically. Projects without a system component (organisational change, a new office) fall outside NIS2's interest.",
       "cir.6.1 exige requisitos de seguridad y una evaluacion de riesgos antes de adquirir servicios o productos TIC, y cir.6.2 un ciclo de vida de desarrollo seguro con reglas definidas; ambos apuntan especificamente a los sistemas de redes e informacion. Los proyectos sin componente de sistema (un cambio organizativo, una nueva oficina) quedan fuera del interes de NIS2."),
 close=("Make the pre-acquisition risk assessment a mandatory project artefact for any ICT purchase or build.",
        "Hacer de la evaluacion de riesgos previa a la adquisicion un artefacto obligatorio del proyecto para cualquier compra o desarrollo TIC.")),
"5.13": dict(
 covers=("Labelling procedures that make the classification visible on documents, media and systems, including automated labels.",
         "Procedimientos de etiquetado que hacen visible la clasificacion en documentos, soportes y sistemas, incluidas etiquetas automaticas."),
 adds=("cir.12.1 requires a classification scheme for all assets, with levels based on the security needs and applied to information, and periodic review; labelling as a separate practice is not mentioned. The ISO control goes further than NIS2 here.",
       "cir.12.1 exige un esquema de clasificacion para todos los activos, con niveles basados en las necesidades de seguridad y aplicado a la informacion, y revision periodica; el etiquetado como practica aparte no se menciona. El control ISO va aqui mas lejos que NIS2."),
 close=("Nothing more for NIS2; keep the classification scheme reviewed and cite the labels as its visible application.",
        "Nada mas para NIS2; mantener el esquema de clasificacion revisado y citar las etiquetas como su aplicacion visible.")),
"5.14": dict(
 covers=("Rules and agreements for every transfer channel — electronic, physical media, verbal — including encryption, non-repudiation and third-party agreements.",
         "Reglas y acuerdos para cada canal de transferencia — electronico, soportes fisicos, verbal — incluidos cifrado, no repudio y acuerdos con terceros."),
 adds=("Article 21(2)(j) requires secured voice, video and text communications and secured emergency communication systems where appropriate, and cir.9 a cryptography policy that determines which data and communications are encrypted and how; NIS2 is technical and network-centred. A transfer policy that covers paper and conversations is broader, but it does not by itself specify the cryptographic mechanisms cir.9 wants.",
       "El articulo 21.2.j exige comunicaciones de voz, video y texto protegidas y sistemas de comunicacion de emergencia protegidos cuando proceda, y cir.9 una politica de criptografia que determine que datos y comunicaciones se cifran y como; NIS2 es tecnico y centrado en la red. Una politica de transferencia que cubre el papel y las conversaciones es mas amplia, pero no especifica por si misma los mecanismos criptograficos que quiere cir.9."),
 close=("Add to the transfer policy the list of encrypted channels, the algorithms and the secured emergency channel, per cir.9.",
        "Anadir a la politica de transferencia la lista de canales cifrados, los algoritmos y el canal de emergencia protegido, segun cir.9.")),
"5.20": dict(
 covers=("Security clauses in every supplier agreement: requirements, incident notification, audit rights, subcontracting, exit.",
         "Clausulas de seguridad en cada acuerdo con proveedores: requisitos, notificacion de incidentes, derechos de auditoria, subcontratacion, salida."),
 adds=("cir.5.1 sets the requirement at policy level: the supply-chain policy must define the criteria to select suppliers, the security requirements they must meet based on their practices and the vulnerabilities of their products, and the review of the policy. The content of each contract is left to the entity; ISO's clause-level control is more detailed than the NIS2 policy requirement.",
       "cir.5.1 situa el requisito a nivel de politica: la politica de cadena de suministro debe definir los criterios para seleccionar proveedores, los requisitos de seguridad que deben cumplir en funcion de sus practicas y de las vulnerabilidades de sus productos, y la revision de la politica. El contenido de cada contrato se deja a la entidad; el control ISO a nivel de clausula es mas detallado que el requisito de politica de NIS2."),
 close=("Write the supply-chain policy cir.5.1 asks for and point from it to the standard clause set.",
        "Redactar la politica de cadena de suministro que pide cir.5.1 y remitir desde ella al juego de clausulas estandar.")),
"5.23": dict(
 covers=("A policy for acquiring, using and exiting cloud services: risk assessment, shared responsibilities, data location, exit plan.",
         "Una politica para adquirir, usar y abandonar servicios en la nube: evaluacion de riesgos, responsabilidades compartidas, ubicacion de datos, plan de salida."),
 adds=("cir.5.1 and cir.6.1 treat the cloud provider as any supplier or acquisition (selection criteria, requirements, risk assessment). But NIS2 also regulates cloud providers directly as an Annex I sector, and the customer's use of them is watched through the supply-chain lens: the provider's own NIS2 status and its incident notifications to the customer become part of the requirement.",
       "cir.5.1 y cir.6.1 tratan al proveedor de nube como a cualquier proveedor o adquisicion (criterios de seleccion, requisitos, evaluacion de riesgos). Pero NIS2 tambien regula directamente a los proveedores de nube como sector del Anexo I, y el uso que hace el cliente se vigila con la lente de la cadena de suministro: el propio estatus NIS2 del proveedor y sus notificaciones de incidentes al cliente pasan a formar parte del requisito."),
 close=("Record each cloud provider's NIS2 status and incident-notification commitment in the supplier register.",
        "Registrar en el directorio de proveedores el estatus NIS2 de cada proveedor de nube y su compromiso de notificacion de incidentes.")),
"5.28": dict(
 covers=("Procedures to identify, collect, acquire and preserve evidence so that it is admissible: chain of custody, integrity, competent staff.",
         "Procedimientos para identificar, recoger, adquirir y preservar evidencias de forma admisible: cadena de custodia, integridad, personal competente."),
 adds=("cir.3.2 requires logging and monitoring procedures, log retention for a defined period, log protection and regular review, so that incidents can be reconstructed; it does not mention forensic evidence handling or admissibility. NIS2 wants the raw material; ISO wants it handled correctly.",
       "cir.3.2 exige procedimientos de registro y monitorizacion, conservacion de los registros durante un periodo definido, su proteccion y revision regular, de modo que los incidentes puedan reconstruirse; no menciona el manejo forense de evidencias ni su admisibilidad. NIS2 quiere la materia prima; ISO quiere que se maneje correctamente."),
 close=("Set the log retention period cir.3.2 asks for and reference the forensic procedure from the incident plan.",
        "Fijar el periodo de conservacion de registros que pide cir.3.2 y referenciar el procedimiento forense desde el plan de incidentes.")),
"5.31": dict(
 covers=("An inventory of the legal and contractual requirements affecting security, kept up to date, with owners and the controls that meet each.",
         "Un inventario de los requisitos legales y contractuales que afectan a la seguridad, actualizado, con responsables y los controles que cumplen cada uno."),
 adds=("cir.1.1 wants the policy aligned with the applicable obligations and cir.2.2 a compliance monitoring process with regular reporting to the management body. But NIS2 itself creates duties the inventory does not discharge: registration with the competent authority (Art. 3 and 27), the reporting chain of Art. 23, the management body's approval and training (Art. 20), cooperation with supervision (Art. 32). Once transposed in Spain, these will carry their own deadlines.",
       "cir.1.1 quiere la politica alineada con las obligaciones aplicables y cir.2.2 un proceso de supervision del cumplimiento con informes regulares al organo de direccion. Pero NIS2 crea por si misma deberes que el inventario no cumple: el registro ante la autoridad competente (arts. 3 y 27), la cadena de notificacion del art. 23, la aprobacion y formacion del organo de direccion (art. 20), la cooperacion con la supervision (art. 32). Una vez transpuesta en Espana, tendran sus propios plazos."),
 close=("Determine whether the entity is essential or important, register with the authority, and add the NIS2 duties to the compliance monitoring cir.2.2 requires.",
        "Determinar si la entidad es esencial o importante, registrarse ante la autoridad y anadir los deberes NIS2 a la supervision del cumplimiento que exige cir.2.2.")),
"5.33": dict(
 covers=("Records protected against loss, tampering, unauthorised access and unlawful destruction, for the period each must be kept.",
         "Registros protegidos frente a perdida, manipulacion, acceso no autorizado y destruccion ilicita, durante el periodo en que deba conservarse cada uno."),
 adds=("cir.3.2 only concerns activity and security logs: retention period, integrity protection, restricted access. NIS2 has no measure on the protection of business or compliance records in general.",
       "cir.3.2 solo se refiere a los registros de actividad y de seguridad: periodo de conservacion, proteccion de integridad, acceso restringido. NIS2 no tiene una medida sobre la proteccion de los registros de negocio o de cumplimiento en general."),
 close=("Nothing more for NIS2 beyond the log retention and protection of cir.3.2.",
        "Nada mas para NIS2 mas alla de la conservacion y proteccion de registros de cir.3.2.")),
"5.37": dict(
 covers=("Operating procedures for systems and processes documented, current and available to those who run them.",
         "Procedimientos operativos de sistemas y procesos documentados, actualizados y disponibles para quienes los ejecutan."),
 adds=("cir.1.1 requires a network and information systems security policy, approved by the management body, with objectives, resources, roles and the topic-specific policies that develop it, reviewed at planned intervals. Documented operating procedures at the technical level are presupposed by many requirements (backup, change, incident) but are not a requirement of their own.",
       "cir.1.1 exige una politica de seguridad de las redes y sistemas de informacion, aprobada por el organo de direccion, con objetivos, recursos, roles y las politicas especificas que la desarrollan, revisada a intervalos planificados. Los procedimientos operativos documentados a nivel tecnico se presuponen en muchos requisitos (copias, cambios, incidentes) pero no son un requisito propio."),
 close=("Make sure the top-level policy cir.1.1 wants exists and lists the operating procedures as its supporting documents.",
        "Asegurarse de que existe la politica de primer nivel que quiere cir.1.1 y de que enumera los procedimientos operativos como documentos de soporte.")),
"6.6": dict(
 covers=("Confidentiality or non-disclosure agreements with defined content, signed by personnel and third parties, reviewed periodically.",
         "Acuerdos de confidencialidad o no divulgacion con contenido definido, firmados por el personal y los terceros, revisados periodicamente."),
 adds=("cir.10.1 asks the entity to ensure that employees and direct suppliers understand and commit to their security responsibilities, according to the service and the role; the form of that commitment is left open. An NDA is one way of evidencing it, alongside terms of employment and the acceptable-use policy.",
       "cir.10.1 pide a la entidad asegurarse de que los empleados y los proveedores directos entienden y asumen sus responsabilidades de seguridad, segun el servicio y el rol; la forma de ese compromiso se deja abierta. Un acuerdo de confidencialidad es una forma de evidenciarlo, junto a las condiciones de empleo y la politica de uso aceptable."),
 close=("Keep the signed NDAs as the evidence of commitment cir.10.1 wants, covering suppliers too.",
        "Conservar los acuerdos de confidencialidad firmados como la evidencia de compromiso que quiere cir.10.1, cubriendo tambien a los proveedores.")),
"6.7": dict(
 covers=("A remote-working policy that addresses the environment, the device, the connection, the rules and the support.",
         "Una politica de trabajo a distancia que trata el entorno, el dispositivo, la conexion, las reglas y el soporte."),
 adds=("cir.11.1 requires an access control policy that covers remote access with appropriate authentication and logging, and cir.6.7 network security including secured remote connections and, per Art. 21(2)(j), multi-factor authentication; NIS2 does not look at the person's home or the ergonomics of the arrangement, only at the technical access path.",
       "cir.11.1 exige una politica de control de acceso que cubra el acceso remoto con autenticacion y registro adecuados, y cir.6.7 seguridad de red incluidas las conexiones remotas protegidas y, segun el art. 21.2.j, autenticacion multifactor; NIS2 no mira el domicilio de la persona ni las condiciones del regimen, solo la via tecnica de acceso."),
 close=("Enforce MFA and VPN for every remote session and log it; the organisational side of the policy is beyond NIS2.",
        "Aplicar MFA y VPN en toda sesion remota y registrarla; el lado organizativo de la politica queda mas alla de NIS2.")),
"7.3": dict(
 covers=("Offices, rooms and facilities protected physically: locks, no external signs of sensitive areas, protection of records and equipment.",
         "Oficinas, salas e instalaciones protegidas fisicamente: cerraduras, sin senales externas de las areas sensibles, proteccion de registros y equipos."),
 adds=("cir.13.3 asks for perimeter and physical access control of the premises that house network and information systems, with logging and periodic review of access rights; ordinary offices are relevant only if they host such systems.",
       "cir.13.3 pide control perimetral y de acceso fisico de las instalaciones que albergan sistemas de redes e informacion, con registro y revision periodica de los derechos de acceso; las oficinas ordinarias solo importan si alojan tales sistemas."),
 close=("Identify which rooms hold in-scope systems and evidence access control and logs for those; the rest is ISO only.",
        "Identificar que salas albergan sistemas en alcance y evidenciar el control de acceso y los registros de esas; el resto es solo ISO.")),
"7.4": dict(
 covers=("Continuous physical monitoring: alarms, video surveillance, guards, alerting and review of events.",
         "Vigilancia fisica continua: alarmas, videovigilancia, vigilantes, alertas y revision de eventos."),
 adds=("cir.13.3 requires access control at the perimeter and to the areas with systems, and the logging of that access; continuous monitoring is not spelled out, though it fits under the general protection against physical threats of cir.13.2.",
       "cir.13.3 exige control de acceso en el perimetro y a las areas con sistemas, y el registro de ese acceso; la vigilancia continua no se detalla, aunque encaja en la proteccion general frente a amenazas fisicas de cir.13.2."),
 close=("Cite the monitoring as the detective control behind cir.13.3's access logs.",
        "Citar la vigilancia como el control detectivo detras de los registros de acceso de cir.13.3.")),
"7.6": dict(
 covers=("Rules of conduct inside secure areas: supervision, no recording devices, activity logging, locked when unattended.",
         "Reglas de conducta dentro de las areas seguras: supervision, sin dispositivos de grabacion, registro de actividad, cierre cuando estan vacias."),
 adds=("cir.13.3 controls who gets in and records it; it contains no rules about behaviour inside. The ISO control adds something NIS2 does not ask for.",
       "cir.13.3 controla quien entra y lo registra; no contiene reglas sobre el comportamiento dentro. El control ISO anade algo que NIS2 no pide."),
 close=("Nothing further for NIS2.",
        "Nada mas para NIS2.")),
"7.7": dict(
 covers=("A clear desk and clear screen rule: papers and media locked away, sessions locked, printers cleared.",
         "Una regla de puesto despejado y pantalla limpia: papeles y soportes guardados bajo llave, sesiones bloqueadas, impresoras vaciadas."),
 adds=("cir.12.2 asks for rules on handling assets according to their classification — storage, use, transport, disposal; a clear desk rule is a sensible instance of those rules, not a requirement in itself.",
       "cir.12.2 pide reglas de manejo de activos segun su clasificacion — almacenamiento, uso, transporte, eliminacion; una regla de puesto despejado es un ejemplo razonable de esas reglas, no un requisito en si."),
 close=("Include the clear desk rule in the asset-handling rules cir.12.2 wants.",
        "Incluir la regla de puesto despejado en las reglas de manejo de activos que quiere cir.12.2.")),
"7.8": dict(
 covers=("Equipment sited to reduce environmental risk and unauthorised viewing or access: screens away from public view, servers in racks, sensitive equipment isolated.",
         "Equipos ubicados para reducir el riesgo ambiental y la visualizacion o el acceso no autorizados: pantallas fuera de la vista publica, servidores en racks, equipos sensibles aislados."),
 adds=("cir.13.2 requires protection against physical and environmental threats (fire, flood, power, temperature) based on a risk assessment; the siting of individual equipment to prevent shoulder surfing or tampering is not addressed.",
       "cir.13.2 exige proteccion frente a amenazas fisicas y ambientales (incendio, inundacion, energia, temperatura) basada en una evaluacion de riesgos; la ubicacion de cada equipo para evitar miradas o manipulaciones no se trata."),
 close=("Cover the environmental side in the cir.13.2 risk assessment; the siting rules remain an ISO extra.",
        "Cubrir la parte ambiental en la evaluacion de riesgos de cir.13.2; las reglas de ubicacion siguen siendo un extra de ISO.")),
"7.9": dict(
 covers=("Assets used off-site protected: authorisation, encryption, physical custody, insurance, rules for travel and home use.",
         "Activos usados fuera de las instalaciones protegidos: autorizacion, cifrado, custodia fisica, seguro, reglas para viajes y uso domestico."),
 adds=("cir.12.2 covers handling of assets in general, including outside the premises, and cir.12.3 removable media; NIS2 does not treat off-site assets as a separate case. The ISO control is the finer-grained one.",
       "cir.12.2 cubre el manejo de activos en general, tambien fuera de las instalaciones, y cir.12.3 los soportes extraibles; NIS2 no trata los activos fuera de las instalaciones como caso aparte. El control ISO es el de grano mas fino."),
 close=("Reference the off-site rules from the asset-handling policy cir.12.2 asks for.",
        "Referenciar las reglas de uso fuera de las instalaciones desde la politica de manejo de activos que pide cir.12.2.")),
"7.12": dict(
 covers=("Cabling protected from interception, interference and damage: conduits, separation of power and data, locked patch panels, labelling.",
         "Cableado protegido frente a interceptacion, interferencias y danos: canalizaciones, separacion de energia y datos, paneles de parcheo cerrados, etiquetado."),
 adds=("cir.13.1 protects supporting utilities — power, telecommunications, cooling, water — against failure and disruption; cabling is one of those utilities, seen from the availability angle, not as an interception risk.",
       "cir.13.1 protege los suministros de apoyo — energia, telecomunicaciones, refrigeracion, agua — frente a fallos e interrupciones; el cableado es uno de esos suministros, visto desde la disponibilidad, no como riesgo de interceptacion."),
 close=("Evidence redundancy and protection of the communication lines under cir.13.1; the confidentiality angle is ISO only.",
        "Evidenciar la redundancia y proteccion de las lineas de comunicacion bajo cir.13.1; el angulo de confidencialidad es solo ISO.")),
"7.14": dict(
 covers=("Equipment checked before disposal or re-use, data securely erased or media destroyed, licences removed, with a record.",
         "Equipos verificados antes de eliminarlos o reutilizarlos, datos borrados de forma segura o soportes destruidos, licencias retiradas, con registro."),
 adds=("cir.12.5 requires procedures for the return of assets and the deletion of data from them when a person leaves; secure disposal of equipment at end of life, verification of erasure and the handling of media outside the leaver scenario are not covered.",
       "cir.12.5 exige procedimientos para la devolucion de activos y el borrado de sus datos cuando una persona se va; la eliminacion segura de equipos al final de su vida, la verificacion del borrado y el manejo de soportes fuera del escenario de baja no estan cubiertos."),
 close=("Apply the same erasure procedure to leavers' devices and evidence it, which meets cir.12.5.",
        "Aplicar el mismo procedimiento de borrado a los dispositivos de quienes se van y evidenciarlo, lo que cumple cir.12.5.")),
"8.1": dict(
 covers=("A policy for endpoint devices: registration, hardening, encryption, patching, malware protection, remote wipe, BYOD rules, user responsibilities.",
         "Una politica de dispositivos de usuario: registro, bastionado, cifrado, parcheo, proteccion antimalware, borrado remoto, reglas BYOD, responsabilidades del usuario."),
 adds=("cir.6.9 requires protection against malicious software on all systems and cir.12.2 rules for handling assets; NIS2 has no requirement dedicated to endpoints. Encryption of laptops, remote wipe and BYOD conditions would have to be argued under the general asset-handling and network-security requirements.",
       "cir.6.9 exige proteccion frente al software malicioso en todos los sistemas y cir.12.2 reglas para el manejo de activos; NIS2 no tiene un requisito dedicado a los dispositivos de usuario. El cifrado de portatiles, el borrado remoto y las condiciones BYOD tendrian que argumentarse bajo los requisitos generales de manejo de activos y seguridad de red."),
 close=("Evidence anti-malware on every endpoint for cir.6.9 and cite the endpoint policy as the asset-handling rules of cir.12.2.",
        "Evidenciar el antimalware en todos los dispositivos para cir.6.9 y citar la politica de dispositivos como las reglas de manejo de activos de cir.12.2.")),
"8.4": dict(
 covers=("Access to source code, tools and libraries restricted by role, logged, with change control on the repository.",
         "Acceso al codigo fuente, herramientas y bibliotecas restringido por rol, registrado, con control de cambios en el repositorio."),
 adds=("cir.6.2 requires a secure development lifecycle: security requirements, secure engineering, testing, separation of environments, review; protecting the source code repository is not listed among its elements, so it is evidenced through the general access control of cir.11.",
       "cir.6.2 exige un ciclo de vida de desarrollo seguro: requisitos de seguridad, ingenieria segura, pruebas, separacion de entornos, revision; proteger el repositorio de codigo no figura entre sus elementos, asi que se evidencia mediante el control de acceso general de cir.11."),
 close=("Include the repository in the access-rights review of cir.11.2.",
        "Incluir el repositorio en la revision de derechos de acceso de cir.11.2.")),
"8.6": dict(
 covers=("Capacity of systems, storage, network and people monitored and planned against current and projected demand.",
         "Capacidad de sistemas, almacenamiento, red y personas supervisada y planificada frente a la demanda actual y prevista."),
 adds=("cir.6.3 is configuration management (baselines, documented and reviewed configurations). NIS2 touches capacity only through business continuity and, in cir.6.7, through network security; there is no capacity management requirement.",
       "cir.6.3 es gestion de la configuracion (lineas base, configuraciones documentadas y revisadas). NIS2 toca la capacidad solo a traves de la continuidad de negocio y, en cir.6.7, de la seguridad de red; no hay un requisito de gestion de capacidad."),
 close=("Nothing more for NIS2; the ISO control is an extra.",
        "Nada mas para NIS2; el control ISO es un extra.")),
"8.10": dict(
 covers=("Information deleted from systems, devices and media when no longer required, by approved methods, including with suppliers, with records.",
         "Informacion borrada de sistemas, dispositivos y soportes cuando ya no se necesita, por metodos aprobados, incluidos los proveedores, con registro."),
 adds=("cir.12.5 requires deletion only in one situation: assets returned when personnel leave. Deleting information at end of retention, in general, is not a NIS2 requirement.",
       "cir.12.5 exige el borrado solo en una situacion: los activos devueltos cuando el personal se va. Borrar la informacion al fin de su retencion, en general, no es un requisito NIS2."),
 close=("Evidence the leaver deletion; the retention-driven deletion is ISO only.",
        "Evidenciar el borrado en las bajas; el borrado por fin de retencion es solo ISO.")),
"8.12": dict(
 covers=("Data-leakage prevention on endpoints, e-mail, web and cloud, driven by the classification, with monitoring and blocking.",
         "Prevencion de fugas de datos en puestos, correo, web y nube, guiada por la clasificacion, con monitorizacion y bloqueo."),
 adds=("cir.6.7 requires network security measures (segmentation, filtering, secured remote access, monitoring); leakage prevention is not named. NIS2 does not ask for DLP.",
       "cir.6.7 exige medidas de seguridad de red (segmentacion, filtrado, acceso remoto protegido, monitorizacion); la prevencion de fugas no se nombra. NIS2 no pide DLP."),
 close=("Nothing more for NIS2.",
        "Nada mas para NIS2.")),
"8.17": dict(
 covers=("All system clocks synchronised to an approved time source so that logs can be correlated.",
         "Todos los relojes de los sistemas sincronizados con una fuente de tiempo aprobada para poder correlacionar los registros."),
 adds=("cir.3.2 requires logs that allow investigation and correlation; synchronised clocks are the obvious enabler but are not stated. The ISO control makes explicit what NIS2 assumes.",
       "cir.3.2 exige registros que permitan investigar y correlacionar; los relojes sincronizados son el habilitador obvio pero no se enuncian. El control ISO hace explicito lo que NIS2 da por supuesto."),
 close=("Mention time synchronisation in the logging procedure as the basis for correlation.",
        "Mencionar la sincronizacion horaria en el procedimiento de registro como base de la correlacion.")),
"8.18": dict(
 covers=("Privileged utilities inventoried, restricted to authorised users, logged and removed where unnecessary.",
         "Utilidades privilegiadas inventariadas, restringidas a usuarios autorizados, registradas y eliminadas cuando no son necesarias."),
 adds=("cir.11.3 manages privileged accounts (separate accounts, restricted, logged, reviewed) and cir.11.4 dedicated administration systems; restricting which tools those accounts may run is not addressed.",
       "cir.11.3 gestiona las cuentas privilegiadas (cuentas separadas, restringidas, registradas, revisadas) y cir.11.4 sistemas dedicados de administracion; restringir que herramientas pueden ejecutar esas cuentas no se trata."),
 close=("Cite the privileged-account controls of cir.11.3 and list the utilities in the admin-system baseline.",
        "Citar los controles de cuentas privilegiadas de cir.11.3 y listar las utilidades en la linea base de los sistemas de administracion.")),
"8.19": dict(
 covers=("Software installed on operational systems only through a controlled process: approved sources, authorisation, testing, rollback, inventory.",
         "Software instalado en sistemas en produccion solo mediante un proceso controlado: fuentes aprobadas, autorizacion, pruebas, marcha atras, inventario."),
 adds=("cir.6.9 requires protection against malicious and unauthorised software; controlling installation is one way to achieve it, alongside anti-malware and allow-listing, but it is not required as a separate control. Change management (cir.6.4) covers the procedural part.",
       "cir.6.9 exige proteccion frente al software malicioso y no autorizado; controlar la instalacion es una forma de lograrlo, junto al antimalware y las listas de permitidos, pero no se exige como control aparte. La gestion de cambios (cir.6.4) cubre la parte procedimental."),
 close=("Evidence application allow-listing or restricted install rights as the cir.6.9 measure against unauthorised software.",
        "Evidenciar listas de aplicaciones permitidas o derechos de instalacion restringidos como medida de cir.6.9 frente al software no autorizado.")),
"8.23": dict(
 covers=("Web access filtered by category and reputation, with blocking of malicious and inappropriate sites and user rules.",
         "Acceso web filtrado por categoria y reputacion, con bloqueo de sitios maliciosos e inapropiados y reglas para los usuarios."),
 adds=("cir.6.7 asks for network security in general — segmentation, filtering of traffic, protection of connections; filtering outgoing web traffic is a reasonable part of it but is not named.",
       "cir.6.7 pide seguridad de red en general — segmentacion, filtrado de trafico, proteccion de conexiones; filtrar el trafico web saliente es una parte razonable pero no se nombra."),
 close=("Cite the web filter as one of the network security measures of cir.6.7.",
        "Citar el filtro web como una de las medidas de seguridad de red de cir.6.7.")),
"8.26": dict(
 covers=("Security requirements identified, specified and approved for applications, whether developed or acquired: authentication, data protection, logging, input validation.",
         "Requisitos de seguridad identificados, especificados y aprobados para las aplicaciones, desarrolladas o adquiridas: autenticacion, proteccion de datos, registro, validacion de entradas."),
 adds=("cir.6.2 puts security requirements at the start of the development lifecycle for in-house systems, with rules for secure engineering and testing; for acquired applications the requirement sits in cir.6.1 (security requirements in procurement) and is less detailed. The ISO control unifies both cases.",
       "cir.6.2 situa los requisitos de seguridad al inicio del ciclo de vida de desarrollo de sistemas propios, con reglas de ingenieria segura y pruebas; para las aplicaciones adquiridas el requisito esta en cir.6.1 (requisitos de seguridad en la adquisicion) y es menos detallado. El control ISO unifica ambos casos."),
 close=("Use the same requirements checklist for builds (cir.6.2) and purchases (cir.6.1) and keep it as evidence in both.",
        "Usar la misma lista de requisitos para desarrollos (cir.6.2) y compras (cir.6.1) y conservarla como evidencia en ambos casos.")),
"8.27": dict(
 covers=("Documented secure architecture and engineering principles — defence in depth, least privilege, fail secure, zero trust where applicable — applied to every design.",
         "Principios documentados de arquitectura e ingenieria segura — defensa en profundidad, minimo privilegio, fallo seguro, confianza cero cuando aplique — aplicados a todo diseno."),
 adds=("cir.6.2 mentions secure engineering practices as part of the lifecycle without asking for a documented set of principles; the ISO control formalises what NIS2 only names.",
       "cir.6.2 menciona practicas de ingenieria segura como parte del ciclo de vida sin pedir un conjunto documentado de principios; el control ISO formaliza lo que NIS2 solo nombra."),
 close=("Reference the principles document from the secure development policy cir.6.2 wants.",
        "Referenciar el documento de principios desde la politica de desarrollo seguro que quiere cir.6.2.")),
"8.28": dict(
 covers=("Secure coding rules per language, tooling and training, applied to in-house, outsourced and open-source code.",
         "Reglas de codificacion segura por lenguaje, herramientas y formacion, aplicadas al codigo propio, externalizado y de codigo abierto."),
 adds=("cir.6.2 asks for secure coding practices within the lifecycle but does not define them; ISO expects concrete rules and their verification.",
       "cir.6.2 pide practicas de codificacion segura dentro del ciclo de vida pero no las define; ISO espera reglas concretas y su verificacion."),
 close=("Cite the coding standard and the static analysis results as the evidence of cir.6.2's secure coding practices.",
        "Citar la norma de codificacion y los resultados del analisis estatico como evidencia de las practicas de codificacion segura de cir.6.2.")),
"8.30": dict(
 covers=("Outsourced development directed and reviewed: requirements, licensing, testing, evidence of secure practices, right to audit.",
         "Desarrollo externalizado dirigido y revisado: requisitos, licencias, pruebas, evidencia de practicas seguras, derecho de auditoria."),
 adds=("cir.6.2 applies the secure development lifecycle to whoever develops and cir.5.1 the supply-chain policy to the developer as a supplier; but NIS2 does not require supervising the external developer's process specifically. It is the combination that covers it, and the audit of the developer is not demanded.",
       "cir.6.2 aplica el ciclo de vida de desarrollo seguro a quien desarrolle y cir.5.1 la politica de cadena de suministro al desarrollador como proveedor; pero NIS2 no exige supervisar especificamente el proceso del desarrollador externo. Es la combinacion la que lo cubre, y la auditoria del desarrollador no se exige."),
 close=("Put the cir.6.2 lifecycle requirements in the development contract and keep the supplier in the cir.5.2 directory.",
        "Incluir los requisitos del ciclo de vida de cir.6.2 en el contrato de desarrollo y mantener al proveedor en el directorio de cir.5.2.")),
"8.31": dict(
 covers=("Development, test and production separated, with different credentials, controlled promotion and no production data in test.",
         "Desarrollo, pruebas y produccion separados, con credenciales distintas, promocion controlada y sin datos de produccion en pruebas."),
 adds=("cir.6.2 requires secure development and testing environments; that they must be separated from production is implied by 'secure' but not stated. The ISO control makes the separation explicit.",
       "cir.6.2 exige entornos de desarrollo y prueba seguros; que deban estar separados de produccion se implica en 'seguros' pero no se enuncia. El control ISO hace explicita la separacion."),
 close=("Document the environment separation as the way the cir.6.2 environments are made secure.",
        "Documentar la separacion de entornos como la forma en que se hacen seguros los entornos de cir.6.2.")),
"8.33": dict(
 covers=("Test data selected, masked or anonymised, protected, authorised when copied from production, deleted after use.",
         "Datos de prueba seleccionados, enmascarados o anonimizados, protegidos, autorizados cuando se copian de produccion, borrados tras su uso."),
 adds=("cir.6.5 requires security testing procedures, their scope and frequency, and remediation of findings; the protection of the data used in those tests is not mentioned.",
       "cir.6.5 exige procedimientos de pruebas de seguridad, su alcance y frecuencia, y la remediacion de los hallazgos; la proteccion de los datos usados en esas pruebas no se menciona."),
 close=("Nothing more for NIS2; the ISO control is an extra.",
        "Nada mas para NIS2; el control ISO es un extra.")),
"8.34": dict(
 covers=("Audit tests on production agreed and controlled: scope, read-only access, timing, tools, data protected.",
         "Pruebas de auditoria sobre produccion acordadas y controladas: alcance, acceso de solo lectura, momento, herramientas, datos protegidos."),
 adds=("cir.2.3 requires an independent review of the risk management measures by people with adequate expertise, with results reported to the management body; how the review's own tests are kept from disturbing production is not addressed.",
       "cir.2.3 exige una revision independiente de las medidas de gestion de riesgos por personas con competencia adecuada, con resultados reportados al organo de direccion; como se evita que las propias pruebas de la revision perturben produccion no se trata."),
 close=("Include the test-protection rules in the terms of the independent review cir.2.3 requires.",
        "Incluir las reglas de proteccion de las pruebas en las condiciones de la revision independiente que exige cir.2.3.")),
}
