D = {
"5.2": dict(
 covers=("Security responsibilities assigned to named roles and communicated across the organisation.",
         "Responsabilidades de seguridad asignadas a roles concretos y comunicadas a toda la organizacion."),
 adds=("Req. 12.1.3 wants the policy to define roles and responsibilities for information security and to have them formally acknowledged; and each of the twelve requirements repeats, in its x.1.2, that the roles for that requirement's activities are documented, assigned and understood. An assessor expects to see the assignment per requirement area, typically as a responsibility matrix, and evidence that the people know it.",
       "El req. 12.1.3 quiere que la politica defina roles y responsabilidades de seguridad y que se reconozcan formalmente; y cada uno de los doce requisitos repite, en su x.1.2, que los roles para las actividades de ese requisito estan documentados, asignados y se comprenden. Un evaluador espera ver la asignacion por area de requisito, normalmente como una matriz de responsabilidades, y evidencia de que las personas la conocen."),
 close=("Build a responsibility matrix with one row per PCI requirement and collect signed acknowledgements from the owners.",
        "Construir una matriz de responsabilidades con una fila por requisito PCI y recoger reconocimientos firmados de los responsables.")),
"5.3": dict(
 covers=("Conflicting duties separated so that no one person can request, approve and execute a sensitive action.",
         "Funciones en conflicto separadas para que ninguna persona pueda solicitar, aprobar y ejecutar una accion sensible."),
 adds=("Req. 6.5.3 requires pre-production and production environments to be separated and 6.5.4 the roles and functions between them to be separated, so that only authorised personnel deploy changes to production; PCI does not ask for a general segregation-of-duties analysis. Small entities may compensate with detective controls where the same person must do both.",
       "El req. 6.5.3 exige separar los entornos de preproduccion y produccion y el 6.5.4 separar los roles y funciones entre ellos, de modo que solo personal autorizado despliegue cambios en produccion; PCI no pide un analisis general de segregacion de funciones. Las entidades pequenas pueden compensar con controles detectivos cuando la misma persona deba hacer ambas cosas."),
 close=("Evidence that developers cannot deploy to production, or document the compensating control if they can.",
        "Evidenciar que los desarrolladores no pueden desplegar en produccion, o documentar el control compensatorio si pueden.")),
"5.4": dict(
 covers=("Management visibly requires and supports the application of security by all personnel.",
         "La direccion exige y respalda de forma visible que todo el personal aplique la seguridad."),
 adds=("Req. 12.4 requires executive management to establish responsibility for the protection of cardholder data and a PCI DSS compliance programme, with a charter and communication to executives; for service providers, 12.4.2 adds documented reviews at least every three months confirming that personnel perform their tasks per the policies. General support for security does not create the programme or the quarterly review.",
       "El req. 12.4 exige que la alta direccion establezca la responsabilidad sobre la proteccion de los datos de tarjeta y un programa de cumplimiento PCI DSS, con un mandato y comunicacion a los directivos; para los proveedores de servicios, el 12.4.2 anade revisiones documentadas al menos cada tres meses que confirmen que el personal realiza sus tareas segun las politicas. El respaldo general a la seguridad no crea el programa ni la revision trimestral."),
 close=("Issue a PCI compliance charter signed by executive management and, if a service provider, schedule the quarterly reviews.",
        "Emitir un mandato de cumplimiento PCI firmado por la alta direccion y, si es proveedor de servicios, programar las revisiones trimestrales.")),
"5.5": dict(
 covers=("Authorities identified, contact persons named, circumstances of contact defined.",
         "Autoridades identificadas, personas de contacto designadas, circunstancias del contacto definidas."),
 adds=("Req. 12.10.1 requires the incident response plan to include roles and contacts, notification of the payment brands and acquirers at a minimum, the legal requirements for reporting compromises, and reference to the brands' incident procedures (which may impose a PFI investigation). ISO wants to know whom to call; PCI wants the call written into the plan, with the brands' procedures.",
       "El req. 12.10.1 exige que el plan de respuesta a incidentes incluya roles y contactos, la notificacion como minimo a las marcas de tarjetas y a los adquirentes, los requisitos legales de reporte de compromisos y la referencia a los procedimientos de incidentes de las marcas (que pueden imponer una investigacion PFI). ISO quiere saber a quien llamar; PCI quiere la llamada escrita en el plan, con los procedimientos de las marcas."),
 close=("Add the acquirer and brand notification step, with contact data and the brands' compromise procedures, to the incident plan.",
        "Anadir al plan de incidentes el paso de notificacion al adquirente y a las marcas, con datos de contacto y los procedimientos de compromiso de las marcas.")),
"5.6": dict(
 covers=("Membership of professional bodies and forums keeps the organisation informed about threats and practice.",
         "La pertenencia a asociaciones profesionales y foros mantiene a la organizacion informada de amenazas y practicas."),
 adds=("Req. 6.3.1 requires vulnerabilities to be identified using industry-recognised sources (vendor advisories, CERTs, the NVD) and ranked by risk; the contact with groups is a means to that end, and the assessor will look for the sources actually monitored and the ranking, not the memberships.",
       "El req. 6.3.1 exige identificar las vulnerabilidades usando fuentes reconocidas del sector (avisos de fabricantes, CERT, la NVD) y clasificarlas por riesgo; el contacto con grupos es un medio para ese fin, y el evaluador buscara las fuentes realmente monitorizadas y la clasificacion, no las afiliaciones."),
 close=("Document the list of vulnerability sources monitored and the risk-ranking rule.",
        "Documentar la lista de fuentes de vulnerabilidades monitorizadas y la regla de clasificacion por riesgo.")),
"5.7": dict(
 covers=("Threat information collected, analysed and used to adjust controls.",
         "Informacion sobre amenazas recogida, analizada y usada para ajustar los controles."),
 adds=("Req. 6.3.1 is narrower — vulnerability intelligence from recognised sources with a risk ranking (critical, high, medium) — and PCI has no requirement for broader threat intelligence. In the other direction, 6.3.1 must include vulnerabilities in bespoke and third-party software, which a generic threat process may not cover.",
       "El req. 6.3.1 es mas estrecho — inteligencia de vulnerabilidades de fuentes reconocidas con una clasificacion por riesgo (critico, alto, medio) — y PCI no tiene requisito de inteligencia de amenazas mas amplia. En la otra direccion, el 6.3.1 debe incluir las vulnerabilidades del software a medida y de terceros, algo que un proceso generico de amenazas puede no cubrir."),
 close=("Make sure the threat process ranks vulnerabilities per 6.3.1 and includes bespoke and third-party components.",
        "Asegurarse de que el proceso de amenazas clasifica las vulnerabilidades segun el 6.3.1 e incluye los componentes a medida y de terceros.")),
"5.9": dict(
 covers=("An inventory of information and associated assets with an owner for each.",
         "Un inventario de la informacion y los activos asociados con un propietario para cada uno."),
 adds=("Req. 12.5.1 requires an inventory of the system components in scope for PCI DSS with a description of function, and 12.5.2 a documented confirmation of scope at least every 12 months (every six for service providers) and after significant change, covering data flows, locations of account data, segmentation and connected third parties. A general asset inventory does not establish or validate the CDE scope.",
       "El req. 12.5.1 exige un inventario de los componentes del sistema en alcance de PCI DSS con la descripcion de su funcion, y el 12.5.2 una confirmacion documentada del alcance al menos cada 12 meses (cada seis para proveedores de servicios) y tras cambios significativos, que cubra flujos de datos, ubicaciones de los datos de cuenta, segmentacion y terceros conectados. Un inventario general de activos no establece ni valida el alcance del CDE."),
 close=("Tag in-scope components in the inventory and run the annual scoping exercise with data-flow diagrams and a signed scope statement.",
        "Marcar en el inventario los componentes en alcance y realizar el ejercicio anual de alcance con diagramas de flujo de datos y una declaracion de alcance firmada.")),
"5.12": dict(
 covers=("Information classified by confidentiality, integrity and availability needs.",
         "Informacion clasificada segun sus necesidades de confidencialidad, integridad y disponibilidad."),
 adds=("Req. 9.4.1 requires all media with cardholder data to be classified according to the sensitivity of the data; that is the only classification PCI asks for, and it applies to one class of data. The ISO scheme must simply make sure cardholder data lands at the level that triggers the PCI handling rules.",
       "El req. 9.4.1 exige clasificar todos los soportes con datos de tarjeta segun la sensibilidad de los datos; es la unica clasificacion que pide PCI, y se aplica a una clase de datos. El esquema ISO simplemente debe asegurar que los datos de tarjeta caen en el nivel que dispara las reglas de manejo PCI."),
 close=("State explicitly in the classification scheme which level cardholder data belongs to and which PCI rules follow.",
        "Indicar explicitamente en el esquema de clasificacion a que nivel pertenecen los datos de tarjeta y que reglas PCI se derivan.")),
"5.14": dict(
 covers=("Rules and agreements for every transfer channel, with encryption and non-repudiation where needed.",
         "Reglas y acuerdos para cada canal de transferencia, con cifrado y no repudio cuando haga falta."),
 adds=("Req. 4.2.1 requires strong cryptography and secure protocols whenever PAN is transmitted over open, public networks, with an inventory of trusted keys and certificates, and 4.2.2 forbids sending PAN by end-user messaging unless encrypted; 9.4.3 and 9.4.4 require media sent outside to be logged, sent by trackable means and approved by management. ISO covers every transfer at policy level; PCI prescribes the mechanism for one kind of data.",
       "El req. 4.2.1 exige criptografia robusta y protocolos seguros siempre que se transmita el PAN por redes publicas abiertas, con un inventario de claves y certificados de confianza, y el 4.2.2 prohibe enviar el PAN por mensajeria de usuario salvo cifrado; el 9.4.3 y el 9.4.4 exigen que los soportes enviados fuera se registren, se envien por medios rastreables y los apruebe la direccion. ISO cubre toda transferencia a nivel de politica; PCI prescribe el mecanismo para un tipo de datos."),
 close=("Add PAN-specific rules to the transfer policy (TLS versions, certificate inventory, no PAN in e-mail or chat, media shipment log).",
        "Anadir a la politica de transferencia reglas especificas para el PAN (versiones TLS, inventario de certificados, sin PAN en correo o chat, registro de envios de soportes).")),
"5.17": dict(
 covers=("Authentication secrets allocated, protected and changed through a controlled process.",
         "Secretos de autenticacion asignados, protegidos y cambiados mediante un proceso controlado."),
 adds=("Req. 8.3 fixes the parameters: passwords of at least 12 characters with letters and numbers, no reuse of the last four, lockout after 10 failed attempts for at least 30 minutes, 15-minute idle timeout, a change every 90 days or continuous dynamic analysis of the account's posture, first-use passwords unique and changed at first login, secrets stored and transmitted only with strong cryptography. Req. 8.6 governs application and system accounts: no interactive use unless justified, no hard-coded secrets in scripts, periodic change based on a targeted risk analysis. ISO leaves every parameter to the organisation.",
       "El req. 8.3 fija los parametros: contrasenas de al menos 12 caracteres con letras y numeros, sin reutilizar las cuatro ultimas, bloqueo tras 10 intentos fallidos durante al menos 30 minutos, cierre de sesion a los 15 minutos de inactividad, cambio cada 90 dias o analisis dinamico continuo del estado de la cuenta, contrasenas iniciales unicas y cambiadas en el primer acceso, secretos almacenados y transmitidos solo con criptografia robusta. El req. 8.6 rige las cuentas de aplicacion y de sistema: sin uso interactivo salvo justificacion, sin secretos incrustados en scripts, cambio periodico basado en un analisis de riesgo dirigido. ISO deja cada parametro a la organizacion."),
 close=("Set the password and lockout policy to the 8.3 values in the directory and inventory system accounts with their secret-rotation rule.",
        "Configurar la politica de contrasenas y bloqueo con los valores del 8.3 en el directorio e inventariar las cuentas de sistema con su regla de rotacion de secretos.")),
"5.18": dict(
 covers=("Access rights provisioned, reviewed, modified and revoked per the access control policy.",
         "Derechos de acceso concedidos, revisados, modificados y revocados segun la politica de control de acceso."),
 adds=("Req. 7.2.4 requires all user accounts and their privileges to be reviewed at least once every six months, with inappropriate access remediated and management acknowledging the result; 7.2.5 requires the same for application and system accounts on a frequency set by a targeted risk analysis; 7.3 requires an access control system that restricts by need-to-know and denies by default. ISO reviews at 'regular intervals' and does not prescribe the default-deny mechanism.",
       "El req. 7.2.4 exige revisar todas las cuentas de usuario y sus privilegios al menos cada seis meses, remediando los accesos inadecuados y con la direccion reconociendo el resultado; el 7.2.5 exige lo mismo para las cuentas de aplicacion y de sistema con una frecuencia fijada por un analisis de riesgo dirigido; el 7.3 exige un sistema de control de acceso que restrinja por necesidad de conocer y deniegue por defecto. ISO revisa a 'intervalos regulares' y no prescribe el mecanismo de denegacion por defecto."),
 close=("Fix the access review at six months for the CDE, evidence management sign-off, and verify default-deny in the access control system.",
        "Fijar la revision de accesos en seis meses para el CDE, evidenciar la aprobacion de la direccion y verificar la denegacion por defecto en el sistema de control de acceso.")),
"5.19": dict(
 covers=("A supplier security process: risk-based selection, requirements, monitoring, termination.",
         "Un proceso de seguridad de proveedores: seleccion basada en riesgo, requisitos, seguimiento, terminacion."),
 adds=("Req. 12.8 requires a list of all third-party service providers (TPSPs) with which account data is shared or that could affect its security, with a description of each service (12.8.1); written agreements with the TPSP's acknowledgement of responsibility (12.8.2); a due-diligence process before engagement (12.8.3); monitoring of each TPSP's PCI DSS compliance status at least every 12 months (12.8.4); and a matrix of which PCI requirements are managed by the TPSP, by the entity, or shared (12.8.5). None of these five artefacts is produced by a generic supplier process.",
       "El req. 12.8 exige una lista de todos los proveedores de servicios (TPSP) con los que se comparten datos de cuenta o que puedan afectar a su seguridad, con la descripcion de cada servicio (12.8.1); acuerdos escritos con el reconocimiento de responsabilidad del TPSP (12.8.2); un proceso de diligencia debida antes de contratar (12.8.3); seguimiento del estado de cumplimiento PCI DSS de cada TPSP al menos cada 12 meses (12.8.4); y una matriz de que requisitos PCI gestiona el TPSP, cuales la entidad y cuales son compartidos (12.8.5). Ninguno de esos cinco artefactos lo produce un proceso generico de proveedores."),
 close=("Create the TPSP list, collect each provider's AOC yearly and maintain the responsibility matrix per provider.",
        "Crear la lista de TPSP, recoger anualmente el AOC de cada proveedor y mantener la matriz de responsabilidades por proveedor.")),
"5.21": dict(
 covers=("Risks in the ICT supply chain identified and managed beyond the direct supplier.",
         "Riesgos de la cadena de suministro TIC identificados y gestionados mas alla del proveedor directo."),
 adds=("Req. 12.8 reaches only the TPSPs that handle account data or can affect its security, and 6.3.2 asks for an inventory of bespoke and custom software and of the third-party components it uses, so that vulnerabilities in those components are managed. PCI does not look at the supplier's own suppliers or at hardware provenance; ISO's supply-chain control is wider, PCI's software-component inventory is more specific.",
       "El req. 12.8 alcanza solo a los TPSP que manejan datos de cuenta o pueden afectar a su seguridad, y el 6.3.2 pide un inventario del software a medida y de los componentes de terceros que usa, para gestionar las vulnerabilidades de esos componentes. PCI no mira a los proveedores del proveedor ni a la procedencia del hardware; el control de cadena de suministro de ISO es mas amplio, el inventario de componentes de PCI es mas concreto."),
 close=("Maintain a software bill of materials for bespoke applications in the CDE and tie it to vulnerability monitoring.",
        "Mantener una lista de materiales de software (SBOM) de las aplicaciones a medida del CDE y ligarla a la monitorizacion de vulnerabilidades.")),
"5.23": dict(
 covers=("A cloud policy on the customer side: risk assessment, shared responsibilities, data location, exit.",
         "Una politica de nube del lado del cliente: evaluacion de riesgos, responsabilidades compartidas, ubicacion de datos, salida."),
 adds=("Req. 12.8 treats the cloud provider as a TPSP (list, agreement, due diligence, annual compliance status, responsibility matrix); 12.9 obliges the provider itself to acknowledge its responsibilities in writing and to give customers, on request, its compliance status and the matrix; multi-tenant providers must also meet Appendix A1 (logical separation, customer access to logs, penetration tests of the separation at least every six months). The customer policy is one side; PCI binds both.",
       "El req. 12.8 trata al proveedor de nube como un TPSP (lista, acuerdo, diligencia debida, estado de cumplimiento anual, matriz de responsabilidades); el 12.9 obliga al propio proveedor a reconocer por escrito sus responsabilidades y a dar a los clientes, a peticion, su estado de cumplimiento y la matriz; los proveedores multiinquilino deben cumplir ademas el Apendice A1 (separacion logica, acceso del cliente a los registros, pruebas de penetracion de la separacion al menos cada seis meses). La politica del cliente es un lado; PCI vincula a ambos."),
 close=("Obtain the provider's AOC and responsibility matrix and file them with the cloud risk assessment.",
        "Obtener el AOC y la matriz de responsabilidades del proveedor y archivarlos con la evaluacion de riesgos de la nube.")),
"5.25": dict(
 covers=("Security events assessed and classified, with a decision on whether they are incidents and their priority.",
         "Eventos de seguridad evaluados y clasificados, con una decision sobre si son incidentes y su prioridad."),
 adds=("Req. 12.10.5 requires the incident plan to include monitoring and responding to alerts from specific systems: intrusion detection and prevention, network security controls, file integrity monitoring, change-detection on payment pages, and unauthorised wireless access points; 10.7 requires failures of critical security control systems (firewalls, IDS, FIM, anti-malware, logging, segmentation controls) to be detected, alerted, and handled through a defined restoration and root-cause process. ISO's assessment step does not name the sources or the control-failure case.",
       "El req. 12.10.5 exige que el plan de incidentes incluya la monitorizacion y respuesta a las alertas de sistemas concretos: deteccion y prevencion de intrusiones, controles de seguridad de red, monitorizacion de integridad de ficheros, deteccion de cambios en las paginas de pago y puntos de acceso inalambrico no autorizados; el 10.7 exige que los fallos de los sistemas de control criticos (cortafuegos, IDS, FIM, antimalware, registro, controles de segmentacion) se detecten, alerten y traten con un proceso definido de restauracion y causa raiz. El paso de evaluacion de ISO no nombra las fuentes ni el caso de fallo de control."),
 close=("List the 12.10.5 alert sources in the incident plan and write the control-failure procedure of 10.7 with its evidence.",
        "Listar en el plan de incidentes las fuentes de alerta del 12.10.5 y redactar el procedimiento de fallo de control del 10.7 con su evidencia.")),
"5.28": dict(
 covers=("Evidence identified, collected and preserved with chain of custody so that it is admissible.",
         "Evidencias identificadas, recogidas y preservadas con cadena de custodia para que sean admisibles."),
 adds=("Req. 10.5.1 requires audit logs to be retained for at least 12 months with the last three immediately available, and 12.10.1 requires the incident plan to cover the analysis of legal requirements and, through the brands' procedures, a forensic investigation by a PFI when the brands demand it. PCI secures the raw material and the external investigator; the entity's own forensic procedure is not a requirement.",
       "El req. 10.5.1 exige conservar los registros de auditoria al menos 12 meses con los tres ultimos disponibles de inmediato, y el 12.10.1 exige que el plan de incidentes cubra el analisis de los requisitos legales y, mediante los procedimientos de las marcas, una investigacion forense por un PFI cuando las marcas lo exijan. PCI asegura la materia prima y el investigador externo; el procedimiento forense propio de la entidad no es un requisito."),
 close=("Set log retention to 12 months (3 online) and add 'preserve systems for PFI' to the incident plan.",
        "Fijar la conservacion de registros en 12 meses (3 en linea) y anadir 'preservar los sistemas para el PFI' al plan de incidentes.")),
"5.29": dict(
 covers=("Plans to keep security at the required level during a disruption.",
         "Planes para mantener la seguridad al nivel requerido durante una interrupcion."),
 adds=("Req. 12.10.1 asks the incident response plan to include business recovery and continuity procedures and data backup processes; that is the whole of PCI's continuity interest. It does not ask how security is maintained during the disruption.",
       "El req. 12.10.1 pide que el plan de respuesta a incidentes incluya procedimientos de recuperacion y continuidad del negocio y procesos de copia de datos; ese es todo el interes de PCI en la continuidad. No pregunta como se mantiene la seguridad durante la interrupcion."),
 close=("Reference the continuity procedures from the incident plan; nothing more is needed for PCI.",
        "Referenciar los procedimientos de continuidad desde el plan de incidentes; no hace falta mas para PCI.")),
"5.30": dict(
 covers=("ICT continuity planned, implemented and tested against business continuity objectives.",
         "Continuidad TIC planificada, implantada y probada conforme a los objetivos de continuidad de negocio."),
 adds=("Req. 12.10.1 only mentions recovery and continuity inside the incident plan; RTO/RPO, alternate sites and continuity tests are not PCI requirements. The ISO control exceeds PCI here.",
       "El req. 12.10.1 solo menciona la recuperacion y la continuidad dentro del plan de incidentes; RTO/RPO, sedes alternativas y pruebas de continuidad no son requisitos PCI. El control ISO supera aqui a PCI."),
 close=("Nothing more for PCI.",
        "Nada mas para PCI.")),
"5.31": dict(
 covers=("Legal, regulatory and contractual requirements identified, documented and owned.",
         "Requisitos legales, reglamentarios y contractuales identificados, documentados y con responsable."),
 adds=("Req. 12.4 makes PCI DSS compliance a managed programme with executive accountability and 12.5 a validated scope; beyond the standard, the entity must validate annually to its acquirer (SAQ or ROC plus AOC) and, depending on level, quarterly ASV scans. Identifying PCI DSS as an applicable contractual requirement is the first line of the inventory; the programme, the scope validation and the annual attestation are the obligation.",
       "El req. 12.4 hace del cumplimiento PCI DSS un programa gestionado con responsabilidad ejecutiva y el 12.5 un alcance validado; mas alla de la norma, la entidad debe validar anualmente ante su adquirente (SAQ o ROC mas AOC) y, segun el nivel, analisis ASV trimestrales. Identificar PCI DSS como requisito contractual aplicable es la primera linea del inventario; el programa, la validacion del alcance y la atestacion anual son la obligacion."),
 close=("Determine the merchant or service-provider level and the applicable SAQ type, and calendar the annual validation.",
        "Determinar el nivel de comerciante o proveedor de servicios y el tipo de SAQ aplicable, y calendarizar la validacion anual.")),
"5.33": dict(
 covers=("Records protected against loss, tampering and unauthorised access for their retention period.",
         "Registros protegidos frente a perdida, manipulacion y acceso no autorizado durante su periodo de conservacion."),
 adds=("Req. 10.5.1 fixes audit log retention at 12 months, three immediately available for analysis; 3.2.1 requires a data retention and disposal policy that limits storage of account data to what is needed for legal, regulatory or business reasons, defines retention periods and includes a process to identify and securely delete data beyond retention at least every three months. ISO protects records without setting periods and without a minimisation duty.",
       "El req. 10.5.1 fija la conservacion de los registros de auditoria en 12 meses, tres disponibles de inmediato para analisis; el 3.2.1 exige una politica de retencion y eliminacion de datos que limite el almacenamiento de datos de cuenta a lo necesario por razones legales, regulatorias o de negocio, defina los plazos e incluya un proceso para identificar y borrar de forma segura, al menos cada tres meses, los datos que superen la retencion. ISO protege los registros sin fijar plazos y sin un deber de minimizacion."),
 close=("Write the account-data retention policy with the quarterly deletion process and set log retention to 12 months.",
        "Redactar la politica de retencion de datos de cuenta con el proceso trimestral de borrado y fijar la conservacion de registros en 12 meses.")),
"5.35": dict(
 covers=("Periodic independent review of the security approach, reported to management.",
         "Revision independiente periodica del enfoque de seguridad, reportada a la direccion."),
 adds=("PCI validation is itself an annual independent assessment: a Report on Compliance by a QSA (or an ISA for some levels) or a Self-Assessment Questionnaire, plus an Attestation of Compliance to the acquirer; 12.4.2 adds quarterly reviews for service providers; and 11.3/11.4 require quarterly scans and annual penetration tests by qualified, organisationally independent parties. ISO's independent review has no fixed cycle, no external assessor requirement and no testing component.",
       "La validacion PCI es en si misma una evaluacion independiente anual: un Report on Compliance por un QSA (o un ISA en algunos niveles) o un cuestionario de autoevaluacion, mas una atestacion de cumplimiento al adquirente; el 12.4.2 anade revisiones trimestrales para proveedores de servicios; y los 11.3/11.4 exigen analisis trimestrales y pruebas de penetracion anuales por partes cualificadas e independientes de la organizacion. La revision independiente de ISO no tiene ciclo fijo, ni exige evaluador externo, ni componente de pruebas."),
 close=("Engage a QSA or complete the SAQ yearly, and schedule the ASV scans and the annual penetration test.",
        "Contratar un QSA o completar el SAQ anualmente, y programar los analisis ASV y la prueba de penetracion anual.")),
"5.36": dict(
 covers=("Managers regularly verify compliance with policies and standards and correct deviations.",
         "Los responsables verifican regularmente el cumplimiento de politicas y normas y corrigen las desviaciones."),
 adds=("Req. 12.4.2 requires service providers to perform reviews at least every three months confirming that personnel perform their tasks per the policies (daily log reviews, ruleset reviews, configuration standards applied, alerts responded to), with documented results, remediation and sign-off by the responsible executive. ISO leaves the frequency open and does not list what to verify.",
       "El req. 12.4.2 exige a los proveedores de servicios realizar revisiones al menos cada tres meses que confirmen que el personal realiza sus tareas segun las politicas (revisiones diarias de registros, revisiones de reglas, normas de configuracion aplicadas, alertas atendidas), con resultados documentados, remediacion y firma del directivo responsable. ISO deja la frecuencia abierta y no enumera que verificar."),
 close=("Set up the quarterly review checklist of 12.4.2 with executive sign-off (service providers).",
        "Establecer la lista de revision trimestral del 12.4.2 con firma del directivo (proveedores de servicios).")),
"5.37": dict(
 covers=("Operating procedures documented, current and available to those who need them.",
         "Procedimientos operativos documentados, actualizados y disponibles para quienes los necesitan."),
 adds=("Each of the twelve requirements opens with an x.1.1: all security policies and operational procedures identified in that requirement are documented, kept up to date, in use and known to all affected parties. The assessor tests it per requirement: a network procedure for Req. 1, a hardening standard for Req. 2, a key-management procedure for Req. 3, and so on. One general set of operating procedures meets the spirit but not the per-requirement evidence.",
       "Cada uno de los doce requisitos abre con un x.1.1: todas las politicas de seguridad y procedimientos operativos identificados en ese requisito estan documentados, actualizados, en uso y son conocidos por todas las partes afectadas. El evaluador lo prueba por requisito: un procedimiento de red para el req. 1, una norma de bastionado para el req. 2, un procedimiento de gestion de claves para el req. 3, y asi sucesivamente. Un conjunto general de procedimientos operativos cumple el espiritu pero no la evidencia por requisito."),
 close=("Build a document map with one row per PCI requirement pointing to the procedure that covers it, with review dates.",
        "Construir un mapa documental con una fila por requisito PCI que apunte al procedimiento que lo cubre, con fechas de revision.")),
"6.2": dict(
 covers=("Security responsibilities stated in the terms of employment.",
         "Responsabilidades de seguridad recogidas en las condiciones de empleo."),
 adds=("Req. 12.6.3 requires personnel to acknowledge, at least once every 12 months, that they have read and understood the information security policy and procedures; the acknowledgement must be renewed, whereas a contract clause is signed once. The terms of employment themselves are not a PCI subject.",
       "El req. 12.6.3 exige que el personal reconozca, al menos cada 12 meses, que ha leido y entendido la politica y los procedimientos de seguridad; el reconocimiento debe renovarse, mientras que una clausula contractual se firma una vez. Las condiciones de empleo en si no son un asunto PCI."),
 close=("Add an annual policy acknowledgement to the awareness cycle.",
        "Anadir un reconocimiento anual de la politica al ciclo de concienciacion.")),
"6.5": dict(
 covers=("Security duties surviving termination or change of role, communicated and enforced.",
         "Deberes de seguridad que perduran tras el cese o cambio de puesto, comunicados y exigidos."),
 adds=("Req. 8.2.5 requires access for terminated users to be revoked immediately, and 8.2.6 inactive accounts to be disabled within 90 days; the other post-employment duties (confidentiality, return of assets) are not PCI subjects.",
       "El req. 8.2.5 exige revocar de inmediato el acceso de los usuarios cesados, y el 8.2.6 desactivar las cuentas inactivas en 90 dias; los demas deberes posteriores al empleo (confidencialidad, devolucion de activos) no son asunto de PCI."),
 close=("Evidence same-day revocation for leavers with CDE access and the 90-day inactive-account sweep.",
        "Evidenciar la revocacion el mismo dia para las bajas con acceso al CDE y el barrido de cuentas inactivas a 90 dias.")),
"6.7": dict(
 covers=("A remote-working policy covering environment, device, connection, rules and support.",
         "Una politica de trabajo a distancia que cubre entorno, dispositivo, conexion, reglas y soporte."),
 adds=("Req. 8.4.3 requires MFA for all remote access from outside the entity's network, including by vendors, and 8.5 fixes how MFA is configured; 1.5.1 requires security controls (personal firewall or equivalent, not alterable by the user) on any device that connects to both untrusted networks and the CDE; 3.4.2 prevents copying PAN through remote-access technologies unless authorised. The home environment, ergonomics and support are not PCI subjects.",
       "El req. 8.4.3 exige MFA para todo acceso remoto desde fuera de la red de la entidad, incluido el de proveedores, y el 8.5 fija como se configura; el 1.5.1 exige controles de seguridad (cortafuegos personal o equivalente, no alterable por el usuario) en todo dispositivo que se conecte a redes no confiables y al CDE; el 3.4.2 impide copiar el PAN mediante tecnologias de acceso remoto salvo autorizacion. El entorno domestico, la ergonomia y el soporte no son asunto de PCI."),
 close=("Enforce MFA on every remote path into the CDE, lock the host firewall on remote devices and block clipboard/copy of PAN in remote sessions.",
        "Imponer MFA en toda via remota al CDE, bloquear el cortafuegos del equipo en los dispositivos remotos e impedir el portapapeles/copia del PAN en sesiones remotas.")),
"6.8": dict(
 covers=("A channel for anyone to report security events quickly.",
         "Un canal para que cualquiera notifique con rapidez los eventos de seguridad."),
 adds=("Req. 12.10.4 requires the incident response personnel to be trained, and 12.10.5 the plan to receive alerts from the monitoring systems; a reporting channel for all staff is not required, though 12.6 awareness training is expected to tell people how to report.",
       "El req. 12.10.4 exige formar al personal de respuesta a incidentes, y el 12.10.5 que el plan reciba las alertas de los sistemas de monitorizacion; un canal de notificacion para todo el personal no se exige, aunque se espera que la concienciacion del 12.6 explique como notificar."),
 close=("Mention the reporting channel in the awareness material as 12.6 evidence.",
        "Mencionar el canal de notificacion en el material de concienciacion como evidencia del 12.6.")),
"7.3": dict(
 covers=("Offices, rooms and facilities physically secured.",
         "Oficinas, salas e instalaciones protegidas fisicamente."),
 adds=("Req. 9.2.1.1 requires individual physical access to sensitive areas within the CDE to be monitored with video cameras or electronic access control (or both), the data reviewed and correlated with other entries, and retained for at least three months; 9.2.3 restricts access to consoles in sensitive areas. PCI only looks at the areas that store, process or transmit cardholder data, but there it is precise.",
       "El req. 9.2.1.1 exige monitorizar el acceso fisico individual a las areas sensibles del CDE con camaras de video o control de acceso electronico (o ambos), revisar los datos y correlacionarlos con otras entradas, y conservarlos al menos tres meses; el 9.2.3 restringe el acceso a las consolas en areas sensibles. PCI solo mira las areas que almacenan, procesan o transmiten datos de tarjeta, pero ahi es preciso."),
 close=("Define the sensitive areas, install camera or badge logging at their entry points and keep three months of records.",
        "Definir las areas sensibles, instalar registro por camara o tarjeta en sus puntos de entrada y conservar tres meses de registros.")),
"7.4": dict(
 covers=("Continuous physical monitoring of premises with alerts and review.",
         "Vigilancia fisica continua de las instalaciones con alertas y revision."),
 adds=("Req. 9.2.1.1 fixes the mechanism (video or electronic access control at entry and exit points of sensitive areas), the review and correlation of the data, its protection from tampering and a three-month retention; ISO's control covers all premises but sets no retention or correlation requirement.",
       "El req. 9.2.1.1 fija el mecanismo (video o control de acceso electronico en los puntos de entrada y salida de las areas sensibles), la revision y correlacion de los datos, su proteccion frente a manipulacion y una conservacion de tres meses; el control ISO cubre todas las instalaciones pero no fija retencion ni correlacion."),
 close=("Set camera retention to at least three months and document the review of access records.",
        "Fijar la retencion de las camaras en al menos tres meses y documentar la revision de los registros de acceso.")),
"7.6": dict(
 covers=("Rules of conduct inside secure areas.",
         "Reglas de conducta dentro de las areas seguras."),
 adds=("Req. 9.3 requires personnel access to sensitive areas to be authorised and based on job function, revoked on termination with badges returned, and visitors to be authorised, escorted, badged distinctly and logged in a register kept for three months; how people behave once inside is not a PCI subject.",
       "El req. 9.3 exige que el acceso del personal a las areas sensibles este autorizado y basado en la funcion, revocado al cesar con devolucion de las identificaciones, y que los visitantes esten autorizados, acompanados, identificados de forma distinguible y registrados en un libro conservado tres meses; como se comporta la gente una vez dentro no es asunto de PCI."),
 close=("Keep the visitor log with the 9.3 fields and a three-month retention.",
        "Llevar el registro de visitantes con los campos del 9.3 y una conservacion de tres meses.")),
"7.8": dict(
 covers=("Equipment sited to reduce environmental risk and unauthorised viewing or access.",
         "Equipos ubicados para reducir el riesgo ambiental y la visualizacion o el acceso no autorizados."),
 adds=("Req. 9.2.2 requires publicly accessible network jacks to be restricted or disabled, and 9.5 requires POI devices to be inventoried (make, model, location, serial), periodically inspected for tampering or substitution, and staff trained to spot it. General siting of servers or screens is not addressed.",
       "El req. 9.2.2 exige restringir o desactivar las tomas de red accesibles al publico, y el 9.5 exige inventariar los dispositivos POI (marca, modelo, ubicacion, numero de serie), inspeccionarlos periodicamente frente a manipulacion o sustitucion, y formar al personal para detectarlo. La ubicacion general de servidores o pantallas no se trata."),
 close=("Disable unused public network jacks and run the POI inventory and inspection programme.",
        "Desactivar las tomas de red publicas no usadas y ejecutar el programa de inventario e inspeccion de POI.")),
"7.9": dict(
 covers=("Assets used off-site protected: authorisation, encryption, custody.",
         "Activos usados fuera de las instalaciones protegidos: autorizacion, cifrado, custodia."),
 adds=("Req. 9.4.3 and 9.4.4 require media with cardholder data sent outside the facility to be logged, sent by secured courier or trackable means and approved by management, and 9.5 covers POI devices in the field; other assets used off-site are not a PCI subject.",
       "El req. 9.4.3 y el 9.4.4 exigen que los soportes con datos de tarjeta enviados fuera de las instalaciones se registren, se envien por mensajeria segura o medios rastreables y los apruebe la direccion, y el 9.5 cubre los dispositivos POI en campo; los demas activos usados fuera no son asunto de PCI."),
 close=("Keep a media shipment log with management approval and tracking numbers.",
        "Llevar un registro de envios de soportes con aprobacion de la direccion y numeros de seguimiento.")),
"7.12": dict(
 covers=("Cabling protected from interception, interference and damage.",
         "Cableado protegido frente a interceptacion, interferencias y danos."),
 adds=("Req. 9.2.2 restricts the use of publicly accessible network jacks (disabled, or enabled only when authorised); protection of cabling as such is not required.",
       "El req. 9.2.2 restringe el uso de las tomas de red accesibles al publico (desactivadas, o activadas solo con autorizacion); la proteccion del cableado como tal no se exige."),
 close=("Evidence the control over public network jacks; the rest is ISO only.",
        "Evidenciar el control sobre las tomas de red publicas; el resto es solo ISO.")),
"7.13": dict(
 covers=("Equipment maintained by authorised personnel with records and data protected during repair.",
         "Equipos mantenidos por personal autorizado con registros y datos protegidos durante las reparaciones."),
 adds=("Req. 9.5.1 requires an up-to-date list of POI devices, periodic inspection of their surfaces for tampering or substitution (with a frequency from a targeted risk analysis), and training of personnel to verify the identity of repair technicians and to report suspicious behaviour; maintenance of other equipment is not addressed.",
       "El req. 9.5.1 exige una lista actualizada de dispositivos POI, inspeccion periodica de sus superficies frente a manipulacion o sustitucion (con una frecuencia derivada de un analisis de riesgo dirigido), y formacion del personal para verificar la identidad de los tecnicos de reparacion y notificar comportamientos sospechosos; el mantenimiento de otros equipos no se trata."),
 close=("Add the technician-identity check and the POI inspection log to the maintenance procedure.",
        "Anadir al procedimiento de mantenimiento la comprobacion de identidad del tecnico y el registro de inspeccion de POI.")),
"8.1": dict(
 covers=("An endpoint policy: hardening, encryption, patching, malware protection, remote wipe, BYOD, user responsibilities.",
         "Una politica de dispositivos de usuario: bastionado, cifrado, parcheo, proteccion antimalware, borrado remoto, BYOD, responsabilidades del usuario."),
 adds=("Req. 12.2.1 requires an acceptable-use policy for end-user technologies with explicit approval by authorised parties and a list of products approved for use; 1.5.1 requires security controls on any device that connects to both untrusted networks and the CDE, configured so that users cannot alter them; 5.3 applies anti-malware to all in-scope endpoints. Disk encryption, remote wipe and BYOD conditions are not PCI requirements unless the device stores PAN.",
       "El req. 12.2.1 exige una politica de uso aceptable de las tecnologias de usuario con aprobacion explicita de las partes autorizadas y una lista de productos aprobados; el 1.5.1 exige controles de seguridad en todo dispositivo que se conecte a redes no confiables y al CDE, configurados de modo que el usuario no pueda alterarlos; el 5.3 aplica antimalware a todos los dispositivos en alcance. El cifrado de disco, el borrado remoto y las condiciones BYOD no son requisitos PCI salvo que el dispositivo almacene el PAN."),
 close=("Add the approved-products list to the endpoint policy and lock the host firewall configuration on devices that reach the CDE.",
        "Anadir la lista de productos aprobados a la politica de dispositivos y bloquear la configuracion del cortafuegos en los dispositivos que alcanzan el CDE.")),
"8.2": dict(
 covers=("Privileged access allocated restrictively, managed and its use controlled.",
         "Acceso privilegiado asignado de forma restrictiva, gestionado y con su uso controlado."),
 adds=("Req. 7.2.2 requires privileges assigned by job classification with least privilege, 7.2.3 documented approval by authorised personnel, 8.2.2 no shared or generic accounts except by exception with management approval and individual accountability, 8.6 strict control of application and system accounts, 8.4.1 MFA for all non-console administrative access to the CDE, and 10.2.1.2 logging of every action by a user with administrative access. ISO's control states the principle; PCI lists the mechanisms.",
       "El req. 7.2.2 exige privilegios asignados por clasificacion del puesto con minimo privilegio, el 7.2.3 aprobacion documentada por personal autorizado, el 8.2.2 sin cuentas compartidas o genericas salvo excepcion aprobada por la direccion con responsabilidad individual, el 8.6 control estricto de las cuentas de aplicacion y sistema, el 8.4.1 MFA para todo acceso administrativo no consola al CDE, y el 10.2.1.2 registro de toda accion de un usuario con acceso administrativo. El control ISO enuncia el principio; PCI enumera los mecanismos."),
 close=("Evidence documented approval for every admin account, MFA on admin access and complete admin-action logging.",
        "Evidenciar la aprobacion documentada de cada cuenta administrativa, MFA en el acceso administrativo y el registro completo de acciones administrativas.")),
"8.3": dict(
 covers=("Access to information and assets restricted according to the access control policy.",
         "Acceso a la informacion y los activos restringido segun la politica de control de acceso."),
 adds=("Req. 7.2 restricts access to system components and cardholder data by business need to know, with an access model defined per role; 7.3 requires an access control system that enforces it and is set to deny all by default; 3.4.1 requires PAN to be masked when displayed (at most the first six and last four digits) so that only personnel with a business need see the full PAN, and 3.4.2 blocks copying or relocating PAN via remote access. ISO's restriction is policy-driven; PCI prescribes the mechanism and the display rule.",
       "El req. 7.2 restringe el acceso a los componentes del sistema y a los datos de tarjeta por necesidad de conocer, con un modelo de acceso definido por rol; el 7.3 exige un sistema de control de acceso que lo aplique y este configurado para denegar todo por defecto; el 3.4.1 exige enmascarar el PAN al mostrarlo (como maximo los seis primeros y los cuatro ultimos digitos) de modo que solo el personal con necesidad de negocio vea el PAN completo, y el 3.4.2 bloquea copiar o mover el PAN mediante acceso remoto. La restriccion de ISO se basa en la politica; PCI prescribe el mecanismo y la regla de visualizacion."),
 close=("Document the role-based access model for the CDE, verify default-deny, and mask PAN on every screen and report.",
        "Documentar el modelo de acceso por roles del CDE, verificar la denegacion por defecto y enmascarar el PAN en toda pantalla e informe.")),
"8.4": dict(
 covers=("Access to source code and development tools restricted and logged.",
         "Acceso al codigo fuente y a las herramientas de desarrollo restringido y registrado."),
 adds=("Req. 7.2 restricts access to all system components by need to know; source code repositories are system components when they hold code for the CDE, but PCI does not single them out. The ISO control is more specific.",
       "El req. 7.2 restringe el acceso a todos los componentes del sistema por necesidad de conocer; los repositorios de codigo son componentes del sistema cuando contienen codigo del CDE, pero PCI no los singulariza. El control ISO es mas especifico."),
 close=("Include the code repositories in the six-monthly access review of 7.2.4.",
        "Incluir los repositorios de codigo en la revision semestral de accesos del 7.2.4.")),
"8.5": dict(
 covers=("Authentication proportionate to the access restriction, including multi-factor where warranted.",
         "Autenticacion proporcional a la restriccion de acceso, incluido el multifactor cuando esta justificado."),
 adds=("Req. 8.4.1 requires MFA for all non-console administrative access to the CDE, 8.4.2 for all access into the CDE by anyone (from March 2025), 8.4.3 for all remote access from outside the network; 8.5.1 fixes the configuration: no bypass except documented exceptions, at least two independent factor types, no factor accepted until all have been provided, and no indication of which factor failed. ISO leaves the authentication strength to a risk decision; PCI mandates MFA and its shape.",
       "El req. 8.4.1 exige MFA para todo acceso administrativo no consola al CDE, el 8.4.2 para todo acceso al CDE por cualquiera (desde marzo de 2025), el 8.4.3 para todo acceso remoto desde fuera de la red; el 8.5.1 fija la configuracion: sin elusion salvo excepciones documentadas, al menos dos tipos de factor independientes, ningun factor aceptado hasta que se han proporcionado todos, y sin indicar que factor fallo. ISO deja la fortaleza de la autenticacion a una decision de riesgo; PCI impone MFA y su forma."),
 close=("Roll out MFA to every access path into the CDE and verify the 8.5.1 configuration settings on the MFA system.",
        "Desplegar MFA en toda via de acceso al CDE y verificar los ajustes de configuracion del 8.5.1 en el sistema MFA.")),
"8.7": dict(
 covers=("Protection against malware combining technical controls with user awareness.",
         "Proteccion frente al malware que combina controles tecnicos con la concienciacion de los usuarios."),
 adds=("Req. 5.2 requires anti-malware on all system components except those documented as not at risk (evaluated periodically), covering all known types of malware; 5.3 requires it to be kept current, to perform periodic scans or continuous analysis, to generate retained audit logs, and to be impossible for users to disable or alter except by documented exception; 5.3.3 covers removable media; 5.4.1 requires automated anti-phishing mechanisms to detect and protect personnel. ISO's control sets none of those operating parameters.",
       "El req. 5.2 exige antimalware en todos los componentes del sistema salvo los documentados como no en riesgo (evaluados periodicamente), que cubra todos los tipos conocidos de malware; el 5.3 exige mantenerlo actualizado, realizar analisis periodicos o analisis continuo, generar registros de auditoria conservados, y que los usuarios no puedan desactivarlo ni alterarlo salvo excepcion documentada; el 5.3.3 cubre los soportes extraibles; el 5.4.1 exige mecanismos antiphishing automatizados que detecten y protejan al personal. El control ISO no fija ninguno de esos parametros operativos."),
 close=("Lock the anti-malware policy centrally, keep its logs 12 months, and deploy e-mail anti-phishing (DMARC, link and attachment scanning).",
        "Bloquear centralmente la politica del antimalware, conservar sus registros 12 meses y desplegar antiphishing de correo (DMARC, analisis de enlaces y adjuntos).")),
"8.8": dict(
 covers=("Vulnerability information obtained, exposure evaluated and measures taken.",
         "Informacion de vulnerabilidades obtenida, exposicion evaluada y medidas tomadas."),
 adds=("Req. 6.3.1 requires vulnerabilities to be identified from recognised sources and risk-ranked; 6.3.3 critical and high patches installed within one month of release, others per a targeted risk analysis; 11.3.1 internal scans at least every three months with high and critical findings resolved and rescanned; 11.3.2 external scans at least every three months by an Approved Scanning Vendor, passing, plus after significant changes. ISO's vulnerability management fixes no frequency, no assessor and no remediation deadline.",
       "El req. 6.3.1 exige identificar las vulnerabilidades de fuentes reconocidas y clasificarlas por riesgo; el 6.3.3 instalar los parches criticos y altos en el mes siguiente a su publicacion, el resto segun un analisis de riesgo dirigido; el 11.3.1 analisis internos al menos cada tres meses con los hallazgos altos y criticos resueltos y reanalizados; el 11.3.2 analisis externos al menos cada tres meses por un Approved Scanning Vendor, superados, mas tras cambios significativos. La gestion de vulnerabilidades de ISO no fija frecuencia, ni evaluador, ni plazo de remediacion."),
 close=("Contract an ASV for quarterly external scans, schedule quarterly internal scans and enforce the 30-day critical patch SLA.",
        "Contratar un ASV para los analisis externos trimestrales, programar analisis internos trimestrales y aplicar el SLA de 30 dias para parches criticos.")),
"8.10": dict(
 covers=("Information deleted when no longer needed, by approved methods, with records.",
         "Informacion borrada cuando ya no se necesita, por metodos aprobados, con registro."),
 adds=("Req. 3.2.1 requires a retention policy with a process, run at least every three months, to identify and securely delete stored account data that exceeds retention; 3.3.1 forbids storing sensitive authentication data (full track, CVV, PIN) after authorisation even if encrypted, and 3.3.2/3.3.3 restrict its storage before authorisation and by issuers. ISO deletes when 'no longer required'; PCI sets the quarterly cadence and an absolute prohibition for SAD.",
       "El req. 3.2.1 exige una politica de retencion con un proceso, ejecutado al menos cada tres meses, para identificar y borrar de forma segura los datos de cuenta almacenados que superen la retencion; el 3.3.1 prohibe almacenar datos sensibles de autenticacion (pista completa, CVV, PIN) tras la autorizacion aunque esten cifrados, y el 3.3.2/3.3.3 restringen su almacenamiento antes de la autorizacion y por parte de los emisores. ISO borra cuando 'ya no se requiere'; PCI fija la cadencia trimestral y una prohibicion absoluta para los SAD."),
 close=("Run and evidence a quarterly data-discovery and deletion job, and scan for SAD in logs, databases and backups.",
        "Ejecutar y evidenciar un trabajo trimestral de descubrimiento y borrado de datos, y buscar SAD en registros, bases de datos y copias.")),
"8.11": dict(
 covers=("Data masking, pseudonymisation or anonymisation applied per policy and law.",
         "Enmascaramiento, seudonimizacion o anonimizacion de datos aplicados segun la politica y la ley."),
 adds=("Req. 3.4.1 fixes the display mask — at most the first six and last four digits of PAN visible, and only to roles with a documented business need; 3.5.1 requires PAN to be rendered unreadable wherever stored by one of four methods: one-way hashes with a key, truncation, index tokens, or strong cryptography with key management; and 3.5.1.2/3.5.1.3 restrict disk-level encryption to removable media and require separate authentication for it. ISO's masking control leaves technique and scope open.",
       "El req. 3.4.1 fija la mascara de visualizacion — como maximo los seis primeros y cuatro ultimos digitos del PAN visibles, y solo para roles con necesidad de negocio documentada; el 3.5.1 exige que el PAN sea ilegible alli donde se almacene mediante uno de cuatro metodos: hash unidireccional con clave, truncado, tokens indice, o criptografia robusta con gestion de claves; y el 3.5.1.2/3.5.1.3 limitan el cifrado a nivel de disco a los soportes extraibles y exigen autenticacion separada para el. El control de enmascaramiento de ISO deja tecnica y alcance abiertos."),
 close=("Inventory every location where PAN is stored and the unreadability method applied, and enforce the 6/4 mask on all displays.",
        "Inventariar cada ubicacion donde se almacena el PAN y el metodo de ilegibilidad aplicado, y aplicar la mascara 6/4 en todas las pantallas.")),
"8.12": dict(
 covers=("Data-leakage prevention across endpoints, e-mail, web and cloud.",
         "Prevencion de fugas de datos en puestos, correo, web y nube."),
 adds=("Req. 3.4.2 requires technical controls that prevent copying or relocating PAN through remote-access technologies unless explicitly authorised, and 4.2.2 requires PAN sent by end-user messaging (e-mail, chat, SMS) to be protected with strong cryptography; there is no general DLP requirement. PCI asks for two precise leakage blocks, not a programme.",
       "El req. 3.4.2 exige controles tecnicos que impidan copiar o mover el PAN mediante tecnologias de acceso remoto salvo autorizacion explicita, y el 4.2.2 exige proteger con criptografia robusta el PAN enviado por mensajeria de usuario (correo, chat, SMS); no hay un requisito general de DLP. PCI pide dos bloqueos de fuga precisos, no un programa."),
 close=("Configure the DLP to block PAN patterns in outbound e-mail and chat, and disable clipboard and file transfer in remote sessions to the CDE.",
        "Configurar el DLP para bloquear patrones de PAN en correo y chat salientes, y desactivar el portapapeles y la transferencia de ficheros en las sesiones remotas al CDE.")),
"8.13": dict(
 covers=("Backups of information, software and systems taken and regularly tested per policy.",
         "Copias de seguridad de la informacion, el software y los sistemas realizadas y probadas regularmente segun la politica."),
 adds=("Req. 9.4.1.1 only requires offline backup media with cardholder data to be stored in a secure location, reviewed at least once every 12 months; and 3.5.1 applies to PAN in backups too (unreadable). Backup policy, frequency, testing and restoration are not PCI requirements, except that backups of audit logs count for 10.3.3.",
       "El req. 9.4.1.1 solo exige que los soportes de copia fuera de linea con datos de tarjeta se guarden en un lugar seguro, revisado al menos cada 12 meses; y el 3.5.1 se aplica tambien al PAN en las copias (ilegible). La politica de copias, su frecuencia, las pruebas y la restauracion no son requisitos PCI, salvo que las copias de los registros de auditoria cuentan para el 10.3.3."),
 close=("Confirm PAN is encrypted in backups and review the off-site storage location yearly.",
        "Confirmar que el PAN esta cifrado en las copias y revisar anualmente la ubicacion de custodia externa.")),
"8.15": dict(
 covers=("Logs of activities, exceptions, faults and events produced, stored, protected and analysed.",
         "Registros de actividades, excepciones, fallos y eventos generados, almacenados, protegidos y analizados."),
 adds=("Req. 10.2.1 lists the events that must be logged: every access to cardholder data, every administrative action, every access to audit logs, invalid access attempts, changes to credentials, initialisation or stopping of logs, and creation or deletion of system-level objects; 10.2.2 fixes the fields per entry (user, event type, date and time, success or failure, origin, affected resource); 10.3 protects logs (read access restricted, no modification, backed up to a central server, file integrity monitoring or change detection); 10.5.1 retains them 12 months, three online. ISO's logging control leaves all of that to the organisation.",
       "El req. 10.2.1 enumera los eventos que deben registrarse: todo acceso a datos de tarjeta, toda accion administrativa, todo acceso a los registros de auditoria, intentos de acceso invalidos, cambios en las credenciales, inicio o parada de los registros, y creacion o borrado de objetos a nivel de sistema; el 10.2.2 fija los campos de cada entrada (usuario, tipo de evento, fecha y hora, exito o fallo, origen, recurso afectado); el 10.3 protege los registros (lectura restringida, sin modificacion, copiados a un servidor central, monitorizacion de integridad o deteccion de cambios); el 10.5.1 los conserva 12 meses, tres en linea. El control de registro de ISO deja todo eso a la organizacion."),
 close=("Audit the log configuration of every CDE component against the 10.2 event and field list, centralise logs and put FIM on the log server.",
        "Auditar la configuracion de registro de cada componente del CDE contra la lista de eventos y campos del 10.2, centralizar los registros y poner FIM en el servidor de registros.")),
"8.16": dict(
 covers=("Networks, systems and applications monitored for anomalous behaviour, with response.",
         "Redes, sistemas y aplicaciones supervisados para detectar comportamientos anomalos, con respuesta."),
 adds=("Req. 10.4.1 requires daily review of security events, logs of CDE components and critical systems, and logs of security functions, with automated mechanisms (10.4.1.1); 10.4.2 periodic review of other logs per a targeted risk analysis; 10.7 detection and prompt response to failures of critical security controls; 11.5.1 intrusion detection or prevention at the CDE perimeter and critical points, kept current, with alerts; 11.5.2 a change-detection mechanism such as file integrity monitoring, compared at least weekly. ISO's monitoring control fixes none of those.",
       "El req. 10.4.1 exige revisar a diario los eventos de seguridad, los registros de los componentes del CDE y de los sistemas criticos, y los registros de las funciones de seguridad, con mecanismos automatizados (10.4.1.1); el 10.4.2 revision periodica de los demas registros segun un analisis de riesgo dirigido; el 10.7 deteccion y respuesta rapida a los fallos de los controles criticos; el 11.5.1 deteccion o prevencion de intrusiones en el perimetro del CDE y puntos criticos, actualizada, con alertas; el 11.5.2 un mecanismo de deteccion de cambios como la monitorizacion de integridad de ficheros, comparada al menos semanalmente. El control de seguimiento de ISO no fija nada de eso."),
 close=("Evidence the daily log review (SIEM reports), IDS/IPS coverage of the CDE perimeter and weekly FIM comparisons.",
        "Evidenciar la revision diaria de registros (informes del SIEM), la cobertura IDS/IPS del perimetro del CDE y las comparaciones semanales del FIM.")),
"8.18": dict(
 covers=("Privileged utilities inventoried, restricted, logged and removed where unnecessary.",
         "Utilidades privilegiadas inventariadas, restringidas, registradas y eliminadas cuando no son necesarias."),
 adds=("Req. 2.2.4 requires only necessary services, protocols, daemons and functions to be enabled and all unnecessary functionality removed or disabled; 7.2 restricts access by need. Privileged utilities are not a PCI concept; they are covered as unnecessary functions or as privileged access.",
       "El req. 2.2.4 exige que solo esten habilitados los servicios, protocolos, demonios y funciones necesarios y que toda funcionalidad innecesaria se elimine o desactive; el 7.2 restringe el acceso por necesidad. Las utilidades privilegiadas no son un concepto PCI; se cubren como funciones innecesarias o como acceso privilegiado."),
 close=("Reflect the utility restrictions in the configuration standards of 2.2.1.",
        "Reflejar las restricciones de utilidades en las normas de configuracion del 2.2.1.")),
"8.19": dict(
 covers=("Software installed on operational systems only through a controlled process.",
         "Software instalado en sistemas en produccion solo mediante un proceso controlado."),
 adds=("Req. 2.2.4 removes unnecessary software, 6.5.1 puts every change — including software installation — through change management with documented reason, approval, impact, testing and back-out, and 12.2.1 keeps a list of products approved for end-user use; PCI spreads the control across three requirements rather than stating it.",
       "El req. 2.2.4 elimina el software innecesario, el 6.5.1 pasa todo cambio — incluida la instalacion de software — por la gestion de cambios con motivo, aprobacion, impacto, pruebas y marcha atras documentados, y el 12.2.1 mantiene una lista de productos aprobados para el usuario; PCI reparte el control entre tres requisitos en lugar de enunciarlo."),
 close=("Reference the approved-products list and the change records as evidence for each requirement.",
        "Referenciar la lista de productos aprobados y los registros de cambio como evidencia de cada requisito.")),
"8.20": dict(
 covers=("Networks and network devices secured, managed and controlled.",
         "Redes y dispositivos de red protegidos, gestionados y controlados."),
 adds=("Req. 1.2.1 configuration standards for network security controls, 1.2.2 changes through change management, 1.2.3 an accurate network diagram and 1.2.4 a data-flow diagram of all account data flows, 1.2.5-1.2.6 every allowed service, protocol and port identified, approved and justified with insecure ones mitigated, 1.2.7 NSC rulesets reviewed at least every six months, 1.2.8 configuration files secured; 1.4 controls between trusted and untrusted networks, including anti-spoofing and no direct connections; 11.2.1 detection of authorised and unauthorised wireless access points at least every three months. ISO's network control is not prescriptive.",
       "El req. 1.2.1 normas de configuracion de los controles de seguridad de red, el 1.2.2 cambios por la gestion de cambios, el 1.2.3 un diagrama de red exacto y el 1.2.4 un diagrama de flujo de todos los datos de cuenta, los 1.2.5-1.2.6 cada servicio, protocolo y puerto permitido identificado, aprobado y justificado con los inseguros mitigados, el 1.2.7 reglas de los NSC revisadas al menos cada seis meses, el 1.2.8 ficheros de configuracion protegidos; el 1.4 controles entre redes de confianza y no confiables, incluido antispoofing y sin conexiones directas; el 11.2.1 deteccion de puntos de acceso inalambrico autorizados y no autorizados al menos cada tres meses. El control de seguridad de redes de ISO no es prescriptivo."),
 close=("Produce the network and data-flow diagrams, the justified port/protocol list, the six-monthly ruleset review record and the quarterly rogue-AP scan.",
        "Elaborar los diagramas de red y de flujo de datos, la lista justificada de puertos y protocolos, el registro de revision semestral de reglas y el analisis trimestral de puntos de acceso no autorizados.")),
"8.21": dict(
 covers=("Security mechanisms, service levels and requirements of network services identified and monitored, including outsourced ones.",
         "Mecanismos de seguridad, niveles de servicio y requisitos de los servicios de red identificados y supervisados, incluidos los externalizados."),
 adds=("Req. 1.2.5 and 1.2.6 require every service, protocol and port in use to be identified, approved, with a business justification, and the security features of insecure ones defined and implemented; 2.2.5 requires insecure services to be justified and mitigated, 2.2.7 non-console administrative access to be encrypted; the security of network services bought from telecoms or cloud providers falls under 12.8. PCI is about what runs on the wire; ISO about the service agreement.",
       "Los reqs. 1.2.5 y 1.2.6 exigen que cada servicio, protocolo y puerto en uso este identificado, aprobado, con justificacion de negocio, y que las caracteristicas de seguridad de los inseguros esten definidas e implantadas; el 2.2.5 exige justificar y mitigar los servicios inseguros, el 2.2.7 cifrar el acceso administrativo no consola; la seguridad de los servicios de red contratados a operadores o proveedores de nube cae bajo el 12.8. PCI trata de lo que corre por el cable; ISO del acuerdo de servicio."),
 close=("Maintain the approved services/ports/protocols register with justifications and treat network providers as TPSPs.",
        "Mantener el registro de servicios, puertos y protocolos aprobados con justificaciones y tratar a los proveedores de red como TPSP.")),
"8.22": dict(
 covers=("Groups of services, users and systems segregated in the network.",
         "Grupos de servicios, usuarios y sistemas segregados en la red."),
 adds=("Req. 1.3.1 and 1.3.2 restrict inbound and outbound traffic of the CDE to what is necessary, denying the rest; 1.4 controls connections between trusted and untrusted networks; segmentation is optional in PCI but, when used to reduce scope, 11.4.5 requires penetration tests of the segmentation controls at least every 12 months and after changes (11.4.6: every six months for service providers), covering all methods in use. ISO segregates networks; PCI demands proof that the segregation holds.",
       "Los reqs. 1.3.1 y 1.3.2 restringen el trafico entrante y saliente del CDE a lo necesario, denegando el resto; el 1.4 controla las conexiones entre redes de confianza y no confiables; la segmentacion es opcional en PCI pero, cuando se usa para reducir el alcance, el 11.4.5 exige pruebas de penetracion de los controles de segmentacion al menos cada 12 meses y tras cambios (11.4.6: cada seis meses para proveedores de servicios), cubriendo todos los metodos en uso. ISO segrega redes; PCI exige prueba de que la segregacion se mantiene."),
 close=("Document the segmentation design and commission the annual (or six-monthly) segmentation penetration test.",
        "Documentar el diseno de segmentacion y encargar la prueba de penetracion de segmentacion anual (o semestral).")),
"8.23": dict(
 covers=("Web access filtered against malicious and inappropriate sites.",
         "Acceso web filtrado frente a sitios maliciosos e inapropiados."),
 adds=("Req. 1.3.2 restricts outbound traffic from the CDE to what is necessary, which implies that CDE systems do not browse the web freely; filtering the web access of ordinary users is not a PCI requirement.",
       "El req. 1.3.2 restringe el trafico saliente del CDE a lo necesario, lo que implica que los sistemas del CDE no navegan libremente; filtrar el acceso web de los usuarios ordinarios no es un requisito PCI."),
 close=("Evidence that CDE systems have no unrestricted outbound web access.",
        "Evidenciar que los sistemas del CDE no tienen acceso web saliente sin restricciones.")),
"8.24": dict(
 covers=("Rules for the effective use of cryptography, including key management, defined and implemented.",
         "Reglas para el uso eficaz de la criptografia, incluida la gestion de claves, definidas e implantadas."),
 adds=("Req. 3.5.1 fixes how PAN is made unreadable at rest; 3.6.1 protects the keys (fewest custodians, key-encrypting keys as strong as the data keys, stored in fewest locations, in an HSM or with split knowledge); 3.7 requires documented key management covering generation, distribution, storage, cryptoperiods and rotation, retirement when compromised, split knowledge and dual control, no substitution, and a signed custodian acknowledgement; 4.2.1 requires strong cryptography and an inventory of trusted keys and certificates for PAN in transit, with expired or weak certificates and protocols excluded. ISO's cryptography control asks for a policy and key management in general; PCI dictates the mechanisms.",
       "El req. 3.5.1 fija como se hace ilegible el PAN en reposo; el 3.6.1 protege las claves (minimos custodios, claves de cifrado de claves tan robustas como las de datos, almacenadas en el minimo de ubicaciones, en un HSM o con conocimiento dividido); el 3.7 exige una gestion de claves documentada que cubra generacion, distribucion, almacenamiento, criptoperiodos y rotacion, retirada en caso de compromiso, conocimiento dividido y doble control, no sustitucion, y un reconocimiento firmado de los custodios; el 4.2.1 exige criptografia robusta y un inventario de claves y certificados de confianza para el PAN en transito, excluyendo certificados y protocolos caducados o debiles. El control de criptografia de ISO pide una politica y gestion de claves en general; PCI dicta los mecanismos."),
 close=("Write the key-management procedure per 3.7 with custodian acknowledgements, and build the certificate inventory of 4.2.1.1.",
        "Redactar el procedimiento de gestion de claves segun el 3.7 con reconocimientos de los custodios, y construir el inventario de certificados del 4.2.1.1.")),
"8.26": dict(
 covers=("Security requirements specified and approved for developed or acquired applications.",
         "Requisitos de seguridad especificados y aprobados para las aplicaciones desarrolladas o adquiridas."),
 adds=("Req. 6.2.4 requires engineering techniques against injection, data and structure attacks, cryptographic misuse, business-logic flaws and access control weaknesses; 6.4.1/6.4.2 require public-facing web applications to be protected by an automated technical solution that detects and prevents web attacks (a WAF) — mandatory since March 2025 — or reviewed at least annually and after changes; 11.6.1 requires a change- and tamper-detection mechanism on payment pages, checked at least weekly, alerting on unauthorised changes to HTTP headers and scripts. ISO's requirements control stops at design time.",
       "El req. 6.2.4 exige tecnicas de ingenieria frente a inyeccion, ataques a datos y estructuras, mal uso de la criptografia, fallos de logica de negocio y debilidades de control de acceso; los 6.4.1/6.4.2 exigen proteger las aplicaciones web expuestas con una solucion tecnica automatizada que detecte y evite ataques web (un WAF) — obligatoria desde marzo de 2025 — o revisarlas al menos anualmente y tras cambios; el 11.6.1 exige un mecanismo de deteccion de cambios y manipulacion en las paginas de pago, comprobado al menos semanalmente, que alerte de cambios no autorizados en cabeceras HTTP y scripts. El control de requisitos de ISO se detiene en la fase de diseno."),
 close=("Deploy a WAF in front of public payment applications and a script/header integrity monitor on payment pages.",
        "Desplegar un WAF delante de las aplicaciones de pago publicas y un monitor de integridad de scripts y cabeceras en las paginas de pago.")),
"8.27": dict(
 covers=("Documented secure architecture and engineering principles applied to every design.",
         "Principios documentados de arquitectura e ingenieria segura aplicados a todo diseno."),
 adds=("Req. 1.2.3 and 1.2.4 require current network and account-data-flow diagrams showing all connections between the CDE and other networks, and 6.2.4 concrete engineering techniques against common attack classes; PCI wants the drawings and the techniques, not a principles document.",
       "Los reqs. 1.2.3 y 1.2.4 exigen diagramas actualizados de red y de flujo de datos de cuenta que muestren todas las conexiones entre el CDE y otras redes, y el 6.2.4 tecnicas de ingenieria concretas frente a las clases de ataque comunes; PCI quiere los dibujos y las tecnicas, no un documento de principios."),
 close=("Keep the network and data-flow diagrams current and reference the engineering techniques in the development standard.",
        "Mantener actualizados los diagramas de red y de flujo de datos y referenciar las tecnicas de ingenieria en la norma de desarrollo.")),
"8.29": dict(
 covers=("Security testing processes defined and implemented in the development lifecycle.",
         "Procesos de pruebas de seguridad definidos e implantados en el ciclo de vida de desarrollo."),
 adds=("Req. 6.2.3 requires bespoke code to be reviewed before release by knowledgeable people other than the author, with corrections before deployment; 6.4 annual reviews or a WAF for public web applications; 11.3 quarterly internal and ASV external vulnerability scans; 11.4 internal and external penetration testing at least every 12 months and after significant change, following a documented industry-accepted methodology, covering the whole CDE perimeter and critical systems, application and network layers, with exploitable findings corrected and retested. ISO defines the testing process without frequencies, methodology or assessor independence.",
       "El req. 6.2.3 exige revisar el codigo a medida antes de la puesta en produccion por personas con conocimientos distintas del autor, con correcciones antes del despliegue; el 6.4 revisiones anuales o un WAF para las aplicaciones web publicas; el 11.3 analisis de vulnerabilidades trimestrales internos y externos por ASV; el 11.4 pruebas de penetracion internas y externas al menos cada 12 meses y tras cambios significativos, siguiendo una metodologia documentada aceptada por el sector, cubriendo todo el perimetro del CDE y los sistemas criticos, capas de aplicacion y red, con los hallazgos explotables corregidos y reprobados. ISO define el proceso de pruebas sin frecuencias, metodologia ni independencia del evaluador."),
 close=("Define the pen-test methodology document and calendar the annual test, the quarterly scans and the pre-release code reviews.",
        "Definir el documento de metodologia de pruebas de penetracion y calendarizar la prueba anual, los analisis trimestrales y las revisiones de codigo previas a la puesta en produccion.")),
"8.30": dict(
 covers=("Outsourced development directed, monitored and reviewed.",
         "Desarrollo externalizado dirigido, supervisado y revisado."),
 adds=("Req. 6.2 applies to bespoke and custom software whether developed in-house or by a third party (training, code review, engineering techniques), and 12.8 governs the provider relationship if it touches account data; supervising the external developer's process specifically is not addressed, and the entity remains responsible for the code's compliance.",
       "El req. 6.2 se aplica al software a medida tanto propio como de terceros (formacion, revision de codigo, tecnicas de ingenieria), y el 12.8 rige la relacion con el proveedor si toca datos de cuenta; supervisar especificamente el proceso del desarrollador externo no se trata, y la entidad sigue siendo responsable del cumplimiento del codigo."),
 close=("Put the 6.2 obligations (secure training, code review evidence) in the development contract and add the developer to the TPSP list if it accesses the CDE.",
        "Incluir las obligaciones del 6.2 (formacion en desarrollo seguro, evidencia de revision de codigo) en el contrato de desarrollo y anadir al desarrollador a la lista de TPSP si accede al CDE.")),
"8.32": dict(
 covers=("Changes to systems subject to change management procedures.",
         "Cambios en los sistemas sujetos a procedimientos de gestion de cambios."),
 adds=("Req. 6.5.1 fixes the content of every change record: reason and description, documented approval by authorised parties, functionality testing to verify security impact, and back-out procedures; 6.5.2 requires that, after any significant change, all applicable PCI requirements be confirmed on the affected components and documentation updated; 12.5.2 requires the scope to be re-validated after significant changes. ISO's change management does not tie changes to compliance re-validation.",
       "El req. 6.5.1 fija el contenido de cada registro de cambio: motivo y descripcion, aprobacion documentada por las partes autorizadas, pruebas funcionales que verifiquen el impacto en la seguridad, y procedimientos de marcha atras; el 6.5.2 exige que, tras cualquier cambio significativo, se confirmen todos los requisitos PCI aplicables en los componentes afectados y se actualice la documentacion; el 12.5.2 exige revalidar el alcance tras cambios significativos. La gestion de cambios de ISO no liga los cambios a la revalidacion del cumplimiento."),
 close=("Add a 'PCI impact' field and a post-change compliance checklist to the change ticket template.",
        "Anadir un campo 'impacto PCI' y una lista de comprobacion de cumplimiento posterior al cambio a la plantilla de ticket de cambio.")),
}
